### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - hist-spAer-all

### ISSUE THREAD

**Issue by Kirkevag** [NorESMhub/noresm2cmor#101]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**

/projects/NS9560K/noresm/cases/NHIST_spAer_f19_tn14_20190925

**experiment_id**
hist-spAer-all

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NHIST_spAer_f19_tn14_20190925, 1850-2014

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorwegianClimateCentre/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
piControl

**parent_experiment_rip**
e.g., r1i1p1
'no parent'

**parent_time_units**
'days since 1600-01-01'

**branch_method**
hybrid

**other information**
This Tier 1 experiment is central in the RFMIP SpAer paper with deadline ca. now,
so please give this first priority.

**Comment by YanchunHe** [comment]
Cmorized and ready to publish @monsieuralok 

**data path**
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/hist-spAer-all/r1i1p1f1

**version**
- v20190920

**sha256sum**
- .r1i1p1f1.sha256sum_v20190920

**commit**
- 0b437bc83c5dd683522665098394d8b723953fba

**NOTE: Please set this experiment with HIGH priority to publish to ESGF!!**

**Comment by Kirkevag** [comment]
Thanks a lot, Yanchun and Alok!

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
- /tos-project1/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/hist-spAer-all

**data version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@Kirkevag @YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #271, #272 and #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/hist-spAer-al
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/hist-spAer-al

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/hist-spAer-al
- .r1i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published
