### ISSUE TITLE
Add CMIP6_6hrLev/6hrPlev/6hrPlevPt tables

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#109]
##  Fields in  6hr-averaged output  (`cam.h2`)
The Following fields are now supported:
```
                 'bldep       ','PBLH          ','          ',
                 'hurs        ','RHREFHT       ','percent   ',
                 'hus4        ','Q             ','          ',
                 'pr          ','PRECT         ','kg m-2 s-1',
                 'psl         ','PSL           ','          ',
                 'sfcWind     ','U10           ','          ',
                 'tas         ','TREFHT        ','          ',
                 'wap4        ','OMEGA         ','          ',
                 'zg1000      ','Z1000         ','          ',
```

The Following fields are not available in the model output:
```
!                'bs550aer    ','BS550AER/DAYFOC','DAYFOC   ',
!                'uas         ','UAS           ','          ',
!                'vas         ','VAS           ','          ',
```

## Fields in  6hr-instantaneous output (`cam.h3`)
The Following fields are now supported:
```
                 'hus         ','Q             ','          ',
                 'ps          ','PS            ','          ',
                 'ta          ','T             ','          ',
                 'ua          ','U             ','          ',
                 'va          ','V             ','          ',
                 'hus27       ','Q             ','          ',
                 'huss        ','QREFHT        ','          ',
                 'psl         ','PSL           ','          ',
                 'sfcWind     ','U10           ','          ',
                 'ta          ','T             ','          ',
                 'tas         ','TREFHT        ','          ',
                 'ts          ','TS            ','          ',
                 'ua          ','U             ','          ',
                 'va          ','V             ','          ',
                 'zg27        ','Z3            ','          ',
                 'zg500       ','Z500          ','          ',
```

The Following fields are not available in the model output:
(**6hr output from land model is totally missing**)
(mrsol, mrsos,snw should come from clm output)

```
!                'mrsol       ','SOILLIQ+SOILICE','         ',
!                'mrsos       ','SOILWATER_10CM','          ',
!                'snw         ','SNOWICE+SNOWLIQ','         ',
!                'tsl         ','TSL           ','          ',
```

**Sample output**
 -  /scratch/yanchun/cmorout/NorESM2-LM/historical/v20190815/6hr
```
bldep_6hrPlev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
hurs_6hrPlev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
hus_6hrLev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
hus_6hrPlev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
hus_6hrPlevPt_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
huss_6hrPlevPt_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
pr_6hrPlev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
ps_6hrLev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
psl_6hrPlev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
psl_6hrPlevPt_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
sfcWind_6hrPlev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
sfcWind_6hrPlevPt_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
ta_6hrLev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
ta_6hrPlevPt_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
tas_6hrPlev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
tas_6hrPlevPt_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
ts_6hrPlevPt_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
ua_6hrLev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
ua_6hrPlevPt_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
va_6hrLev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
va_6hrPlevPt_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
wap_6hrPlev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
zg1000_6hrPlev_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
zg500_6hrPlevPt_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
zg_6hrPlevPt_NorESM2-LM_historical_r1i1p1f1_gn_201001010300-201001312100.nc
```

**Commit**
- 5a63a93

UPDATED: 30 OCT 2019, correct 6 hourly average and instantaneous file streams. 
commit: 210389a, 8df4e53

**Comment by OskarMETNO** [comment]
Is it really correct that the instantaneous fields (6hrLev) have timestamps at 03h, 09h, 15h and 21h? Shouldn't it be 00/06/12/18? Or has this changed from CMIP5 to CMIP6?

**Comment by YanchunHe** [comment]
First of all, the 6hourly instantaneous fields are those has tag '6hrPlevPt" instead of 6hrLev (which is 6hourly average).

I checked the LM historical run, as an example, the model output should indeed has time tag at 00/06/12/18:
ncdump -v time -t NHIST_f19_tn14_20190710.cam.h3.1959-10-20-21600.nc
...
    "1959-12-29 06", "1959-12-29 12", "1959-12-29 18", "1959-12-30",
    "1959-12-30 06", "1959-12-30 12", "1959-12-30 18", "1959-12-31",
    "1959-12-31 06", "1959-12-31 12", "1959-12-31 18", "1960-01-01" ;

While in the cmorized data:
ncdump -t -v time hus_6hrPlevPt_NorESM2-LM_historical_r1i1p1f1_gn_195001010300-195912312100.nc
    "1959-12-30 03", "1959-12-30 09", "1959-12-30 15", "1959-12-30 21",
    "1959-12-31 03", "1959-12-31 09", "1959-12-31 15", "1959-12-31 21" ;
They are tagged at 03/09/15 and 21.

The time information is read from the model output and the output file tag is determined by the CMOR library. I have not touched this part of the cmorization tool, so I have now no clear idea about the mechanism in cmor library.

If the noresm2cmor tool has done something before passing to the cmor library?

@IngoBethke , maybe you have some impression and can recall on this?

btw, I see some other modelling groups use the tool 'nctime' to quality-check the time-axis of the cmorized data (https://github.com/Prodiguer/nctime).

@monsieuralok , is it possible to install and run this tool for the cmorized NorESM2 data too? Look like a simple tool.

**Comment by OskarMETNO** [comment]
I thought 6hrLev is supposed to be instantaneous.
In the metadata it says 
  ta:cell_methods = "area: mean time: point"
At least for CORDEX-MIP (where a lot of these variables are requested) it would make more sense to have instantaneous values to be used for dynamical downscaling.

**Comment by YanchunHe** [comment]
Sorry for the late response!

I have a typo above. Yes, the 6hrLev should be 6-hr instantaneous on altitude heights, and 6hrPlev is 6-hr average on Pressure levels, and 6hrPlevPt is instantaneous on Plevels.

Actually, there is a 6-hourly average variable, bs550aer,on levels (6hrLev) in CMIP6, but it is not available from NorESM2 output, so there is not actually cmorized.

**Comment by YanchunHe** [comment]
I see that the time stamps is shifted from 0/6/12/18 to 3/9/15/21. This is very likely done in our noresm2cmor implementation, that the time values is used as the average of the first time slice and the last time slice. Something like:
```fortran
tval=0.5*(tbnds(1,1)+tbnds(2,1))
```

I may fix this in the future release.

Is this very important to republish new data version of published experiment? or we can just create an ESGF known-issue?

**Comment by YanchunHe** [comment]
This has been fixed in commit: 9ef437e91df26aab0f52c7a8e32d81f484c59975

The 3hrly and 6hourly data of NorESM2-LM historical will be reprocessed with data version v20200218, and be published to ESGF later.

Will not reprocess published data.

Now the timestamp for 6hr instantaneous is like:
    "1950-01-29 06", "1950-01-29 12", "1950-01-29 18", "1950-01-30", 
    "1950-01-30 06", "1950-01-30 12", "1950-01-30 18", "1950-01-31", 
    "1950-01-31 06", "1950-01-31 12", "1950-01-31 18", "1950-02-01" ;
and for 3hr instantaneous data is like:
    "1950-01-30 15", "1950-01-30 18", "1950-01-30 21", "1950-01-31", 
    "1950-01-31 03", "1950-01-31 06", "1950-01-31 09", "1950-01-31 12", 
    "1950-01-31 15", "1950-01-31 18", "1950-01-31 21", "1950-02-01" ;

**Comment by YanchunHe** [comment]
data will be found under: /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical/v20200218

**Comment by YanchunHe** [comment]
fixed in commit: 9ef437e

Data of above referred experiments were cmorized with correct time stamp, and are published to ESGF.

**Comment by YanchunHe** [comment]
by Ø.Seland: (issue #307)

Fields in 6hr-instantaneous output (cam.h3) in `CMIP6_6hrPlevPt`

'snowmxrat      ','QSNOW

**Comment by maosier** [comment]
The files in the  NorESM2-MM historical runs almost start at 03, 09, 15, 21 UTC, while the same output in the NorESM2-MM ssp runs start at 00, 06, 12, 18 UTC. I'm wondering the historical run is only a timestamp error and the data is actually correct, or the timestamp and data are both at the 03, 09, 15, 21 UTC?

**Comment by yfa008** [comment]
After reading the discussions above, I am surprised that the surface air temperature and humidity variables (tas, huss etc.) published on ESGF (huss_6hrPlevPt, tas_6hrPlevPt,  tas_6hrPlev, ps_6hrLev etc.) were labeled as having been interpolated to pressure levels. They should correspond to the original variables TREFHT and QREFHT in the .cam.h5.* history files, which were calculated by the model with reference to 2-m height above the ground. The original data of TREFHT and QREFHT should be directly renamed to tas and huss according to CMIP6 definition of these surface climate variables. Why did they need to be interpolated to pressure levels? Or are 6hrPlevPt and 6hrPlev just mis-labels?

**Comment by YanchunHe** [comment]
`tas`, `hurs` (correpsonds to TREFHT and QREFHT) are not available  in *.h4. (3hourly average) files, so they can not be cmorized.

I will close this issue if no other comments.

**Comment by yfa008** [comment]
Hi Yanchun, thanks for looking into this and your reply.
how about 6hourly tas, hurs or huss. Are they available? If so, it would be
a valuable addition to the impact research community who look at sub-daily
patterns.

Yuanchao

------------------------------
Yuanchao Fan
Assistant Professor
Institute of Environment and Ecology
Tsinghua Shenzhen International Graduate School

Tsinghua University

Shenzhen 518055, China
email: ***@***.***
tel: +86 18026984060

**Comment by YanchunHe** [comment]
> 

Yes, 6-hourly `tas`, `hurs` are already cmorized and available under the `6hrPlev` `table_id`.

**Comment by YanchunHe** [comment]
> @monsieuralok
> 
> Could you please report an Erratum for all the '6hrLev' and '6hrPlevPt', datasets earlier than v202018, that the time stamp should be shift 3 hours to more recent. E.g, shift 03:00/09:00/15:00/21:00 to 06:00/12:00/18:00/24:00.
> 
> For the 3 hourly data, you can report that for all the frequency of '3hrPt' , the time stamp should also be increased by 1.5 hours. The frequency '3hr' is not affected.

OK, there is summary and correction to 3hourly data:

**For the 6-hourly data:**
1. for `6hrLev` and `6hrPlevPt`, of data version earlier than v20200218, the time should be shifted by 3 hours. This should be reported in the Erratum.
2. The '6hrPlev' dataset has been always, before or after v20200218, using the averaged time for each averaging period. This is intended but may be changed in the future (e.g., for CMIP7). 

**For 3 hourly data**
1. For the `CF3hr` and `E3hrPt` datasets, versions before v20200218 should be shifted by 3 hours. This should be reported in the Erratum.
2. for `E3hr`, averaged time is used, and no correction is needed.
3. for `3hr` datasets,  the fields should be treated separately. More specifically:
* Fields at certain time points within the 3 hourly sampling are affected in versions earlier than v2020218, including
   - huss 
   - mrsos
   - ps
   - tas
   - tslsi
This should be reported in the Erratum.
* other fields on 3 hourly time average are not affected. 
   - mrro
   - pr  
   - prc 
   - prsn

**Comment by monsieuralok** [comment]
@YanchunHe does it includes also datasets version v20200218  for 6hrLev and 6hrPlevPt ? or only all version before v20200218 ?

**Comment by monsieuralok** [comment]
@YanchunHe https://errata.ipsl.fr/static/view.html?uid=97352b25-4e4b-4a1a-a5a0-d28c32c0cc87
 https://errata.ipsl.fr/static/view.html?uid=5fb6c827-3ecb-3b98-8c71-9beaae70a847 
Opened for 6hrLev, 6hrPlevPt CF3hr and E3hrPt
You can check it and will open for 3hr and alert for 'E3hr and 6hrPlev'

**Comment by YanchunHe** [comment]
> @YanchunHe https://errata.ipsl.fr/static/view.html?uid=97352b25-4e4b-4a1a-a5a0-d28c32c0cc87 https://errata.ipsl.fr/static/view.html?uid=5fb6c827-3ecb-3b98-8c71-9beaae70a847 Opened for 6hrLev, 6hrPlevPt CF3hr and E3hrPt You can check it and will open for 3hr and alert for 'E3hr and 6hrPlev'

Looks good. Thanks!

**Comment by monsieuralok** [comment]
@YanchunHe https://errata.ipsl.fr/static/view.html?uid=0193293b-e2ef-3935-bb6f-b8ec9f5f5603 I have create issue for Alert you can check.

**Comment by YanchunHe** [comment]
> @YanchunHe https://errata.ipsl.fr/static/view.html?uid=0193293b-e2ef-3935-bb6f-b8ec9f5f5603 I have create issue for Alert you can check.

Looks good to me. Thanks!
