### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - hist-aer (realization 1)

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#117]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases

**experiment_id**
hist-aer

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
N1850aeroxidonly_f19_tn14_20190805, 1850-1949
N1850aeroxidonly_f19_tn14_20190815, 1950-2014
NSSP245frc2aeroxidonly_f19_tn14_20191015, 2015-2020

### Optional information

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 0421-01-01'

**branch_method**
'Hybrid-restart from year 1600-01-01 of piControl'

**other information**
The full simulation consists of three experiments.  The time counting in the files is different between the first two experiments and the third experiment.  This is because the last period has started as a hybrid from the second period.
The period 1850-1949 : time:units = days since 1850-01-01 00:00:00
The period 1950-2014 : time:units = days since 1850-01-01 00:00:00
The period 2015-2020 : time:units = days since 2015-01-01 00:00:00

**Comment by YanchunHe** [comment]
CMORized and ready to publish

**data path**
- /tos-project1/NS9034K/CMIP6/DAMIP/NCC/NorESM2-LM/hist-aer/r1i1p1f1

**version**
- v20190920

**sha256sum**
- .r1i1p1f1.sha256sum_v20190920

Commit: 776ee272e0b3e36208ee6eb93cbbc18657990639

**Comment by monsieuralok** [comment]
@DirkOlivie @YanchunHe published

**Comment by adagj** [comment]
Hi,
srfWind is not present in 
/projects/NS9034K/CMIP6/DAMIP/NCC/NorESM2-LM/hist-aer/r1i1p1f1/

or on esgf

(but it is cmorized)

**Comment by YanchunHe** [comment]
cmorized with additional fields, and can be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/DAMIP/NCC/NorESM2-LM/hist-aer
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/hist-aer

**version**
- v20191108b

**sha256sum**
/projects/NS9034K/CMIP6/DAMIP/NCC/NorESM2-LM/hist-aer
- .r1i1p1f1.sha256sum_v20191108b

(A note, quality-check by PrePARE shows some warning/errors in some variables for their 'long_names' in Emon. That is caused the changes of CMOR libraries from 3.5.0 to 3.6.0. The data was cmorized with cmor 3.5.0, but currently quantity-check by cmor3.6.0. These warning are not critical).

**Comment by YanchunHe** [comment]
Realize that I should have further check on the integrity of the data. Please suspend the publish process.

**Comment by YanchunHe** [comment]
All fixed and now is ready to be published @monsieuralok

**Comment by monsieuralok** [comment]
@YanchunHe @DirkOlivie published

**Comment by YanchunHe** [comment]
@DirkOlivie @monsieuralok @IngoBethke,

Just FYI and to keep a track,

Some extension for this experiment will be done, and  a new datasets (will new version) will be publish to ESGF . Ingo is in charge of this.

Please, any of you, close this issue when this is settled/done.

**Comment by YanchunHe** [comment]
I assume that this has been resolved. I close it now. Reopen if needed.
