### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - hist-aer (realisation 3)

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#119]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS2345K/noresm/cases (for N1850aeroxidonly_03_f19_tn14_20190913)
/projects/NS9560K/noresm/cases (for NSSP245frc2aeroxidonly_03_f19_tn14_20191015)

**experiment_id**
hist-aer

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
N1850aeroxidonly_03_f19_tn14_20190913, 1850-2014
NSSP245frc2aeroxidonly_03_f19_tn14_20191015, 2015-2020

### Optional information

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 0421-01-01'

**branch_method**
'Hybrid-restart from year 1661-01-01 of piControl'

**other information**
realisation = 3
The full simulation consists of two experiments.  The time counting in the files is different between the first and the second experiment.  This is because the second period has started as a hybrid from the first period.
The period 1850-2014 : time:units = days since 1850-01-01 00:00:00
The period 2015-2020 : time:units = days since 2015-01-01 00:00:00

**Comment by YanchunHe** [comment]
CMORized and ready to publish

**data path**
- /tos-project1/NS9034K/CMIP6/DAMIP/NCC/NorESM2-LM/hist-aer/r3i1p1f1

**version**
- v20190920

**sha256sum**
- .r3i1p1f1.sha256sum_v20190920

Commit: 776ee272e0b3e36208ee6eb93cbbc18657990639

**Comment by monsieuralok** [comment]
@YanchunHe @DirkOlivie published

**Comment by adagj** [comment]
Hi,
srfWind is not present in 
/projects/NS9034K/CMIP6/DAMIP/NCC/NorESM2-LM/hist-aer/r1i1p1f1/

or on esgf

(but it is cmorized)

**Comment by YanchunHe** [comment]
cmorized with additional fields, and can be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/DAMIP/NCC/NorESM2-LM/hist-aer
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/hist-aer

**version**
- v20191108b

**sha256sum**
/projects/NS9034K/CMIP6/DAMIP/NCC/NorESM2-LM/hist-aer
- .r3i1p1f1.sha256sum_v20191108b

(A note, quality-check by PrePARE shows some warning/errors in some variables for their 'long_names' in Emon. That is caused the changes of CMOR libraries from 3.5.0 to 3.6.0. The data was cmorized with cmor 3.5.0, but currently quantity-check by cmor3.6.0. These warning are not critical).

**Comment by YanchunHe** [comment]
Realize that I should have further check on the integrity of the data. Please suspend the publish process.

**Comment by YanchunHe** [comment]
ready for publish now @monsieuralok

**Comment by monsieuralok** [comment]
r1 is having a less number of field is that OK?

**Comment by YanchunHe** [comment]
All other hist-* experiments have less fields in r1, so I believe this is normal. One has changed the setting from 1950 of r1 experiments. Please go ahead with publish. thanks!

**Comment by DirkOlivie** [comment]
@monsieuralok @YanchunHe 
For r1, I am aware of the following : the first part of this simulation, i.e. years 1850-1949 (N1850aeroxidonly_f19_tn14_20190805) has indeed been configured with fewer output fields than the next period 1950-2014 (N1850aeroxidonly_f19_tn14_20190805), or than r2 and r3.  This first r1 simulation has been setup with --user-mods-dir cmip6_noresm_DECK, while all the other simulations have been setup with --user-mods-dir cmip6_noresm_xaer (creating e.g., more aerosol-related output).

**Comment by YanchunHe** [comment]
> @monsieuralok @YanchunHe
> For r1, I am aware of the following : the first part of this simulation, i.e. years 1850-1949 (N1850aeroxidonly_f19_tn14_20190805) has indeed been configured with fewer output fields than the next period 1950-2014 (N1850aeroxidonly_f19_tn14_20190805), or than r2 and r3. This first r1 simulation has been setup with --user-mods-dir cmip6_noresm_DECK, while all the other simulations have been setup with --user-mods-dir cmip6_noresm_xaer (creating e.g., more aerosol-related output).

Thanks @DirkOlivie , for the explanation!

Yanchun

**Comment by monsieuralok** [comment]
@YanchunHe @DirkOlivie published

**Comment by YanchunHe** [comment]
@DirkOlivie @monsieuralok @IngoBethke,

Just FYI and to keep a track,

Some extension for this experiment will be done, and  a new datasets (will new version) will be publish to ESGF . Ingo is in charge of this.

Please, any of you, close this issue when this is settled/done.

**Comment by YanchunHe** [comment]
I assume that this has been resolved. I close it now. Reopen if needed.
