### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - piControl

### ISSUE THREAD

**Issue by ChunchengGuo** [NorESMhub/noresm2cmor#122]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/projects/NS9560K/noresm/cases

**experiment_id**
piControl

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
N1850_f19_tn14_20190802, 1901-2100

### Optional information

**parent_experiment_id**
piControl-spinup

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 0421-01-01'

**branch_method**
'branch-restart from year 1600-01-01 of piControl-spinup',

**other information**
@YanchunHe @monsieuralok 
you were on cc of the email earlier: we have only 300 years of NorESM2-LM data on ESGF, and therefore are missing 200 years. This opened issue is for these extra 200 years :)

**Comment by YanchunHe** [comment]
This extra 200 years have been cmorized and can be published.

**data path**
- /tos-project1/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl

**version**
- v20190920

**sha256sum**
- .r1i1p1f1.sha256sum_v20190920

**Note**
Since this is an extension of v20190920, you may need to retract the published data and then republish all of this version again.

**Comment by monsieuralok** [comment]
@YanchunHe  Hi,
       I have checked for variable abs550aer; it is exists only from 1700-2100 years not from 1600-2100 years. Please can you check?

**Comment by YanchunHe** [comment]
As I can see,  abs550aer is not available during 1600-1709. @oyvindseland  may know more about this.

If this is true, please just ignore this.

**Comment by YanchunHe** [comment]
I am also doing the cmorization for piControl with additional fields. But it is keep having annoying weird errors like:
```
138063 Bus error               (core dumped) nohup ./noresm2cmor3 ${nmlroot}/sys${project}.nml ${nmlroot}/mod.nml ${nmlroot}/exp_${year1}-${year2}${real}.nml ${nmlroot}/var.nml > ${logroot}/${year1}-${year2}${real}.log 2> ${logroot}/${year1}-${year2}${real}.err
```

Looks like some thing wrong with read/write.

I have to look into this later.

**Comment by monsieuralok** [comment]
@oyvindseland @ChunchengGuo Could you reply about above mentioned variable abs550aer which is available only from 1700-2100 not from 1600-2100

**Comment by YanchunHe** [comment]
@monsieuralok. I think you can go ahead with the publishing with abs550aer.

But there are indeed a problem of the versions of the this experiments.

The already published parts has data version v20190815, and a few fields has version v20190909.

Now the cmorized part has version v20190920.

Maybe we should rename the current version to v20190815 and v20190909 so that for a single fileld, it has whole record (if available) from 1600-2100?

**Comment by monsieuralok** [comment]
@YanchunHe all other variables are already published except  abs550aer  with renamed version name v20190920

**Comment by YanchunHe** [comment]
OK, let it be. You can publish available sets of abs550aer as well.

**Comment by monsieuralok** [comment]
@ChunchengGuo @YanchunHe published

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
-

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
- /tos-project1/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@ChunchengGuo @YanchunHe published

**Comment by YanchunHe** [comment]
quote (R. Petrie)
>There appear to be two sftgif files with the same name in the dataset CMIP6.CMIP.NCC.NorESM2-LM.piControl.r1i1p1f1.fx.sftgif.gn.v20190920 as this is not permitted please can you resolve this issue, retract the dataset and issue this with a new version number.

I checked this, and there are indeed two files tagged with v20190920.

However,  one file is actually pointing to v20190815.
http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/CMIP/NCC/NorESM2-LM/piControl/r1i1p1f1/fx/sftgif/gn/v20190920/sftgif_fx_NorESM2-LM_piControl_r1i1p1f1_gn.nc
http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/CMIP/NCC/NorESM2-LM/piControl/r1i1p1f1/fx/sftgif/gn/v20190815/sftgif_fx_NorESM2-LM_piControl_r1i1p1f1_gn.nc

@monsieuralok ,  please check this issue and fix.

Maybe also need check sftlf, orog and areacella.

Thanks!

<img width="906" alt="sftgif" src="https://user-images.githubusercontent.com/1725351/98244081-2525d780-1f6f-11eb-92f8-8862f2256f7e.png">

**Comment by monsieuralok** [comment]
@YanchunHe Rightnow ERRATA (certificate problem it would take time support mentioned) is not working and as a rule before retract data we should open a issue.  I will wait for ERRATA to work.

**Comment by monsieuralok** [comment]
Open errata issue https://errata.es-doc.org/static/view.html?uid=c2240480-bf2b-9ebf-9441-6260bbe272c8 soon will retract files.

**Comment by monsieuralok** [comment]
@YanchunHe I am planning to retract files then, these files we should publish with new version and what should be the name of this version? 20190920b or ..?

**Comment by YanchunHe** [comment]
Hi @monsieuralok , yes, I think you can simply republish as v20190920. thanks!

**Comment by YanchunHe** [comment]
Alok, @monsieuralok

There are three steps to republish the data.

1, you retract all the NorESM2-LM piControl data. Please indicate here when this is done.

2, then I will proceed with some necessary post-processing, and will update here

3, you will finally republish all the data.

**Comment by monsieuralok** [comment]
@YanchunHe started retracting process. It would be good to create new shasum file so we can publish soon..

**Comment by YanchunHe** [comment]
I will prepare for that. Will my reorganization of the data files local on NIRD affect the retract process? If no, I will start create new sha256sum soon.

**Comment by monsieuralok** [comment]
@YanchunHe I really do not know. I will update once it retracted and We would do one by one issue as suddenly server becomes very slow and if I retract all data and not able to publish for couple of weeks it would be bad. So, I will always update once I remove one experiment.

**Comment by YanchunHe** [comment]
OK, then the safest way is that you retract data one by one experiment, update here, and then I update the sha256sum.

**Comment by monsieuralok** [comment]
@YanchunHe I retracted all data from this experiment.

**Comment by YanchunHe** [comment]
Merged all versions and can be republished to ESGF.

**data path**
- /tos-project1/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piControl

**version**
- v20210118

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl
- .r1i1p1f1.sha256sum_v20210118

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
Cmorized with additional iLAMB variables (#262), AERday zg500 (#263) and corrected `fNup` (#251).

They are ready to be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piControl/v20210203
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl

**version**
- v20210203

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl
- .r1i1p1f1.sha256sum_v20210203

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270 #271 #272  #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piControl
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl
- .r1i1p1f1.sha256sum_v20210319

Note, dust variables in AERmon are only available after year 1710

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
Recmorize `sftlf` and `sftgif` related to issue #162
need to be published

**data path**

- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piControl
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl

**version**

- v20191108

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl
- .r1i1p1f1.sha256sum_v20191108c

**Comment by monsieuralok** [comment]
@YanchunHe published
