### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - piClim-aer

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#145]
(this has been cmorzied earlier with version v20190815 etc)

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
- /tos-project1/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-aer/r1i1p1f1/

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@Kirkevag @YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #271, #272 and #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-aer
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-aer

**version**
- v20210319

**sha256sum**
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-aer
- .r1i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published
