### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM -piClim-control

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#147]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases/NF1850norbc_f19_20190727

**experiment_id**
e.g., piClim-control

**model_id**
e.g.,
NorESM2-LM

**CASENAME(s) and years to be CMORized**
e.g., 
NF1850norbc_f19_20190727, 1-30

### Optional information
**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1

**Comment by YanchunHe** [comment]
Hi Dirk, @ DirkOlivie would you open read permission to this experiment, so that I can redo cmorization with additional fields. Thanks!
Yanchun

**Comment by DirkOlivie** [comment]
Hi Yanchun, @YanchunHe I have modified the permissions of NF1850norbc_f19_20190727.  Best regards, Dirk

**Comment by YanchunHe** [comment]
Thanks, Dirk!

**Comment by Kirkevag** [comment]
Hi Yanchun,

some of the fields (rsutaf, rsutcsaf, rlutaf and rlutcsaf) for this particular experiment have been requested for an ongoing RFMIP paper. Would it be possible to give this a high priority (CMOR and ESGF)?

 Best,

 - Alf

**Comment by YanchunHe** [comment]
Hi Alf,

There is already a long queue  to be cmorized for the existing and newly coming experiments. but piClim-control will be one of the next experiments to be processed.

I will try to put this to high priority.

Yanchun

**Comment by Kirkevag** [comment]
Very good. Thank you, Yanchun!

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
- /tos-project1/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-control

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@YanchunHe @Kirkevag published

**Comment by Kirkevag** [comment]
Thank you, Yanchun and Alok!

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #271, #272 and #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-control
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-control

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-control
- .r1i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published
