### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - hist-piAER, realisation 1

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#148]
cmorized with additional fields

**datapath**
- /tos-project1/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/hist-piAer/r1i1p1f1/

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@YanchunHe @oyvindseland

**Comment by YanchunHe** [comment]
cmorized with additional fields.

**data path**
- /tos-project1/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/hist-piAer/r1i1p1f1/

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@YanchunHe @oyvindseland published

**Comment by YanchunHe** [comment]
Cmorized with additional iLAMB variables (#262), AERday `zg500` (#263) and corrected `fNup` (#251).

They are ready to be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/hist-piAer
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/hist-piAer

**version**
- v20210203

**sha256sum**
/projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/hist-piAer
- .r1i1p1f1.sha256sum_v20210203

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #271, #272 and #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/hist-piAer
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/hist-piAer

**version**
- v20210319

**sha256sum**
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/hist-piAer
- .r1i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published
