### ISSUE TITLE
Possible bug in cmorized fx variable sftlf 

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#162]
Hi

I noticed that sftlf does look not the land/sea mask like the variable landfrac in the atmospheric model i.e. "Percentage of the grid  cell occupied by land (including lakes)"

but more like

"Percentage of the grid  cell occupied by land (excluding lakes)"

Should the variable  be equal to landfrac or is it a question of definition of the word excluding / including.

The equivalent CMIP5 variable looks identical to LANDFRAC

**Comment by YanchunHe** [comment]
According to the CMIP6 data request sheet, `LANDFRAC` is used to get `sftlf` without any extra modifications.

`LANDFRAC` is from grid file `
/projects/NS9560K/cmor/griddata/grid_atm_1.9x2.5_tnx1v4.nc`

I have not examined and have no idea if the 'LANDFRAC' includes lakes or not.

**Comment by YanchunHe** [comment]
Could you check if there are possible fixes to this? if this is not as intended.

Then I can cmorize one copy of this file and upload to ESGF. Since this is the same for all the experiments. We do this for only one experiments. And future experiments will have fixed version.

**Comment by IngoBethke** [comment]
To exclude lake fraction you could change the definition to "LANDFRAC * (1 - PCT_LAKE)". The easiest is probably to precompute this and add a new variable to the grid_atm* files in /projects/NS9560K/cmor/griddata. 

Alternatively, you could replace the LANDFRAC field itself in the grid_atm* file. If you do that then  you should use nco or similar and make sure the operation is logged in the history global attribute.

**Comment by oyvindseland** [comment]
It is likely even easier to use the landfrac variable from the model output: This variable is given in all monthly mean files for atmospheric output. (cam.h0).

It is identical for all coupled experiments (but different for LM and MM) so it is enough to choose one field for LM and one field for MM.

A complicating factor is that for atmosphere only experiments there exists two different values so in this case you need to take landuse from each experiment.  The reason for this split is that sometimes the un-coupled experiments use observational files for SST and sometimes our own SST. It is also possible to list all the atmosphere only experiment and ask for "classification" into the two types. 

BTW I checked CMIP5 cmorized data as well and that looked OK.

**Comment by YanchunHe** [comment]
I can not find the PCT_LAKE neither in the grid file or model output @IngoBethke 

And I can not find landfrac in cam.h0 output in either LM and MM simulations, e.g. NHIST_f19_tn14_20190710 and HISTfrc2_f09_tn14_20191001 @oyvindseland

**Comment by YanchunHe** [comment]
> It is likely even easier to use the landfrac variable from the model output: This variable is given in all monthly mean files for atmospheric output. (cam.h0).
> 
> It is identical for all coupled experiments (but different for LM and MM) so it is enough to choose one field for LM and one field for MM.
> 


> A complicating factor is that for atmosphere only experiments there exists two different values so in this case you need to take landuse from each experiment. The reason for this split is that sometimes the un-coupled experiments use observational files for SST and sometimes our own SST. It is also possible to list all the atmosphere only experiment and ask for "classification" into the two types.
> 
> BTW I checked CMIP5 cmorized data as well and that looked OK.

I don't see if there is simple solution to the atmospheric-only simulations, except provide a seperate file for each experiment with the landfrac stored, e.g., landfrac.nc under each case, or landfrac_expid.nc at a command directory.

**Comment by IngoBethke** [comment]
For PCT_LAKE check e.g. /cluster/shared/noresm/inputdata/lnd/clm2/surfdata/surfdata_0.9x1.25_HistSSP3RCP70_simyr1850_c181010.nc for MM 

LANDFRAC should be in CAM model output (note that it is capitalised)

**Comment by YanchunHe** [comment]
Thanks Ingo!

@oyvindseland  Could you check if this sftlf that is used the LANDFRAC from the LM historical run correct?

[sftlf_fx_NorESM2-LM_historical_r1i1p1f1_gn.nc.zip](https://github.com/NorwegianClimateCentre/noresm2cmor/files/3929343/sftlf_fx_NorESM2-LM_historical_r1i1p1f1_gn.nc.zip)

**Comment by YanchunHe** [comment]
This is roughly the difference compared to that use LANDFRAC from atmos_grid file:

<img width="432" alt="sftlf_diff" src="https://user-images.githubusercontent.com/1725351/70278948-997f5600-17b5-11ea-9523-b24e487a5374.png">

**Comment by oyvindseland** [comment]
Yes sftlf_fx_NorESM2-LM_historical_r1i1p1f1_gn_new.nc
give the correct landfraction for all LM coupled runs.

**Comment by YanchunHe** [comment]
OK, then I will use LANDFRAC from each model output (cam.h0), so does not matter whether they differ from model to model. (Assume each model has only one version of LANDFRAC, of course)

New experiments that have not been cmorized with have the `sftlf`.

I will post here some sample experiments that has the new `sftlf`.

**Comment by IngoBethke** [comment]
Great. Sounds like a good solution. 

Although you might need to change the computation of sftgif then as it depends on LANDFRAC: 
                 'sftgif        ','PCT_GLACIER*0.01  ','unitless;landfrac',

I don't know why LANDFRAC has changed as I am sure the one used in grid_atm file is extracted from the output. Could you check the LANDFRAC in the NorESM1-F output? Maybe it differs between CESM1 and CESM2. 

Maybe you can also check that orography PHIS is read from the output. I think noresm2cmor first checks the output and if it cannot find the variable there then it checks in grid_atm file. The reason I implemented this logic was that for NorCPM we tried to save storage space by not storing constant fields in the output.

**Comment by YanchunHe** [comment]
only have updated the sftgif using new landfrc,
commit: b96c5b0

[sftgif_fx_NorESM2-LM_historical_r1i1p1f1_gn_new.nc.zip](https://github.com/NorwegianClimateCentre/noresm2cmor/files/3934847/sftgif_fx_NorESM2-LM_historical_r1i1p1f1_gn_new.nc.zip)
[sftgif_fx_NorESM2-LM_historical_r1i1p1f1_gn_old.nc.zip](https://github.com/NorwegianClimateCentre/noresm2cmor/files/3934848/sftgif_fx_NorESM2-LM_historical_r1i1p1f1_gn_old.nc.zip)
[sftgif_new-old.nc.zip](https://github.com/NorwegianClimateCentre/noresm2cmor/files/3934849/sftgif_new-old.nc.zip)

**Comment by YanchunHe** [comment]
The NorESM2-MM historical (to be published soon) has the updated `stflf`, but since I don't find PCT_GLACIER in both grid file and cam.h0 file, sftgif is not available.

**Comment by YanchunHe** [comment]
Experiments that are cmorized after 20th Dec 2019 should have updated `sftlf` and `sftgif` (data version v20191108)

For example,
* NorESM2-LM, abrupt-4xCO2, See Issue #129 
* NorESM2-LM, abrupt-4xCO2, See Issue #141

**Comment by YanchunHe** [comment]
Hi @monsieuralok , could you create an issue report to all the `softly` and `sftgif` data that have version numbers v20191108 and earlier should use those from the abrupt-4xCO2 experiment of the LM and MM versions respectively?

So should we recmorized all these data and republish?

**Comment by monsieuralok** [comment]
@YanchunHe I have found _sftgif_ data but I do not find _softly_ data. I guess it should be _sftlf_ ? For every experiments it should be same? You want people should use it from abrupt-4xCO2 ?

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
(an update:)
link to the bug report:
https://errata.es-doc.org/static/view.html?uid=0b9d744d-be7c-0152-89fc-ca64ab2dbe40

**Comment by YanchunHe** [comment]
Hi @monsieuralok 

Could you retract all `sftlf` and `sftgif` with data version earlier than `v20191108` (not including v20191108). But also retract them of version `v20210118` as they are just republished old data with newer version. This applies to NorESM2-LM and all experiments.

I recmorized the coupled `historical `and `picontrol` simulation, and atmospheric only 'amip'  experiments, and they can be published after the above datasets are retracted.

Thanks!

**Comment by monsieuralok** [comment]
@YanchunHe I guess you want to mention v20210218 as there is no version v20210118?

**Comment by YanchunHe** [comment]
Hi @monsieuralok 

Any progress? Hope I do not missed any information.

Yanchun

**Comment by monsieuralok** [comment]
Hi, I have removed most datasets but stiil, I am not sure all are removed.

**Comment by monsieuralok** [comment]
@YanchunHe it seems all are removed. I will open Errata issue on that soon.

**Comment by monsieuralok** [comment]
Errata issue opened: https://errata.es-doc.org/static/view.html?uid=cbf20fbf-bed9-e4fb-9f8f-d62573ef5ed0
