### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - ssp370-lowNTCF (realisation 3, correction)

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#170]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/FRAM/noresm/cases

**experiment_id**
ssp370-lowNTCF

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NSSP370REFGHGLOWNTCFfrc2_03_f19_tn14_20191220, 2015-2054

### Optional information

**parent_experiment_id**
historical

**parent_experiment_rip**
r3i1p1f1

**parent_time_units**
'days since 1850-01-01'

**branch_method**
'Hybrid-restart from year 2015-01-01 of historical'

**other information**
realisation = 3
In the original version of this experiment (NSSP370LOWNTCFfrc2_03_f19_tn14_20191118), green-house gas (GHG) concentrations evolved according to ssp370-lowNTCF.  In this corrected version, GHG concentrations evolve according to ssp370.

**Comment by YanchunHe** [comment]
Please transfer the model data to NIRD, and comments on where it is stored on NIRD after it is transferred.
@tto061

**Comment by jgriesfeller** [comment]
Transfer to NIRD started.
Directory
/projects/NS9560K/noresm/cases/NSSP370REFGHGLOWNTCFfrc2_03_f19_tn14_20191220

**Comment by jgriesfeller** [comment]
transfer complete.
please cmorize.

**Comment by YanchunHe** [comment]
cmorized and ready to be published

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20200206
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/ssp370-lowNTCF/r3i1p1f1

**version**
- v20200206

**sha256sum**
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/ssp370-lowNTCF/.r3i1p1f1.sha256sum_v20200206

**Comment by monsieuralok** [comment]
@YanchunHe @DirkOlivie published

**Comment by YanchunHe** [comment]
Cmorized with additional iLAMB variables (#262), AERday `zg500` (#263) and corrected `fNup` (#251).

They are ready to be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-ssp370-lowNTCF
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/piClim-ssp370-lowNTCF

**version**
- v20210203

**sha256sum**
/projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/piClim-ssp370-lowNTCF
- .r3i1p1f1.sha256sum_v20210203

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #271, #272 and #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/ssp370-lowNTCF
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF

**version**
- v20210319

**sha256sum**
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/ssp370-lowNTCF
- .r3i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published
