### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - piControl

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#177]
CMORized precipitation (pr) between 1600-1709, using 
pr=precc+precl

total pr is not written out during this period.

**data path**
- /tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-LM/piControl/v20200217
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl

**version**
- v20200217

**sha256sum**
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl/.r1i1p1f1.sha256sum_v20200217

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
This issue should be merged to #122

**Comment by monsieuralok** [comment]
@YanchunHe retracted
