### ISSUE TITLE
issue with DMS concentration units

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#178]
(refer to J Bock mail)
In the NorESM2-LM CMIP6 files available on ESGF nodes, it seems that the DMS surface ocean concentration (variable named dmsos) does not have the correct units.

The metadata says that units should be "mol m-3", and with such units the DMS concentration is expected to lie in the 1e-6 range.
However, the data are rather in the 1e-9 range, more consistent with "mol l-1" units.

Has this already been reported?
Can you confirm the actual units of files currently available on ESGF nodes?

**Comment by YanchunHe** [comment]
(Jörg)
the problem is that in the original model output DMS is reported in kmol 
m^-3. This is inconsistent with the units of all other tracers, which 
are reported as mol m^-3. I was not aware of this, and therefore I did 
not provide a conversion factor for DMS surface concentrations.

So yes, Josue is correct, our DMS values provided at ESGF are a factor 
1000 too small. I guess this error is not serious enough to justify a 
retraction of DMS data, but it should be corrected in case we provide a 
new data version. Do we have a publicly available "known issues with 
NorESM2 data" somewhere?

**Comment by YanchunHe** [comment]
@JorgSchwinger Could you check if dms in other components, e.g, aero are also correct?

**Comment by YanchunHe** [comment]
Alok, @monsieuralok , could you create a known issue at ESGF for this?

**Comment by monsieuralok** [comment]
@JorgSchwinger @YanchunHe I was planning to create an issue on es-doc; but it needs a list of all the affected datasets and which is quite long could be more than 1000 datasets that we need to select. Without list of these datasets it is not possible to create a issue. Finally, what should we do ? Also, I guess it is only DMS variable which is having issue or there are any other DMS related variables ? or should be fix it?

**Comment by monsieuralok** [comment]
@YanchunHe updated on es-doc

**Comment by monsieuralok** [comment]
https://errata.es-doc.org/static/view.html?uid=b57e7df0-bec0-941e-872a-dd4bb0d744a6 issue on es-doc

**Comment by YanchunHe** [comment]
New dmsos data are cmorized with version v20200218 for the above referred experiments.
