### ISSUE TITLE
[BUG] Imcomplete data of 3hourly, 6hourly data

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#179]
For LM and MM,  amip, ssp126, ssp245, ssp370, and ssp585 variables.

(refer to m.priestley)

> I have been attempting to download some of your CMIP6 data from the ESGF and have encountered some empty data files from your models. The experiments I have been trying to download data from are amip, ssp126, ssp245, ssp370, and ssp585 for variables ua, va, and psl and 6 hourly time resolution (6hrPlevPt).
> 
> It appears that some of the files have the complete amount of data and some are empty, only containing the file metadata. Is this a problem you are aware of? Or are only the files with the complete data the ones that will be published?
> 
> Thank you in advance for your help with this and I look forward to hearing back from you.
>

**Comment by oyvindseland** [comment]
I can confirm that this is the case also when looking directly into the files at NS9034K

**Comment by YanchunHe** [comment]
> I can confirm that this is the case also when looking directly into the files at NS9034K

Yes, I also noticed this.

**Comment by monsieuralok** [comment]
(base) [agu002@login2-nird v20191108]$ ls -altr ../../../../../../../../../.cmorout/NorESM2-LM/ssp245/v20191108/ua_6hrPlevPt_NorESM2-LM_ssp245_r1i1p1f1_gn_*
-rw-rw-r-- 1 yanchun ns9034k 1925660203 Nov 27 05:55 ../../../../../../../../../.cmorout/NorESM2-LM/ssp245/v20191108/ua_6hrPlevPt_NorESM2-LM_ssp245_r1i1p1f1_gn_202101010300-203012312100.nc
-rw-rw-r-- 1 yanchun ns9034k 1924988805 Dec  7 03:10 ../../../../../../../../../.cmorout/NorESM2-LM/ssp245/v20191108/ua_6hrPlevPt_NorESM2-LM_ssp245_r1i1p1f1_gn_203101010300-204012312100.nc
-rw-rw-r-- 1 yanchun ns9034k 1925139621 Dec  7 09:57 ../../../../../../../../../.cmorout/NorESM2-LM/ssp245/v20191108/ua_6hrPlevPt_NorESM2-LM_ssp245_r1i1p1f1_gn_204101010300-205012312100.nc
-rw-rw-r-- 1 yanchun ns9034k 1924918207 Dec  7 16:16 ../../../../../../../../../.cmorout/NorESM2-LM/ssp245/v20191108/ua_6hrPlevPt_NorESM2-LM_ssp245_r1i1p1f1_gn_205101010300-206012312100.nc
-rw-rw-r-- 1 yanchun ns9034k 1924689510 Dec  7 22:55 ../../../../../../../../../.cmorout/NorESM2-LM/ssp245/v20191108/ua_6hrPlevPt_NorESM2-LM_ssp245_r1i1p1f1_gn_207101010300-208012312100.nc
-rw-rw-r-- 1 yanchun ns9034k 1924634499 Dec  8 05:06 ../../../../../../../../../.cmorout/NorESM2-LM/ssp245/v20191108/ua_6hrPlevPt_NorESM2-LM_ssp245_r1i1p1f1_gn_208101010300-209012312100.nc
-rw-rw-r-- 1 yanchun ns9034k 1924444596 Dec  8 11:18 ../../../../../../../../../.cmorout/NorESM2-LM/ssp245/v20191108/ua_6hrPlevPt_NorESM2-LM_ssp245_r1i1p1f1_gn_209101010300-210012312100.nc
-rw-rw-r-- 1 yanchun ns9034k    4498094 Dec 26 00:23 ../../../../../../../../../.cmorout/NorESM2-LM/ssp245/v20191108/ua_6hrPlevPt_NorESM2-LM_ssp245_r1i1p1f1_gn_206101010300-207012312100.nc
-rw-rw-r-- 1 yanchun ns9034k    2720430 Dec 30 13:18 ../../../../../../../../../.cmorout/NorESM2-LM/ssp245/v20191108/ua_6hrPlevPt_NorESM2-LM_ssp245_r1i1p1f1_gn_201501010000-202012312100.nc

It seems data are missing after CMORIZATION.

**Comment by YanchunHe** [comment]
This happened when the cmorization was performed on the mounted data from the cluster, and I was away on vacation and could not check carefully if data were complete.

As the mounted disk is not stable, the tool get only partly the time slices, but by unknown reasons, it still dumps to the file without crash.

Now I have to restart cmorization for the 3houly and 6 hourly fields of these experiments.

**Comment by YanchunHe** [comment]
This is quite annoying, since this can happens quite randomly to the the files.

I many need to reduce substantially the parallel threads of the cmorization, but this will increase the processing time by folders.

**Comment by YanchunHe** [comment]
The corrected data for the following 3 hourly and 6 hourly data are cmorized with v20200218:

- 6hrLev
- 6hrPlevPt
- CF3hr

The following experiments are updated:

**NorESM2-LM**:
- amip
- historical
- ssp126
- ssp245
- ssp370
- ssp585

**NorESM2-MM**:
- ssp126
- ssp245
- ssp370
- ssp585

The old incomplete data should be retracted from ESGF, and remove the local nird old files
```
# cd /projects/NS9034K/CMIP6/.cmorout/NorESM2-?M/[experiment_id]
rm -f v20200218/{*6hrLev*,*6hrPlevPt*,*CF3hr*}
```

And then remove the broken links of the deleted files:
```
find ./v20200218 -xtype l -print -exec rm -f {} \;
```

@monsieuralok , could you retract the data from ESGF and update the local files? Thanks!

**Comment by monsieuralok** [comment]
@YanchunHe I guess I need to remove/delete data from version v20191108 instead as mentioned above  rm -f v20200218/{*6hrLev*,*6hrPlevPt*,*CF3hr*} and find ./v20200218 -xtype l -print -exec rm -f {} \;  As, I have almost retracted data for NorESM2-MM.

**Comment by YanchunHe** [comment]
oh, yes, the v20200218 should be the correct version. The versions before that, i.e., v20191108 should be retracted instead. Thanks!

**Comment by monsieuralok** [comment]
@YanchunHe For NorESM2-LM ssp* r1i1p1f1 has new 6hrLev,6hrPlevPt,CF3hr data and ssp245 with all realization (r2 and r3) has all new  6hrLev,6hrPlevPt,CF3hr data. While ssp370 donot have these new data for r2 and r3 realization. Is it true or something missing?

**Comment by YanchunHe** [comment]
Yes, I think there are no high-frequency output in these realisations. As I also noted in ssp370 r2/r3 issues, there are no 3hr/6hr data. Please just go ahead.

**Comment by monsieuralok** [comment]
@YanchunHe done
