### ISSUE TITLE
bi-monthly output of 'loadxxx' variables.

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#18]
(A. Gjermundsen)
the cmorized output in /projects/NS9034K/CMIP6/cmorout/NorESM2-LM/ and I have a question regarding the load output. In both historical and piControl the output is missing January. All the files are from February to December. It is not a name error, because the files are shorter compared to others. E.g.:
 ls /projects/NS9034K/CMIP6/cmorout/NorESM2-LM/historical/v20190815/loaddust_Emon_NorESM2-LM_historical_r1i1p1f1_gn_185002-185912.nc 

Is there a reason or just a bug?

if compare with e.g. CESM2 the output is monthly (it is the same for all the other models I have looked at):
```
(base) [adagj@login-nird-3 piControl]$ ncdump -h loaddust_Emon_CESM2_piControl_r1i1p1f1_gn_000101-009912.nc 
netcdf loaddust_Emon_CESM2_piControl_r1i1p1f1_gn_000101-009912 {
dimensions:
lat = 192 ;
nbnd = 2 ;
time = UNLIMITED ; // (1188 currently)
lon = 288 ;
variables:
double lat(lat) ;
lat:axis = "Y" ;
lat:bounds = "lat_bnds" ;
lat:standard_name = "latitude" ;
lat:title = "Latitude" ;
lat:type = "double" ;
lat:units = "degrees_north" ;
lat:valid_max = 90. ;
lat:valid_min = -90. ;
float lat_bnds(lat, nbnd) ;
lat_bnds:units = "degrees_north" ;
float loaddust(time, lat, lon) ;
loaddust:_FillValue = 1.e+20f ;
loaddust:cell_measures = "area: areacella" ;
loaddust:cell_methods = "area: time: mean" ;
loaddust:comment = "The total dry mass of dust aerosol particles per unit area." ;
loaddust:coordinates = "time lat lon" ;
loaddust:deflate = "0" ;
loaddust:deflate_level = "0" ;
loaddust:description = "The total dry mass of dust aerosol particles per unit area." ;
loaddust:frequency = "mon" ;
loaddust:id = "loaddust" ;
loaddust:long_name = "Load of Dust" ;
loaddust:mipTable = "Emon" ;
loaddust:missing_value = 1.e+20 ;
loaddust:out_name = "loaddust" ;
loaddust:prov = "PMIP [PMIP-aero-02]" ;
loaddust:realm = "atmos" ;
loaddust:shuffle = "0" ;
loaddust:standard_name = "atmosphere_mass_content_of_dust_dry_aerosol_particles" ;
loaddust:time = "time" ;
loaddust:time_label = "time-mean" ;
loaddust:time_title = "Temporal mean" ;
loaddust:title = "Load of Dust" ;
loaddust:type = "real" ;
loaddust:units = "kg m-2" ;
loaddust:variable_id = "loaddust" ;
double lon(lon) ;
lon:axis = "X" ;
lon:bounds = "lon_bnds" ;
lon:standard_name = "longitude" ;
lon:title = "Longitude" ;
lon:type = "double" ;
lon:units = "degrees_east" ;
lon:valid_max = 360. ;
lon:valid_min = 0. ;
float lon_bnds(lon, nbnd) ;
lon_bnds:units = "degrees_east" ;
double time(time) ;
time:axis = "T" ;
time:bounds = "time_bnds" ;
time:standard_name = "time" ;
time:title = "time" ;
time:type = "double" ;
time:units = "days since 0001-01-01 00:00:00" ;
time:calendar = "noleap" ;
double time_bnds(time, nbnd) ;
time_bnds:calendar = "noleap" ;
time_bnds:units = "days since 0001-01-01 00:00:00" ;
```

**Comment by YanchunHe** [comment]
This applies to most Emon and Lmon fields too.

**Comment by YanchunHe** [comment]
bi-monthly wrong records in fields including "hus loaddust loadss ps rsdsdiff ua va wap" in table Emon was due to a bug a duplicated snippets of code in the m_modelsatm.F for table Emon, which has fixed in commit: 11aacd0bf6ca8d3fb5029df19d2afa35e14c3cb8 and 257b840add25084e862053fb658271e59e03ed8b

**Comment by YanchunHe** [comment]
The first monthl data for fields for "LImon Lmon" are also missing for the first year data of CMORized output. This should be due to the fact that the timestamp start from xxxx-02-01 in the output of atmospheric, ice and land components.

$ ls *185002* |cut -d"_" -f2 |sort -u
Emon
LImon
Lmon

However, Amon SImon etc are not effected????? (ocean output has correct timestamp, so not effected of course)

$ ls *185001* |cut -d"_" -f2 |sort -u

AERmon

Amon
day
Oday
Omon
SIday
SImon
`
We shoule leave it as it is, or fix this?

**Comment by YanchunHe** [comment]
Should we remove the effected fields in v20190815?

**Comment by IngoBethke** [comment]
The problem with the Lmon and LImon data might be related to incorrect specification of time_bounds in the CLM output.

The output of ncdump -v time_bounds -t NHIST_f19_tn14_20190625.clm2.h0.1850-01.nc is 
 time_bounds =
  "1849-12-31 23:30", "1850-02-01" ;

The first bound should be 1850-01-01. So if noresm2noresm3 checks if the data is within 1850-01-01 and 1859-12-13 then it might reject the first month because of the incorrect time bounds specification. As a work around you could simply try specifying year1=1949 in the exp-namelist.  

It should be safe to remove all erroneous cmor-ized fields. Just keep track of the hashtag version of noresm2cmor that you used to produce the removed data. If you do that you can in principal always re-generate the removed data.

**Comment by YanchunHe** [comment]
With incorrect time_bounds in the first month of land history file, tables "Emon, Lmon and LImon" are affected, including experiments:
- 1pctCO2
- abrupt-4xCO2
- hist-GHG
- historical
- hist-piAer
- hist-piNTCF
- piClim-4xCO2
- piClim-aer
- piClim-BC
- piClim-control
- piClim-ghg
- piClim-OC
- piClim-SO2

The following two experiments are not affected:
- piClim-lu
- piControl

 Specifically the following files  are affected:
/projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/{1pctCO2,abrupt-4xCO2,hist-GHG,historical,hist-piAer,hist-piNTCF,piClim-4xCO2,piClim-aer,piClim-BC,piClim-control,piClim-ghg,piClim-OC,piClim-SO2}l/v20190815/

- cCwd_Lmon_NorESM2-LM_*02-*.nc
- cLeaf_Lmon_NorESM2-LM_*02-*.nc
- cLitter_Lmon_NorESM2-LM_*02-*.nc
- cRoot_Lmon_NorESM2-LM_*02-*.nc
- cSoilFast_Lmon_NorESM2-LM_*02-*.nc
- cSoilMedium_Lmon_NorESM2-LM_*02-*.nc
- cSoilSlow_Lmon_NorESM2-LM_*02-*.nc
- cVeg_Lmon_NorESM2-LM_*02-*.nc
- cWood_Emon_NorESM2-LM_*02-*.nc
- evspsblsoi_Lmon_NorESM2-LM_*02-*.nc
- evspsblveg_Lmon_NorESM2-LM_*02-*.nc
- fFire_Lmon_NorESM2-LM_*02-*.nc
- fHarvest_Lmon_NorESM2-LM_*02-*.nc
- fVegLitter_Lmon_NorESM2-LM_*02-*.nc
- gpp_Lmon_NorESM2-LM_*02-*.nc
- lai_Lmon_NorESM2-LM_*02-*.nc
- lwsnl_LImon_NorESM2-LM_*02-*.nc
- mrfso_Lmon_NorESM2-LM_*02-*.nc
- mrlso_Emon_NorESM2-LM_*02-*.nc
- mrro_Lmon_NorESM2-LM_*02-*.nc
- mrros_Lmon_NorESM2-LM_*02-*.nc
- mrsfl_Emon_NorESM2-LM_*02-*.nc
- mrsll_Emon_NorESM2-LM_*02-*.nc
- mrsol_Emon_NorESM2-LM_*02-*.nc
- mrso_Lmon_NorESM2-LM_*02-*.nc
- mrsos_Lmon_NorESM2-LM_*02-*.nc
- nbp_Lmon_NorESM2-LM_*02-*.nc
- nep_Emon_NorESM2-LM_*02-*.nc
- nppLeaf_Lmon_NorESM2-LM_*02-*.nc
- npp_Lmon_NorESM2-LM_*02-*.nc
- nppRoot_Lmon_NorESM2-LM_*02-*.nc
- nppWood_Lmon_NorESM2-LM_*02-*.nc
- prveg_Lmon_NorESM2-LM_*02-*.nc
- ra_Lmon_NorESM2-LM_*02-*.nc
- rGrowth_Lmon_NorESM2-LM_*02-*.nc
- rh_Lmon_NorESM2-LM_*02-*.nc
- rMaint_Lmon_NorESM2-LM_*02-*.nc
- snc_LImon_NorESM2-LM_*02-*.nc
- snd_LImon_NorESM2-LM_*02-*.nc
- snw_LImon_NorESM2-LM_*02-*.nc
- sootsn_LImon_NorESM2-LM_*02-*.nc
- tran_Lmon_NorESM2-LM_*02-*.nc
- tsl_Lmon_NorESM2-LM_*02-*.nc
- vegHeight_Emon_NorESM2-LM_*02-*.nc

These are the cmorized first of the first 10 model years. However, to maintain consistency, these affected fields are cmorized again for all the model years, tagged as v20190917; and related old v20190815 files are  removed.

Links are updated; sha256sum  are calculated to append to .r1i1l1f1.sha256sum files (old sha256sum are removed).

exp_*.nml and scripts are committed: 121f504faa697dd2ea7f716dd0533abc5334882c

**Comment by IngoBethke** [comment]
I assume the problem has been fixed then and will close this issue.

**Comment by YanchunHe** [comment]
(refer to X. Yao)
2. The start time in snw (snd / snw) _LImon_NorESM2-LM_ssp126 (245/370/585) _r1i1p1f1_gn_201502-220012.nc are not '201501', and the data at '201501' are missing.

**Comment by YanchunHe** [comment]
fixed in new cmorized data version v20191108b.

Refer to #134 

commit: 2725389

**Comment by aliasaadi** [comment]
The start time in "Lmon" fields is not '201501' for ssp585, other ssps as well.
data version: v20191108

**Comment by YanchunHe** [comment]
> The start time in "Lmon" fields is not '201501' for ssp585, other ssps as well.
> data version: v20191108

Yes, I am aware of that. I will update all SSP* experiments, for relevant Emon, Lmon and LImon variables.
