### ISSUE TITLE
[BUG] tasmax and tasmin

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#180]
From e-mail

"I have recently been working with daily tasmax data from historical NorESM-LM2 simulations (member r1i1p1f1) and the data have an apparent jump at 1950 (see attached plots). The same is true for tasmin while tas looks normal. It looks a bit like the daily temperature range would increase after 1950.
I also checked the r2i1p1f1 member and there everything looks normal.
Do you already know about this issue?"

This is the same issue as for early control. tasmx and tasmn = tas for 1850-1949 historical.

This is not easy to correct so the fields should just be retracted I think

Øyvind

**Comment by monsieuralok** [comment]
@oyvindseland Should I retract tasmx, tasmn and  tas all three variables from historical experiemt? and for which realization ? r1 r2 r3 or only for r1?

**Comment by oyvindseland** [comment]
tas is OK 
tasmax and tasmin should be retracted for the r1, 1850-1949

**Comment by monsieuralok** [comment]
@oyvindseland @YanchunHe did it. 
Alok

**Comment by monsieuralok** [comment]
tasmax and tasmin only show data from 1950-2014 on All Replicas

**Comment by monsieuralok** [comment]
do we need to retract all data? even from 1950-2014?

**Comment by oyvindseland** [comment]
1950-2014 should be fine and useful for studies of scenarios - present day so I do not think those should be removed.
An errata may be useful though.

**Comment by YanchunHe** [comment]
(I made mistake in my mail for retracting data after 1950, should be before 1950).

I search on the ESGF data portal, and find data before 1950 have bee retracted from the noresg.nird.sigma2.no, but they reside on other replica:

```
esgf-data1.llnl.gov
esgf-data3.ceda.ac.uk
esgf-data3.diasjp.net
esgf3.dkrz.de
```

**Comment by monsieuralok** [comment]
I have checked through https://esgf-node.llnl.gov/search/cmip6/ and I found data is only available from 1950-2014

**Comment by YanchunHe** [comment]
You can check 'Show All Replicas' box at the top.

<img width="1067" alt="Screenshot 2020-10-08 at 13 51 01" src="https://user-images.githubusercontent.com/1725351/95455310-f4ea1980-096d-11eb-8e09-c332b8f9da40.png">
<img width="1067" alt="Screenshot 2020-10-08 at 13 51 12" src="https://user-images.githubusercontent.com/1725351/95455317-f87da080-096d-11eb-8c45-4d97f28476e1.png">

**Comment by monsieuralok** [comment]
Ok, now I understand, I was checking replica in wrong way as I was always selecting noresg node.

**Comment by YanchunHe** [comment]
OK! Then it means the replicas will not retract the data, or take long time for them to synchronise (remove) the data on each node. so an errata report might be useful.

**Comment by oyvindseland** [comment]
The same error also exists in parts of piControl and 4XCO2 so more periods of daily tasmax and tasmin have to be retracted. 
Control the period 1600-1710 (The problem stops at 1700, but the cmorized period starts in 1700 
abrupt 4XCO2 year 1 to 119
1 pct CO2 year 100-119 (Most of it is already retracted)

**Comment by oyvindseland** [comment]
Slight change in information

Control the period 1600-1709

**Comment by monsieuralok** [comment]
@YanchunHe could you mention which variables and from which experiments need to be removed?

**Comment by YanchunHe** [comment]
@monsieuralok 

`tasman` and `tasmin` for the following should be retracted according to above information:
* PiControl: 1600-1709
* Abrupt4XCO2: 1 to 119
* 1pctCO2: 100-119

However, as I understand, it may need to retract all the records of these fields, and republish the remaining correct period.

So please first retract (all of them if needed), and then I will regenerate the meta information, and you republish the rest of the them.

Keep the issue open until final republish.

**Comment by monsieuralok** [comment]
@YanchunHe if I am correct then for both resolutions NorESM2-LM and MM?

**Comment by monsieuralok** [comment]
For LM, I have already retracted datasets and opened issue on errata: https://errata.es-doc.org/static/view.html?uid=2ea22575-6dd2-598a-821b-33557f437c3c    . For MM, I will do it after confirmation.

**Comment by oyvindseland** [comment]
The error is only found in the NorESM2-LM simulations, so no MM fields need to be retracted from this.
