### ISSUE TITLE
[BUG]  CMIP6 esm-hist co2 behaviour and land-use emissions

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#181]
(quote T. Walsh)

> 1) Concentration differences between models: During the tuning I made a direct plot of the esm-hist output CO2 surface concentrations (please see attached), and we were surprised/interested by how large the difference in output concentrations were between the models.
How do these behaviours generally compare to your expectations and experience of working with these experiments and models?
How does the concentration plotted for your model match your expectation/knowledge, and what insight might you have into its particular behaviour here?
> 2) Input emissions datasets: For the tuning, I am comparing FaIR’s diagnosed cumulative emissions to the esm-hist input cumulative forcing emissions. We have the historical fossil fuel emissions (bulk and vertically resolved airplane emissions) from CEDs, and I am aware that each model may treat land use change emissions differently, either internally or externally.
How did your model apply land use emissions?
If internally, would you be able to provide these calculated emissions; if externally, was the dataset used the one given by C4MIP (see below)?

**Comment by YanchunHe** [comment]
Quote J.Tjiputra
> Regarding (1), I found this to be surprising. Can you clarify how did you compute the CO2 concentration?
An example of the first 10 years of NorESM2-LM co2 data from esm-hist can be found here: 
ftp://ftp.uib.no/pub/gfi/jtj061/CMIP6/
And they are more within the range of the other models.

Quote I. Benke
>From your plot it looks like we forgot to apply a unit conversion factor during the post-processing of the output. The factor is 29 / (12 + 2*16), which is the molecular mass of air divided by the molecular mass of CO2.

**Comment by YanchunHe** [comment]
Hi @monsieuralok, 

Could you report an issue at ESGF for all the `co2` data of AERmon that they should be applied with a factor of 29/(12+2*16) for unit conversion from ` kg kg-1` to `mol mol-1`?
for example, the file:
* co2_AERmon_NorESM2-LM_historical_r3i1p1f1_gn_201001-201412.nc

**Comment by monsieuralok** [comment]
@YanchunHe Do we need to report this issue for every published data set ? as I have to collect all the names of datasets. Is it going to fix in any future version?

**Comment by YanchunHe** [comment]
Yes, if there is going to be a new version, it will be fixed. But I don't plan so far to cmorize all experiments and you publish them. That will be more work than just reporting an issue, right?

If you filter the variable and source_id in ESGF web portal, you should easily get a list of the affected experiments, right? I have no idea how much work this requires for you to do so and retract the data.

**Comment by monsieuralok** [comment]
I would do it. It is not much work as I checked there are only 52 datasets but each time we publish then we have to add datasets to this list. So, I am filtering AERmon and CO2.

**Comment by YanchunHe** [comment]
Good, thanks!

**Comment by monsieuralok** [comment]
@YanchunHe done

**Comment by YanchunHe** [comment]
This issue is fixed in commit: 554cabd. Data version after v20200401 should have the correct CO2 value

**Comment by YanchunHe** [comment]
Errata report:

https://errata.es-doc.org/static/view.html?uid=2b26dd51-be64-8d15-b8ca-5a08f7f6b021
