### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - PAMIP pdSST-pdSIC members 101-200

### ISSUE THREAD

**Issue by lisesg** [NorESMhub/noresm2cmor#182]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
* Members 101-125:
/projects/NS2345K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p1_pdSST-pdSIC_mem101-125_f19_mg17_20200313
* Members 126-150:
/projects/NS2345K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p1_pdSST-pdSIC_mem126-150_f19_mg17_20200313
* Members 151-175:
/projects/NS2345K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p1_pdSST-pdSIC_mem151-175_f19_mg17_20200313
* Members 176-200:
/projects/NS2345K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p1_pdSST-pdSIC_mem176-200_f19_mg17_20200313

Full path to post-processed fields epfy, epfz, utendepfd, vtem, wtem (Eliassen-Palm fluxes and friends):
* Members 101-125:
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p1_pdSST-pdSIC_mem101-125_f19_mg17_20200313
* Members 126-150:
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p1_pdSST-pdSIC_mem126-150_f19_mg17_20200313
* Members 151-175:
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p1_pdSST-pdSIC_mem151-175_f19_mg17_20200313
* Members 176-200:
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p1_pdSST-pdSIC_mem176-200_f19_mg17_20200313

**experiment_id**
pdSST-pdSIC

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
* NFHISTnorpddmsbc_PAMIP_1p1_pdSST-pdSIC_mem101-125_f19_mg17_20200313: 
June 1st 2000 - May 31st 2001
* NFHISTnorpddmsbc_PAMIP_1p1_pdSST-pdSIC_mem126-150_f19_mg17_20200313: 
June 1st 2000 - May 31st 2001
* NFHISTnorpddmsbc_PAMIP_1p1_pdSST-pdSIC_mem151-175_f19_mg17_20200313: 
June 1st 2000 - May 31st 2001
* NFHISTnorpddmsbc_PAMIP_1p1_pdSST-pdSIC_mem176-200_f19_mg17_20200313: 
June 1st 2000 - May 31st 2001

### Optional information

**parent_experiment_id**
amip

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
days since 1975-01-01 00:00:00

**branch_method**
'Hybrid-restart from year 2000-04-01 of amip'

**other information**
The experiment is a hybrid run starting from /projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_f19_mg17_IC4PAMIP_20190816, which is an extension of the amip experiment carried out to provide restart and initial-condition files for the start date April 1st 2000.

**Comment by YanchunHe** [comment]
Hi @lisesg , please check the permission of all the experiment folders so that I can have read access.

I would suggest that you change the group of the files/folders to ns2345k, use command as:
```
chmod -R lisesg:ns2345k parent_folders_to_change
```

And also add `r-s` permission to users of the same group
```
find parent_folder_to_change -type d -print -exec chmod g+rxs {} \; 
```

After you have done this, I can start the cmorization process. Thanks!

Yanchun

**Comment by lisesg** [comment]
Sorry about that! I've updated the permissions of the files. Hope everything is OK now.

**Comment by YanchunHe** [comment]
Thanks, cmorization now starts!

**Comment by YanchunHe** [comment]
cmorized and ready to publish to ESGF

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/pdSST-pdSIC
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-pdSIC

**data version*
- v20200218

**sha256sum**
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-pdSIC/.r[1-2]??i1p1f1.sha256sum_v20200218

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by lisesg** [comment]
It seems like zg500 for AERday has not been cmorized with the additional members.

**Comment by YanchunHe** [comment]
cmorized `zg500` and `ta850` for members 101-200.

cmorized and ready to publish to ESGF

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/pdSST-pdSIC
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-pdSIC

**data version*
- v20200218

**sha256sum**
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-pdSIC/.r[1-2]??i1p1f1.sha256sum_v20200218b

**Comment by monsieuralok** [comment]
@YanchunHe ta850 with Eday frequency with same version is already published

**Comment by YanchunHe** [comment]
> @YanchunHe ta850 with Eday frequency with same version is already published

OK, I see indeed ta850 is published, but the ensemble member r101 is missing in locally on NIRD but findable on ESGF.

I am a bit confused now what happed.

What is the best way to proceed?

Is that OK to retract all `ta850` and republish them again together with `zg500`?

**Comment by monsieuralok** [comment]
@YanchunHe I retracted datasets ta850 but, it is not possible to publish them with same version number.

**Comment by YanchunHe** [comment]
> @YanchunHe I retracted datasets ta850 but, it is not possible to publish them with same version number.

OK, I renamed the datasets to the latest v20230616, please see the updated threads above.

**Comment by YanchunHe** [comment]
> > @YanchunHe I retracted datasets ta850 but, it is not possible to publish them with same version number.
> 
> OK, I renamed the datasets to the latest v20230616, please see the updated threads above.

Hi Alok, @monsieuralok 

Just wondering is this still in the process for publishing?

**Comment by monsieuralok** [comment]
@YanchunHe I have published atleast a week earlier but, I should open errata issue regarding retract then, I will update

**Comment by monsieuralok** [comment]
@YanchunHe published Eratta issue:- https://errata.ipsl.fr/static/view.html?uid=372c2185-7d71-58a7-821a-b47c3b42e3af
