### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - PAMIP pdSST-futArcSIC members 101-200

### ISSUE THREAD

**Issue by lisesg** [NorESMhub/noresm2cmor#183]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
* Members 101-125:
/projects/NS2345K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p6_pdSST-futArcSIC_mem101-125_f19_mg17_20200313
* Members 126-150:
/projects/NS2345K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p6_pdSST-futArcSIC_mem126-150_f19_mg17_20200313
* Members 151-175:
/projects/NS2345K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p6_pdSST-futArcSIC_mem151-175_f19_mg17_20200313
* Members 176-200:
/projects/NS2345K/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p6_pdSST-futArcSIC_mem176-200_f19_mg17_20200313

Full path to post-processed fields epfy, epfz, utendepfd, vtem, wtem (Eliassen-Palm fluxes and friends):
* Members 101-125:
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p6_pdSST-futArcSIC_mem101-125_f19_mg17_20200313
* Members 126-150:
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p6_pdSST-futArcSIC_mem126-150_f19_mg17_20200313
* Members 151-175:
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p6_pdSST-futArcSIC_mem151-175_f19_mg17_20200313
* Members 176-200:
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NFHISTnorpddmsbc_PAMIP_1p6_pdSST-futArcSIC_mem176-200_f19_mg17_20200313

**experiment_id**
pdSST-futArcSIC

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
* NFHISTnorpddmsbc_PAMIP_1p6_pdSST-futArcSIC_mem101-125_f19_mg17_20200313: 
June 1st 2000 - May 31st 2001
* NFHISTnorpddmsbc_PAMIP_1p6_pdSST-futArcSIC_mem126-150_f19_mg17_20200313: 
June 1st 2000 - May 31st 2001
* NFHISTnorpddmsbc_PAMIP_1p6_pdSST-futArcSIC_mem151-175_f19_mg17_20200313: 
June 1st 2000 - May 31st 2001
* NFHISTnorpddmsbc_PAMIP_1p6_pdSST-futArcSIC_mem176-200_f19_mg17_20200313: 
June 1st 2000 - May 31st 2001

### Optional information

**parent_experiment_id**
amip

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
days since 1975-01-01 00:00:00

**branch_method**
'Hybrid-restart from year 2000-04-01 of amip'

**other information**
The experiment is a hybrid run starting from /projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_f19_mg17_IC4PAMIP_20190816, which is an extension of the amip experiment carried out to provide restart and initial-condition files for the start date April 1st 2000.

**Comment by YanchunHe** [comment]
cmorized and ready to publish to ESGF

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/pdSST-futArcSIC
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-futArcSIC

**data version*
- v20200218

**sha256sum**
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-futArcSIC/.r[1-2]??i1p1f1.sha256sum_v20200218

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by lisesg** [comment]
It seems like zg500 for AERday has not been cmorized with the additional members.

**Comment by YanchunHe** [comment]
cmorized `zg500` and `ta850` for members 101-200.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/pdSST-futArcSIC
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-futArcSIC

**data version*
- v20200218

**sha256sum**
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pdSST-futArcSIC/.r[1-2]??i1p1f1.sha256sum_v20200218b

**Comment by monsieuralok** [comment]
@YanchunHe ta850 with Eday frequency with same version is already published

**Comment by YanchunHe** [comment]
> @YanchunHe ta850 with Eday frequency with same version is already published

Refer to my last reply at #182 on 8 Aug 2024.

**Comment by YanchunHe** [comment]
> > @YanchunHe ta850 with Eday frequency with same version is already published
> 
> Refer to my last reply at #182 on 8 Aug 2024.

I updated the data version, please try again to publish as `v20230616`.

**Comment by monsieuralok** [comment]
@YanchunHe published Eratta issue:- https://errata.ipsl.fr/static/view.html?uid=372c2185-7d71-58a7-821a-b47c3b42e3af
