### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - deforest-globe

### ISSUE THREAD

**Issue by lca041** [NorESMhub/noresm2cmor#188]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases/b.e21.NHISTfrc2.f19_tn14-deforest-globe.001

**experiment_id**
deforest-globe

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**

<strike>NHISTfrc2.f19_tn14-deforest-globe.001, 1850-1930</strike>
b.e21.NHISTfrc2.f19_tn14-deforest-globe.001, 1850-1930

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorwegianClimateCentre/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**branch_method**
'Hybrid-restart from year 1600-01-01 of piControl',

**other information**
LUMIP call requests the extraction of several sub-grid level variables. Scripts for re-gridding is already provided.

**Comment by YanchunHe** [comment]
Are you sure this is "historical" instead of something, e.g. 'land-hist'? @lca041

**Comment by lca041** [comment]
Hi Yanchun,

If you are referring to the experiment ID, then it should be
"deforest-glob". This simulation case is supposed to cover the whole
historical period, while LUMIP only requests the first 81 years. Sorry for
the inconvenience.

Lei

Yanchun He <notifications@github.com> 于2020年6月3日周三 上午9:29写道：

**Comment by YanchunHe** [comment]
ok, I updated the information at the top.

**Comment by YanchunHe** [comment]
Do you need to cmorize normal model variables in addition to the lUMIP variables?

I see clm2.h0, clm2.h1 and clm2.h2 in the original output are all monthly fields, right?

By default, monthly data is stored in clm2.h0, daily in clm2.h1, 3hr in clm2.h2.

Please find the default output format in the piControl simulation:
/projects/NS9560K/noresm/cases/N1850_f19_tn14_20190621/

**Comment by lca041** [comment]
Hi Yanchun,

Yes. Normal LUMIP variables are also needed to publish. For land, you only
need to CMORize monthly variables (in clm2.h0). You can ignore the
variables in clm2.h1 and clm2.h2. In this case, the variables in h1 and h2
are different from the default setting (They are landunit-level and pft
level variables). Thank you.

Lei

Yanchun He <notifications@github.com> 于2020年6月26日周五 下午4:44写道：

**Comment by YanchunHe** [comment]
Finally, this case is finally cmorized:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/deforest-globe
- /projects/NS9034K/CMIP6/LUMIP/NCC/NorESM2-LM/deforest-globe

**version**
- v20200702

**sha256sum**
/projects/NS9034K/CMIP6/LUMIP/NCC/NorESM2-LM/deforest-globe
- .r1i1p1f1.sha256sum_v20200702

@lca041 Could you check if all the results look OK so that we can precede with data publish? Thanks!

**Comment by lca041** [comment]
Hi Yanchun,

The data looks good. Thank you very much for your help! I am gonna register
issues for the rest four cases.

Lei

Yanchun He <notifications@github.com> 于2020年7月3日周五 上午11:07写道：

**Comment by YanchunHe** [comment]
Yes, please go ahead

**Comment by YanchunHe** [comment]
Hi Alok, @monsieuralok could you publish this? thanks!

**Comment by monsieuralok** [comment]
@YanchunHe I do not have write permission in directory.

**Comment by YanchunHe** [comment]
fixed!

**Comment by monsieuralok** [comment]
@YanchunHe published
