### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM esm-ssp585

### ISSUE THREAD

**Issue by tjiputra** [NorESMhub/noresm2cmor#193]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases/NSSP585_f19_tn14_20191223esm

**experiment_id**
esm-ssp585

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NSSP585_f19_tn14_20191223esm, 2015-2100

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorwegianClimateCentre/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
e.g., 
esm-hist

**parent_experiment_rip**
r1i1p1

**parent_time_units**
e.g.,
<strike>'days since 0421-01-01'</strike>
'days since 1850-01-01'

**branch_method**
e.g.,
<strike>'Hybrid-restart from year 2014-01-01 of esm-hist',</strike>
'Hybrid-restart from year 2015-01-01 of esm-hist',

**other information**
Please also publish once ready.

(provide other information that might be useful)
e.g., realisation, initialisation, etc...
and the cases name and path to the parent experiment, etc

**Comment by YanchunHe** [comment]
I think "parent_time_units" should be:
'days since 1850-01-01'
I updated this directly in the main thread.

And, is the branch method correct?
'Hybrid-restart from year 2014-01-01 of esm-hist',

is 2014-01-01 or 2015-01-01?

**Comment by tjiputra** [comment]
You're correct.

Branch method should be: 
Branch-restart from year 2015-01-01

**Comment by YanchunHe** [comment]
Thanks.

**Comment by YanchunHe** [comment]
cmorized and can be published

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/esm-ssp585
- /projects/NS9034K/CMIP6/C4MIP/NCC/NorESM2-LM/esm-ssp585

**version**
- v20200218

**sha256sum**
/projects/NS9034K/CMIP6/C4MIP/NCC/NorESM2-LM/esm-ssp585
- .r1i1p1f1.sha256sum_v20200218

**Comment by YanchunHe** [comment]
fixed it! @monsieuralok

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
@monsieuralok 
Please retract all `6hrPlev`, `6hrPlevPt` datasets of NorESM2-LM esm-ssp585.

**Comment by YanchunHe** [comment]
New dataset version to fix issues #269, #270, #271, #272, #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/esm-ssp585
- /projects/NS9034K/CMIP6/C4MIP/NCC/NorESM2-LM/esm-ssp585

**data version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/C4MIP/NCC/NorESM2-LM/esm-ssp585
- .r1i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by monsieuralok** [comment]
@YanchunHe retracted
