### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - esm-hist

### ISSUE THREAD

**Issue by tjiputra** [NorESMhub/noresm2cmor#194]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases/

**experiment_id**
esm-hist

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NHIST_f19_tn14_20191104esm, 1850-2014

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
esm-piControl

**parent_experiment_rip**
r1i1p1

**parent_time_units**
e.g.,
'days since 0421-01-01'

**branch_method**
'Hybrid-restart from year 1851-01-01 of piControl',

**other information**
(provide other information that might be useful)
e.g., realisation, initialisation, etc...
and the cases name and path to the parent experiment, etc

**Comment by YanchunHe** [comment]
cmorized and can be published

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/esm-hist
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/esm-hist

**version**
- v20200218

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/esm-hist
- .r1i1p1f1.sha256sum_v20200218

**Comment by YanchunHe** [comment]
Cmorized with additional iLAMB variables (#262), AERday `zg500` (#263) and corrected `fNup` (#251).

They are ready to be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/esm-hist/v20210203
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/esm-hist

**version**
- v20210203

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/esm-hist
- .r1i1p1f1.sha256sum_v20210203
-

**Comment by monsieuralok** [comment]
@YanchunHe published
