### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - piClim-control (phys2)

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#195]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS2345K/noresm/cases

**experiment_id**
piClim-control

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NF1850norbc_f19_20191025, 1-30

### Optional information

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 0421-01-01'

**branch_method**
'Hybrid-restart from year 1751-01-01 of piControl'

**other information**
physics = 2
I suggest to call this member r1i1p2f1

**Comment by YanchunHe** [comment]
cmorized and can be published

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-control
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-control

**version**
- v20200218

**sha256sum**
/projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-control
- .r1i1p2f1.sha256sum_v20200218

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #271, #272 and #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-control
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-control

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-control
- .r1i1p2f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by DirkOlivie** [comment]
Hi @YanchunHe, can also the years 31-90 of this simulation be cmorized?

**Comment by YanchunHe** [comment]
I will cmorize the years 31-90. @DirkOlivie 

I would suggest retract the first 1-30 years of `r1i1p2f1` and then republish the whole 1-90 years. Alok, would you retract the this dataset? (retract all `r1i1p2f1`  of `piClim-control`). @monsieuralok

**Comment by monsieuralok** [comment]
@YanchunHe started retracting

**Comment by YanchunHe** [comment]
Hi Dirk, could you open read access and change the group owner to NS9560K for the following folders? thanks.

```
/projects/NS2345K/noresm/cases/NF1850norbc_f19_20191025
drwx------  3 olivie olivie  4.0K Nov 18  2019 cpl/
drwx------  3 olivie olivie  4.0K Nov 18  2019 esp/
drwx------  3 olivie olivie  4.0K Nov 18  2019 ocn/
```

**Comment by DirkOlivie** [comment]
Hi Yanchun, I have now modified the access and group owner of the folders and files.  If it still not ok, please let me know.

**Comment by monsieuralok** [comment]
@YanchunHe data are retracted

**Comment by YanchunHe** [comment]
old data removed from NIRD and new data from 1-90 are cmorized and can be published to ESGF.

**data paht**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-control
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-control/r1i1p2f1

**version**
- v20210811

**sha256sum**
/projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-control
- .r1i1p2f1.sha256sum_v20210811

**Comment by monsieuralok** [comment]
@YanchunHe published on 24th August
