### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - piClim-ghg (phys2 )

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#200]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS2345K/noresm/cases

**experiment_id**
piClim-ghg

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NF1850norbc_ghg2014_f19_20191025, 1-30

### Optional information

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 0421-01-01'

**branch_method**
'Hybrid-restart from year 1751-01-01 of piControl'

**other information**
physics = 2
I suggest to call this member r1i1p2f1

**Comment by YanchunHe** [comment]
cmorized and can be published

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-ghg
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-ghg

**version**
- v20200218

**sha256sum**
/projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-ghg
- .r1i1p2f1.sha256sum_v20200218

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #271, #272 and #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-ghg
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-ghg

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-ghg
- .r1i1p2f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published
