### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - piClim-anthro (phys 2)

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#201]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS2345K/noresm/cases

**experiment_id**
piClim-anthro

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NF1850norbc_anthro2014_f19_20191025, 1-30

### Optional information

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 0421-01-01'

**branch_method**
'Hybrid-restart from year 1751-01-01 of piControl'

**other information**
physics = 2
I suggest to call this member r1i1p2f1

**Comment by YanchunHe** [comment]
cmorized and can be published

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-anthro
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-anthro

**version**
- v20200218

**sha256sum**
/projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/piClim-anthro
- .r1i1p2f1.sha256sum_v20200218

**Comment by monsieuralok** [comment]
@YanchunHe I guess it should be RFMIP

**Comment by YanchunHe** [comment]
Yes, you are right! corrected!

**Comment by monsieuralok** [comment]
@YanchunHe /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-anthro/.r1i1p2f1.sha256sum_v20200218 does not exists; should it be r1i1p1f1 or something wrong?

**Comment by YanchunHe** [comment]
OK, I find a script is outdated, so that it produces r1i1p1f1 instead of desired r2i1p2f2.

I fixed it and will do the cmorization again.

**Comment by YanchunHe** [comment]
Corrected, and it is now ready to be published. Commit: e0ff4778573b942ad7ccf7212dfbb2d0a50df292

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #271, #272 and #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/piClim-anthro
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-anthro

**version**
- v20210319

**sha256sum**
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/piClim-anthro
- .r1i1p2f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published
