### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-MM - historical (realisation 2)

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#211]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases

**experiment_id**
historical

**model_id**
NorESM2-MM

**CASENAME(s) and years to be CMORized**
NHISTfrc2_02_f09_tn14_20200427, 1850-1949
NHISTfrc2_02_f09_tn14_20200519, 1950-2014

### Optional information

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 1200-01-01'

**branch_method**
'Hybrid-restart from year 1230-01-01 of piControl'

**other information**
realisation = 2

**Comment by YanchunHe** [comment]
Cmorized and ready to be published

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/r2i1p1f1

**version**
- v20200218

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/r2i1p1f1
- .r2i1p1f1.sha256sum_v20200218

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
Cmorized with additional iLAMB variables (#262), AERday `zg500` (#263) and corrected `fNup` (#251).

They are ready to be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

**version**
- v20210203

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical
- .r2i1p1f1.sha256sum_v20210203

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #269, #270, #271, #272, #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical
- .r1i1p1f1.sha256sum_v20210319

Note, 6 hourly data are only available for years 121-150.

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by oyvindseland** [comment]
Asked for additional variables: 6hrPlevPt variables ps and snowmxrat  (1950-2014) and Amon snowmxrat.

**Comment by YanchunHe** [comment]
cmorized `snowmxrat`  for Emon (#82) and 6hrPlevPt (#109).

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical/
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

**version**
- v20210908

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical
- .r2i1p1f1.sha256sum_v20210908

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by monsieuralok** [comment]
@YanchunHe retracted and opened errata issue : -https://errata.es-doc.org/static/view.html?uid=ec9b772f-d4c8-1016-a09a-3d334bc8d751

**Comment by monsieuralok** [comment]
@YanchunHe Hi, should I publish above datasets? As, every netcdf file is having a single year.

**Comment by YanchunHe** [comment]
Yes, I think you can publish them. The data are saved in single year format, so that the size of each file is not too big. If I remember correctly, that is the reason.

cmorized `ta`, `ua` and `va` for `6hrLev`:

**data path**

* /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical
* /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

**version**
* v20221027

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

* .r2i1p1f1.sha256sum_v20221027

**Comment by monsieuralok** [comment]
@YanchunHe  published

**Comment by YanchunHe** [comment]
CMORized additional 3-hourly precipitation datasets.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical/
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

**version**
- v20230616

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical
- .r2i1p1f1.sha256sum_v20230616
