### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - hist-noLu

### ISSUE THREAD

**Issue by lca041** [NorESMhub/noresm2cmor#212]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases/b.e21.NHISTfrc2.f19_tn14-hist-noLu.001

**experiment_id**
hist-noLu

**model_id**

NorESM2-LM

**CASENAME(s) and years to be CMORized**
e.g., 
<strike>b.e21.NHISTfrc2.f19_tn14-hist-noLu.001, 1850-2015</strike>
b.e21.NHISTfrc2.f19_tn14-hist-noLu.001, 1850-2014

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**branch_method**
'Hybrid-restart from year 1600-01-01 of piControl',
 
**other information**
The sub-grid variables have already extracted and stored in the manner you requested.

**Comment by YanchunHe** [comment]
cmorized and ready to be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/hist-noLu
- /projects/NS9034K/CMIP6/LUMIP/NCC/NorESM2-LM/hist-noLu

**version**
- v20200702

**sha256sum**
/projects/NS9034K/CMIP6/LUMIP/NCC/NorESM2-LM/hist-noLu
- .r1i1p1f1.sha256sum_v20200702

commit: 52c7d63

**Comment by monsieuralok** [comment]
do not have write permission in : /projects/NS9034K/CMIP6/LUMIP/NCC/NorESM2-LM/hist-noLu

**Comment by YanchunHe** [comment]
write permission granted

**Comment by monsieuralok** [comment]
@YanchunHe @lca041 published
