### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-MM - historical (realisation 3)

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#229]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases

**experiment_id**
historical

**model_id**
NorESM2-MM

**CASENAME(s) and years to be CMORized**
NHISTfrc2_03_f09_tn14_20200519, 1850-1949
NHISTfrc2_03_f09_tn14_20200619, 1950-2014

### Optional information

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 1200-01-01'

**branch_method**
'Hybrid-restart from year 1260-01-01 of piControl',

**other information**
realisation = 3

**Comment by YanchunHe** [comment]
Hi,

I see the 1943-1949 data are missing for NHISTfrc2_03_f09_tn14_20200519.

And there is no read permission for some folders for NHISTfrc2_03_f09_tn14_20200519:
```
drwx------ 2 adagj ns9560k 4.0K Jun  7 20:42 lnd/
drwx------ 2 adagj ns9560k 4.0K Jun  7 20:42 logs/
drwx------ 2 adagj ns9560k 4.0K Jun  7 20:42 ocn/
drwx------ 2 adagj ns9560k 4.0K Jun  7 20:42 rest/
drwx------ 2 adagj ns9560k 4.0K Jun  7 20:42 rof/
```

**Comment by adagj** [comment]
Hi Yanchun,
Sorry for the delay. The data have been copied and the permission changed.

**Comment by YanchunHe** [comment]
Thanks Ada! I will cmorize these missing files.

**Comment by YanchunHe** [comment]
Hi Ada,

I find monthly ocean output micom.hm from 1861 are missing. And also yearly output is missing (not sure if this is desired). Please also check if all other components and years are at place. Thanks in advance!

Yanchun

**Comment by adagj** [comment]
Hi,
The data is still on FRAM, but I no longer have permission to copy the
data to /projects/NS9560K/noresm/cases/NHISTfrc2_03_f09_tn14_20200519. The
permission was changed after Jens copied some missing data. I'm not sure
why since it seems like the group permissions are correct. I'm now
transferring all the data
to /projects/NS9560K/noresm/cases/TMP_NHISTfrc_03/ on nird. I'll let you
know when the transfer has finished - sorry for the mess...

Ada

ons. 5. aug. 2020 kl. 10:55 skrev Yanchun He <notifications@github.com>:

**Comment by YanchunHe** [comment]
That is weird, I see there is write permission for group members of the NHISTfrc2_03_f09_tn14_20200519. But anyway, thanks for this, and please ask someone who can move the data to NHISTfrc2_03_f09_tn14_20200519 after the transfer is done.

I would recommend to do a rsync between Fram and NIRD to ensure all the data are properly copied.

Cheers,
Yanchun

**Comment by adagj** [comment]
Hi Yanchun,
I have transferred all the data to
/projects/NS9560K/noresm/cases/TMP_NHISTfrc_03/

(base) [adagj@login-1-2.FRAM /cluster/work/users/adagj/archive]$ rsync -av
--progress NHISTfrc2_03_f09_tn14_20200519
/tos-project3/NS9560K/noresm/cases/TMP_NHISTfrc_03
sending incremental file list

sent 1,430,429 bytes  received 89 bytes  25,318.90 bytes/sec
total size is 4,259,299,971,333  speedup is 2,977,452.90

If it is not too much work, can you please test to see if it is ok before I
delete the other folder?

Best,
Ada

ons. 5. aug. 2020 kl. 12:43 skrev Yanchun He <notifications@github.com>:

**Comment by YanchunHe** [comment]
Thanks! I see they should be completely synchronised.

I rename the old `NHISTfrc2_03_f09_tn14_20200519` to `NHISTfrc2_03_f09_tn14_20200519_nobackup`, and made a softlink of `TMP_NHISTfrc_03/NHISTfrc2_03_f09_tn14_20200519` to `NHISTfrc2_03_f09_tn14_20200519'.

I will restart the cmorization for years 1860-1950. After the cmorization is complete, you can remove those temporary folders and restore the temporary folder.

**Comment by YanchunHe** [comment]
CMORized, and is ready to be published to ESGF:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

**version**
- v20200702

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical
- .r3i1p1f1.sha256sum_v20200702

**Comment by monsieuralok** [comment]
@DirkOlivie @YanchunHe published

**Comment by YanchunHe** [comment]
Hi @adagj 

Could you move:
/projects/NS9560K/noresm/cases/TMP_NHISTfrc_03/NHISTfrc2_03_f09_tn14_20200519

under:
/projects/NS9560K/noresm/cases

as normal experiment case?

Thanks!

Yanchun

**Comment by YanchunHe** [comment]
I close it now.

Not updates related to #262, #263, and #251.

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270 #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical
- .r3i1p1f1.sha256sum_v20210319

Note, `chlos` and 'siareas` are only available between 1950-2014

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
cmorized `burtFractionAll` related to issue #286 

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical/v20210818
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r3i1p1f1

**version**
- v20210818

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r3i1p1f1
- .r1i1p1f1.sha256sum_v20210818

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
cmorized `snowmxrat`  for Emon (#82) and 6hrPlevPt (#109).

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical/
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

**version**
- v20210908

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical
- .r31i1p1f1.sha256sum_v20210908

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by monsieuralok** [comment]
@YanchunHe retracted

**Comment by YanchunHe** [comment]
CMORized additional 3-hourly precipitation datasets.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical/
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical

**version**
- v20230616

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical
- .r3i1p1f1.sha256sum_v20230616

**Comment by monsieuralok** [comment]
@YanchunHe published
