### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - 1pctCO2-bgc

### ISSUE THREAD

**Issue by tjiputra** [NorESMhub/noresm2cmor#235]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
<strike>/projects/NS9560K/noresm/cases/</strike>
/projects/NS2345K/noresm/cases/

**experiment_id**
1pctCO2-bgc 

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
<strike>N1PCTRADfrc2_f19_tn14_20191213</strike>
N1PCTBGC_f19_tn14_20190629

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1

**parent_time_units**
'days since 0421-01-01'

**branch_method**
e.g.,
'Hybrid-restart from year 1600-01-01 of piControl',

**other information**
path to parent: /projects/projects/NS2345K/noresm/cases/N1850_f19_tn14_11062019
case name of parent: N1850_f19_tn14_11062019

(updated 29 Sept: The published data should be retracted and need a new cmorization.)

**Comment by YanchunHe** [comment]
cmorized and can be published.

**data path**
- /projects/NS9034K/CMIP6/C4MIP/NCC/NorESM2-LM/1pctCO2-bgc
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/1pctCO2-bgc

**version**
- v20200702

**sha256sum**
/projects/NS9034K/CMIP6/C4MIP/NCC/NorESM2-LM/1pctCO2-bgc
- .r1i1p1f1.sha256sum_v20200702

**Comment by monsieuralok** [comment]
@YanchunHe There are some redundant link or missing link for data example: 
/projects/NS9034K/cmor/CMIP6/C4MIP/NCC/NorESM2-LM/1pctCO2-bgc/r1i1p1f1/Emon/nLeaf/gn/v20200702/nLeaf_Emon_NorESM2-LM_1pctCO2-bgc_r1i1p1f1_gn_000102-001012.nc
/projects/NS9034K/cmor/CMIP6/C4MIP/NCC/NorESM2-LM/1pctCO2-bgc/r1i1p1f1/Emon/nLitter/gn/v20200702/nLitter_Emon_NorESM2-LM_1pctCO2-bgc_r1i1p1f1_gn_000102-001012.nc
/projects/NS9034K/cmor/CMIP6/C4MIP/NCC/NorESM2-LM/1pctCO2-bgc/r1i1p1f1/Emon/fNloss/gn/v20200702/fNloss_Emon_NorESM2-LM_1pctCO2-bgc_r1i1p1f1_gn_000102-001012.nc
approx. 82 files please can you check them...

**Comment by YanchunHe** [comment]
I removed those broken links. Pease check again. Thanks!

**Comment by monsieuralok** [comment]
@tjiputra @YanchunHe published

**Comment by monsieuralok** [comment]
@YanchunHe do we need to retract whole experiment or fewer datasets? sorry, I have not followed whole discussion.

**Comment by YanchunHe** [comment]
quote J.T
> Someone alert me on the wrong simulation published in ESGF: 1pct-bgc
> It was indeed wrong, the full path should be:
/projects/NS2345K/noresm/cases/
>
>and the case name:
>N1PCTBGC_f19_tn14_20190629

**Need to retract the whole experiment from ESGF and redo the cmorization.**

(The top post has been updated with correct information)

**Comment by YanchunHe** [comment]
> @YanchunHe do we need to retract whole experiment or fewer datasets? sorry, I have not followed whole discussion.

Yes, @monsieuralok , please retract the whole experiment.

**Comment by monsieuralok** [comment]
@YanchunHe 1pctCO2-bgc  not 1pct-bgc? Just for confirmation as mentioned in above comment..

**Comment by YanchunHe** [comment]
> @YanchunHe 1pctCO2-bgc not 1pct-bgc? Just for confirmation as mentioned in above comment..

Oh, that should jut be a typo. I correct it.

Yes, should retract 1pctCO2-bgc.

**Comment by monsieuralok** [comment]
@YanchunHe did it.

**Comment by YanchunHe** [comment]
Hi @monsieuralok 

I see that I can still find and download this dataset on the ESGF node (the llnl node). Have this really retracted?

Could you also paste the link to the eos-doc/errata here each time when you retract or report a bug. Many thanks!

**Comment by monsieuralok** [comment]
Hi @YanchunHe 
                     I checked again the datasets donot exists on LIU server (C4MIP+1pctCO2-bgc) on that we are publishing. Now, how other severs are sync I am really not aware.  For retract data, we are not opening any issues on ERATTA as server will get sync they should disappear. Also if datasets donot exist then issue will not exist as it is linked to datasets. 
> 
> 
> Hi @monsieuralok
> 
> I see that I can still find and download this dataset on the ESGF node (the llnl node). Have this really retracted?
> 
> Could you also paste the link to the eos-doc/errata here each time when you retract or report a bug. Many thanks!

**Comment by monsieuralok** [comment]
@YanchunHe I also checked on https://esgf-node.llnl.gov/search/cmip6/ server that also do not have these data.

**Comment by YanchunHe** [comment]
> @YanchunHe I also checked on https://esgf-node.llnl.gov/search/cmip6/ server that also do not have these data.

OK, thanks! Maybe it takes some time for other replica to remove the data.

It is still there in 'llnl.gov' node if the 'Show All replicas' option is checked.

Anyway, I can now move local copy on NIRD.

**Comment by YanchunHe** [comment]
cmorized and can be published

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/1pctCO2-bgc
- /projects/NS9034K/CMIP6/C4MIP/NCC/NorESM2-LM/1pctCO2-bgc

**version**
- v20201001

**sha256sum**
/projects/NS9034K/CMIP6/C4MIP/NCC/NorESM2-LM/1pctCO2-bgc
- .r1i1p1f1.sha256sum_v20201001

**Comment by tjiputra** [comment]
Hi Yanchun @YanchunHe and Alok @monsieuralok,
Have this been re-published in ESGF? Someone reached out to me again noting the values of 1pctCO2-bgc in ESGF are still wrong.

many thanks,
jerry

**Comment by monsieuralok** [comment]
@tjiputra published it just now . Sorry, its got late as in meantime there have been many issues with NIRD and ESGF node. @YanchunHe in Earlier version there were 7254 files and now latest version have 7150 files. Could you check it once?

**Comment by YanchunHe** [comment]
> in Earlier version there were 7254 files and now latest version have 7150 files. Could you check it once?

The "earlier version" was actually from another experiment, which may have somewhat different configuration. It should be normal to have different fields.

So please go ahead with publish. I don't spot any issues. Thanks!

Yanchun

**Comment by monsieuralok** [comment]
@tjiputra @YanchunHe  published
