### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-MM ssp245 (realisation 2)

### ISSUE THREAD

**Issue by adagj** [NorESMhub/noresm2cmor#236]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/projects/NS9560K/noresm/cases/

**experiment_id**
ssp245 (r2i1p1f1)

**model_id**
NorESM2-MM

**CASENAME(s) and years to be CMORized**
NSSP245frc2_02_f09_tn14_20200629, 2015 - 2100

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
historical

**parent_experiment_rip**
r2i1p1f1

**parent_time_units**
'days since 1850-01-01 '

**branch_method**
e.g.,
'Hybrid-restart from year 2015-01-01 of historical',

**other information**
parent case name: /projects/projects/NS9560K/noresm/cases/NHISTfrc2_02_f09_tn14_20200519

**Comment by YanchunHe** [comment]
Hi @adagj , I understand this is hybrid restart from the realisation 2 of the MM historical run.

but I see the `parent_time_units` for the _parent case_ `NHISTfrc2_02_f09_tn14_20200519` is `days since 1850-01-01 00:00:00`.

So if you agree, I will update the 'parent_time_units' (which matters for a parameter 'branch_time_in_parent' for the cmorized data).

**Comment by adagj** [comment]
Hi @YanchunHe ,
yes that is correct. Thank you!

**Comment by YanchunHe** [comment]
cmorized and can be published:

**data path**
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp245/r2i1p1f1/
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/ssp245

**version**
- v20200702

**sha256sum**
/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp245
- .r2i1p1f1.sha256sum_v20200702

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
Cmorized with additional iLAMB variables (#262), AERday `zg500` (#263) and corrected `fNup` (#251).

They are ready to be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/ssp245
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp245

**version**
- v20210203

**sha256sum**
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp245
- .r2i1p1f1.sha256sum_v20210203

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #269, #270, #271, #272, #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/ssp245
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp245

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp245
- .r2i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
cmorized `burtFractionAll` related to issue #286 

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/ssp245/v20210818
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp245

**version**
- v20210818

**sha256sum**
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp245
- .r2i1p1f1.sha256sum_v20210818

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by monsieuralok** [comment]
@YanchunHe retracted
