### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - pa-pdSIC, r71i1p1f1 - r105i1p1f1

### ISSUE THREAD

**Issue by JensBDebernard** [NorESMhub/noresm2cmor#240]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
- Members 71-105
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03000
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03001
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03002
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03003
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03004
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03005
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03006
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03007
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03008
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03009
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03010
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03011
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03012
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03013
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03014
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03015
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03016
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03017
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03018
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03019
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03020
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03021
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03022
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03023
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03024
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03025
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03026
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03027
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03028
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03029
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03030
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03031
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03032
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03033
/projects/NS2345K/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03034

- Full path to post-processed fields epfy, epfz, utendepfd, vtem, wtem (Eliassen-Palm fluxes and friends):
- Members 71-105
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03000
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03001
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03002
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03003
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03004
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03005
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03006
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03007
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03008
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03009
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03010
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03011
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03012
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03013
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03014
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03015
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03016
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03017
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03018
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03019
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03020
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03021
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03022
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03023
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03024
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03025
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03026
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03027
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03028
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03029
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03030
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03031
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03032
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03033
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NHIST_f19_tn14_pamip2p1/NHIST_f19_tn14_pamip2p1_03034

**experiment_id**
pa-pdSIC

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NHIST_f19_tn14_pamip2p1_03000, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03001, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03002, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03003, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03004, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03005, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03006, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03007, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03008, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03009, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03010, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03011, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03012, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03013, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03014, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03015, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03016, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03017, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03018, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03019, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03020, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03021, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03022, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03023, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03024, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03025, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03026, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03027, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03028, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03029, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03030, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03031, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03032, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03033, June 1st 2000 - May 31st 2001
NHIST_f19_tn14_pamip2p1_03034, June 1st 2000 - May 31st 2001

### Optional information

**parent_experiment_id**
historical

**parent_experiment_rip**
r3i1p1

**parent_time_units**
'days since 1850-01-01'

**branch_method**
'Hybrid-restart from year 2000-04-01 of historic r3i1p1',

**other information**
Daily ice fields are collected together i daily files with the
structure casename.cice.h1.YYYY-MM.nc
Hybrid start from /projects/NS2345K/noresm/cases/NHIST_03_f19tn14_pamip-s_init which is a extension of the historical r3i1p1 from 2000-01-01 to 2000-04-01. Ice restart is aggregated to only one ice category.

**Comment by YanchunHe** [comment]
cmorized and be ready to publish to ESGF

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/pa-pdSIC
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-pdSIC

**version**
- v20200702

**sha256sum**
/projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-pdSIC
- .r71i1p1f1.sha256sum_v20200702
...
- .r105i1p1f1.sha256sum_v20200702

(realisation 71 to 105)

**Comment by monsieuralok** [comment]
@YanchunHe @JensBDebernard @lisesg published

**Comment by YanchunHe** [comment]
cmorized Z500 and with Omon, Ofx, Oyr and Emon, Eyr
Ready to be published to ESGF.

** data path **
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-pdSIC
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/pa-pdSIC

**version**
- v20201001

**sha256sum**
/projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-pdSIC
- .r71i1p1f1.sha256sum_v20201001
...
- .r105i1p1f1.sha256sum_v20201001

**Comment by monsieuralok** [comment]
@YanchunHe @JensBDebernard published
