### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM-LM - pa-pdSIC-ext

### ISSUE THREAD

**Issue by AleksiNummelin** [NorESMhub/noresm2cmor#244]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/tos-project1/NS2345K/noresm/cases/

**experiment_id**
pa-pdSIC-ext

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**

N2000_PAMIP_6_1_v1, 2000-2100

### Optional information

The start date is April 1st 2000 and the end date is April 1st in 2100

This is a hybrid run and the direct parent is NHIST_01_f19tn14_pamip-s_init which is just a direct continuation for 3 months of the NorESM2-LM historical simulation NHIST_f19_tn14_20190710 (in order to get the April restarts)

The historical simulation is located at /tos-project3/NS9560K/noresm/cases/NHIST_f19_tn14_20190710/

**parent_experiment_id**
historical

**parent_experiment_rip**
r1i1p1

**parent_time_units**

'days since 1850-01-01'

**branch_method**

Hybrid-restart from year 2000-04-01 of piControl

**other information**

Parent  /tos-project3/NS9560K/noresm/cases/NHIST_f19_tn14_20190710/

**Comment by AleksiNummelin** [comment]
There is an additional analysis step related to the E-P flux calculation and referring to an earlier email exchange, it would be great if @lisesg can do that first before proceeding with the CMORization. Let me know if you have any questions or if there are any issues!

**Comment by lisesg** [comment]
@AleksiNummelin, I will compute the EP fluxes straight away, but I can't access the data. Please update the permissions.

**Comment by lisesg** [comment]
EP fluxes have been computed and are available here: 
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/N2000_PAMIP_6_1_v1/

**Comment by YanchunHe** [comment]
Hi, I guess "N2000_PAMIP_6_1_v1 "  is not real 'experiment_id', but the case name.

It should be something like: 'pa-pdSIC'.

**Comment by AleksiNummelin** [comment]
Hi, sorry, those were the case names, here's the correct info

N2000_PAMIP_6_1_v1 means PAMIP 6.1 and the experiment name should be pa-pdSIC-ext

N2000_PAMIP_6_2_v3 means PAMIP 6.2 and the experiment name should be pa-futArcSIC-ext

reference: http://www.cesm.ucar.edu/projects/CMIP6/PAMIP/protocol.html#6

**Comment by YanchunHe** [comment]
cmorized and ready to be published to ESGF:
**data path**
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-pdSIC-ext
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/pa-pdSIC-ext

**version**
- v20200702

**sha256sum**
/projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-pdSIC-ext
.r1i1p1f1.sha256sum_v20200702

**Comment by monsieuralok** [comment]
@AleksiNummelin @YanchunHe published
