### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM -  pa-futArcSIC-ext

### ISSUE THREAD

**Issue by AleksiNummelin** [NorESMhub/noresm2cmor#245]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/tos-project1/NS2345K/noresm/cases/

**experiment_id**
 pa-futArcSIC-ext

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**

N2000_PAMIP_6_2_v3, 2000-2100

### Optional information

The start date is April 1st 2000 and the end date is April 1st in 2100

This is a hybrid run and the direct parent is NHIST_01_f19tn14_pamip-s_init which is just a direct continuation for 3 months of the NorESM2-LM historical simulation NHIST_f19_tn14_20190710 (in order to get the April restarts)

The historical simulation is located at /tos-project3/NS9560K/noresm/cases/NHIST_f19_tn14_20190710/

**parent_experiment_id**
historical

**parent_experiment_rip**
r1i1p1

**parent_time_units**

'days since 1850-01-01'

**branch_method**

Hybrid-restart from year 2000-04-01 of piControl

**other information**

Parent  /tos-project3/NS9560K/noresm/cases/NHIST_f19_tn14_20190710/

**Comment by AleksiNummelin** [comment]
There is an additional analysis step related to the E-P flux calculation and referring to an earlier email exchange, it would be great if @lisesg can do that first before proceeding with the CMORization. Let me know if you have any questions or if there are any issues!

**Comment by lisesg** [comment]
@AleksiNummelin Please update the permissions of the data. I'll start the script to compute the EP fluxes as soon as I have access.

**Comment by AleksiNummelin** [comment]
Thanks @lisesg  - the permissions should be open now!

**Comment by lisesg** [comment]
@AleksiNummelin I still can't access the data:
$ ls -l /tos-project1/NS2345K/noresm/cases/N2000_PAMIP_6_2_v3
ls: cannot open directory /tos-project1/NS2345K/noresm/cases/N2000_PAMIP_6_2_v3: Permission denied

**Comment by AleksiNummelin** [comment]
Are you member of the ns2345k project (I guess you should be!)?

**Comment by lisesg** [comment]
Yes, I'm a member of the ns2345k group. Did you remember to change the permissions of the top-level folder? 

drwx------  11 anu074   ns2345k       4096 Sep 15 07:26 N2000_PAMIP_6_2_v3

**Comment by AleksiNummelin** [comment]
Can you try again now, should be:

drwxr-x---  11 anu074   ns2345k       4096 Sep 13 17:51 N2000_PAMIP_6_1_v1
drwxr-x---  11 anu074   ns2345k       4096 Sep 15 07:26 N2000_PAMIP_6_2_v3

which I think should be okay?

**Comment by AleksiNummelin** [comment]
Okay, now it's finally

drwxr-xr-x  11 anu074   ns2345k       4096 Sep 13 17:51 N2000_PAMIP_6_1_v1
drwxr-xr-x  11 anu074   ns2345k       4096 Sep 15 07:26 N2000_PAMIP_6_2_v3

Which should work at least

**Comment by lisesg** [comment]
Thanks Aleksi, it works now! :) I've started the script, I'll let you know when it's done.

**Comment by lisesg** [comment]
Files with EP fluxes are available here:
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/N2000_PAMIP_6_2_v3/

**Comment by AleksiNummelin** [comment]
Thanks @lisesg!

@YanchunHe I'm not sure if you already started with CMORization, but I just realized that for some reason my rsync didn't complete and some of the ocean output was still left on Vilje. I'm copying that over now so should be there later today.

**Comment by YanchunHe** [comment]
cmorized and ready to be published to ESGF:
**data path**
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-futArcSIC-ext
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/pa-futArcSIC-ext

**version**
- v20200702

**sha256sum**
/projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-futArcSIC-ext
* .r1i1p1f1.sha256sum_v20200702

**Comment by monsieuralok** [comment]
@AleksiNummelin @YanchunHe published

**Comment by monsieuralok** [comment]
@YanchunHe something went wrong with few datasets as they published incomplete because I generated map files before SHA sum files were completed. I have retracted those but, I need to republish those with new data version. What name should I give for version  20200702b or ..? I will open an issue in errata.

**Comment by YanchunHe** [comment]
Yes, then it would be v20200702

**Comment by monsieuralok** [comment]
@YanchunHe  I will publish remaining two datasets those I retracted with version 20200703

**Comment by YanchunHe** [comment]
> @YanchunHe I will publish remaining two datasets those I retracted with version 20200703

Sounds OK, thanks!

**Comment by AleksiNummelin** [comment]
Thanks @monsieuralok!

**Comment by monsieuralok** [comment]
@YanchunHe @AleksiNummelin finally published remaining data for both experiments pa-pdSIC-ext and pa-futArcSIC-ext
