### ISSUE TITLE
Possible unit error in cmorized variable fNup

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#251]
Forwarded e-mail from the noresm-mailing list
Anyone who recognize this variable

Øyvind

---- Start e-mail
I've been looking at fNup in the CMIP6 simulations available on ESGF, and there's something a bit odd about the NorESM2 values. They're roughly 5 orders of magnitude bigger than I'd expect, given the values for the other models (particularly CESM2). 

An accident with formatting with days rather than seconds would probably account for this. *86400 gives a more sensible value. (No judgement here, formatting ncdf files is a pain.) Please can you check your data and let me know if this is the case? 

The file/s are: fNup_Emon_NorESM2-LM_historical_r1i1p1f1_gn_195001-195912 to the end of the historical simulation. I've briefly looked at fNup_Emon_NorESM2-LM_ssp370_r1i1p1f1_gn_201502-202012 and this seems to be out by about the same amount. 

Cheers,
T

-- 

T Davies-Barnard (she/her, please call me T)

College of Engineering, Mathematics and Physical Sciences
University of Exeter

----End e-mail

**Comment by lca041** [comment]
I have checked the CMOR table for the variable fNup, and it looks like the unit is in second. I could not find a reasonable answer to this abnormally bg value in NorESM2.

**Comment by kjetilaas** [comment]
Hi @oyvindseland and @YanchunHe . I have now looked into this with @huitang-earth, and it seems like the wrong variable has been used for the cmorization. "fNup_Emon_NorESM2..." seems to have used "SMINN_TO_PLANT" as the original variable. However, this variable is not used with the new FUN nitrogen uptake model. Instead, "NUPTAKE" should be used (like in CESM cmorized data).

**Comment by YanchunHe** [comment]
Thanks to looking into this, @kjetilaas !

Indeed `SMINN_TO_PLANT` is used as original input for `fNup`. This has been implemented for long as specified in the "CMIP6 data request Google Sheet file" (can share the link if you request). I can't recall when this is initially used.

If this is the case, all `fNup` in the cmorized and publish files are wrong.

Then we may need to report and errata in the ESGF Doc page, for all the published `fNup`, @monsieuralok ?

I don't think it is practical to retract all, redo the cmorization and republish `fNup` for all the experiments, but possibly we can recmorize some experiments if user really requests.

**Comment by monsieuralok** [comment]
@YanchunHe from which experiments should be retract fNup values?

**Comment by YanchunHe** [comment]
> @YanchunHe from which experiments should be retract fNup values?

We should retract it from all the experiments, as all of them are wrong.
I will have to recmorize at least the CMIP and ScenarioMIP experiments, and they should be republished.
Not clear for me how it is important for other experiments.

**Comment by monsieuralok** [comment]
@YanchunHe Should fNup be removed even recently published pi-Control experiment? That, I have published yesterday.

**Comment by YanchunHe** [comment]
Yes, please remove all of the existing fNup from ESGF, including the piControl exp.

**Comment by aliasaadi** [comment]
Hi @YanchunHe and @kjetilaas: I have now modified the Google Sheet file with the right variable. @oyvindseland was right, the two variables ("SMINN_TO_PLANT" and "NUPTAKE") differ roughly by five orders of magnitude.

**Comment by YanchunHe** [comment]
These new variables have been cmorized for (most of) the CMIP, AerChemMIP and ScenarioMIP experiments by NorESM2-LM and NorESM2-MM (as refereed by above list). They are in the queue to be published to ESGF.

Close this issue now.
(reopen whenever find needed)
