### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - PAMIP modelSST-pdSIC

### ISSUE THREAD

**Issue by lisesg** [NorESMhub/noresm2cmor#260]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
* Members 1-25:
/projects/NS2345K/noresm/cases/NFHISTnorpddmsbc_PAMIP_4p1_modelSST-pdSIC_mem1-25_f19_mg17_20201215
* Members 26-50:
/projects/NS2345K/noresm/cases/NFHISTnorpddmsbc_PAMIP_4p1_modelSST-pdSIC_mem26-50_f19_mg17_20201215
* Members 51-75:
/projects/NS2345K/noresm/cases/NFHISTnorpddmsbc_PAMIP_4p1_modelSST-pdSIC_mem51-75_f19_mg17_20201215
* Members 76-100:
/projects/NS2345K/noresm/cases/NFHISTnorpddmsbc_PAMIP_4p1_modelSST-pdSIC_mem76-100_f19_mg17_20201215

Full path to post-processed fields epfy, epfz, utendepfd, vtem, wtem (EP fluxes etc):
* Members 1-25:
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NFHISTnorpddmsbc_PAMIP_4p1_modelSST-pdSIC_mem1-25_f19_mg17_20201215
* Members 26-50:
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NFHISTnorpddmsbc_PAMIP_4p1_modelSST-pdSIC_mem26-50_f19_mg17_20201215
* Members 51-75:
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NFHISTnorpddmsbc_PAMIP_4p1_modelSST-pdSIC_mem51-75_f19_mg17_20201215
* Members 76-100:
/projects/NS2345K/noresm/work/lisesg/Eliassen-Palm-diags/noresm/cases/NFHISTnorpddmsbc_PAMIP_4p1_modelSST-pdSIC_mem76-100_f19_mg17_20201215

**experiment_id**
modelSST-pdSIC

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
* NFHISTnorpddmsbc_PAMIP_4p1_modelSST-pdSIC_mem1-25_f19_mg17_20201215: 
June 1st 2000 - May 31st 2001
* NFHISTnorpddmsbc_PAMIP_4p1_modelSST-pdSIC_mem26-50_f19_mg17_20201215: 
June 1st 2000 - May 31st 2001
* NFHISTnorpddmsbc_PAMIP_4p1_modelSST-pdSIC_mem51-75_f19_mg17_20201215: 
June 1st 2000 - May 31st 2001
* NFHISTnorpddmsbc_PAMIP_4p1_modelSST-pdSIC_mem76-100_f19_mg17_20201215: 
June 1st 2000 - May 31st 2001

### Optional information

**parent_experiment_id**
amip

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
days since 1975-01-01 00:00:00

**branch_method**
'Hybrid-restart from year 2000-04-01 of amip'

**other information**
The experiment is a hybrid run starting from /projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_f19_mg17_IC4PAMIP_20190816, which is an extension of the amip experiment carried out to provide restart and initial-condition files for the start date April 1st 2000.

**Comment by YanchunHe** [comment]
cmorized and be ready to publish to ESGF

**data path**

- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/modelSST-pdSI
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/modelSST-pdSI

**version**
- v20201001

**sha256sum**
- /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/modelSST-pdSI

.r11i1p1f1.sha256sum_v20201001
...
.r100i1p1f1.sha256sum_v20201001

**Comment by monsieuralok** [comment]
@YanchunHe published
