### ISSUE TITLE
Add fields for iLAMB variables

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#262]
quote (@kjetilaas ):
>since we are cmorizing the hist and scenario data again (issue #251), I wanted to bring up this email correspondence from last year about including the missing ILAMB variables on ESGF. From what I can see, it was seen as too much job to do at that time, but Lei was going to look into this.

>I was not involved when the initial decisions were made about which variables to cmorize, and as I understand this is the responsibility of the NORCE land modeling group (cc). But I am happy to contribute with input.

**Comment by aliasaadi** [comment]
@YanchunHe The Google Sheet file is now updated.

**Comment by YanchunHe** [comment]
Could you also paste these entries you added?

As I can see, this includes the following:

Table|Frequency|realm|variable|model variable
-- | -- | -- | -- | --
Emon | mon | land | tasLut | TSA
Eyr | yrPt | land | cLitter | TOTLITC
Eyr | yrPt | land | cSoil | TOTSOMC
Eyr | yrPt | land | cVeg | TOTVEGC
Lmon | mon | land | burntFractionAll | FAREA_BURNED
Lmon | mon | land | fLitterSoil | LITR1C_TO_SOIL1C+LITR2C_TO_SOIL1C+LITR2C_TO_SOIL2C+LITR3C_TO_SOIL2C+LITR3C_TO_SOIL3C

Please paste here if I missed something.

In addition, I see there are several variables are at 'yrPt' frequency (i.e., instantaneous annual output) 

I know only annul mean output with file name tag 'clm2.h4', but not 'instantaneous annual output'.

Please clarify. Thanks!

**Comment by aliasaadi** [comment]
Sorry! The first four rows (tasLut, cLitter, cSoil, and cVeg) are already provided with other frequencies, therefore not needed. The Google Sheet is updated accordingly.

**Comment by YanchunHe** [comment]
> Sorry! The first four rows (tasLut, cLitter, cSoil, and cVeg) are already provided with other frequencies, therefore not needed. The Google Sheet is updated accordingly.

OK, then two extra monthly fields need to be cmorized. I will look at this.

**Comment by YanchunHe** [comment]
Hi,

`LITR2C_TO_SOIL2C` and `LITR3C_TO_SOIL3C` are missing in both the `piControl` and `historical` experiments, at least.

Are they available in some experiments?

Otherwise, only `burntFractionAll` can be cmorized, but not for `fLitterSoil`

**Comment by aliasaadi** [comment]
Hi Yanchun,
The above-mentioned two variables (LITR2C_TO_SOIL2C and LITR3C_TO_SOIL3C) have been added to the Google Sheet before by other people. As shown in Figure 2.21.2 (attached) from the CLM5.0 user's guide (https://escomp.github.io/ctsm-docs/versions/release-clm5.0/html/tech_note/Decomposition/CLM50_Tech_Note_Decomposition.html), there won't be any LITR2C_TO_SOIL2C and LITR3C_TO_SOIL3C in the Century soil C pool structure, so I have removed them from the fLitterSoil row. 
![Screenshot from 2021-02-04 10-10-15](https://user-images.githubusercontent.com/72909806/106889580-7f5a4400-66e8-11eb-88fb-a8c14def96d8.png)

**Comment by YanchunHe** [comment]
Thanks, @aliasaadi ! Then I want to confirm that we will use `fLitterSoil =LITR1C_TO_SOIL1C+LITR2C_TO_SOIL1C+LITR3C_TO_SOIL2C` to derive the `fLitterSoil`, right?

**Comment by aliasaadi** [comment]
> Thanks, @aliasaadi ! Then I want to confirm that we will use `fLitterSoil =LITR1C_TO_SOIL1C+LITR2C_TO_SOIL1C+LITR3C_TO_SOIL2C` to derive the `fLitterSoil`, right?

Correct! J

**Comment by YanchunHe** [comment]
Could you see the files for:

* fLitterSoil
* burntFractionAll
* fNup

under:
* /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical/v20210203

Looks all right? 

If it is OK, I will then proceed with other experiments.

(relavant issues: #68, #69, #133)

**Comment by aliasaadi** [comment]
> Could you see the files for:
> 
> * fLitterSoil
> * burntFractionAll
> * fNup
> 
> under:
> 
> * NIRD: /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical/v20210203
> 
> Looks all right?
> 
> If it is OK, I will then proceed with other experiments.
> 
> (relavant issues: #68, #69, #133)

Thanks for doing this! Haven't seen anything strange, should be okay.

**Comment by YanchunHe** [comment]
Thanks!

**Comment by YanchunHe** [comment]
These new variables have been cmorized for (most of) the CMIP, AerChemMIP and ScenarioMIP experiments by NorESM2-LM and NorESM2-MM (as refereed by above list). They are in the queue to be published to ESGF.

Close this issue now.
(reopen whenever find needed)
