### ISSUE TITLE
Publish to ESGF 10 ensemble members of ssp245-covid (No.xx)

### ISSUE THREAD

**Issue by tjiputra** [NorESMhub/noresm2cmor#264]
Experiment(s) ready to be published to ESGF:
---

**data path**
 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp245-covid/v20201001

**activity_id:**
- DAMIP

**experiment_id**
- ssp245-covid

**Versions**
- v20201001

**other information**
- There are 10 ensemble in the directory, each should be published separately: r[1-10]i1p1f2

**Comment by YanchunHe** [comment]
reopen #250, #256, and close this duplicated issue.
