### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - histSST-piNTCF (phys 2)

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#267]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases

**experiment_id**
histSST-piNTCF

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NFHISTnorbc_pintcf_f19_20191107, 1850-2014

### Optional information

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 0421-01-01'

**branch_method**
'Hybrid-restart from year 1600-01-01 of piControl',

**other information**
realisation = 1
physics = 2
I suggest to call this member r1i1p2f1

**Comment by YanchunHe** [comment]
cmorized and can be published to ESGF

**data path**
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/histSST-piNTCF
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/histSST-piNTCF

**version**
- v20210218

**sha256sum**
/projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/histSST-piNTCF
- .r1i1p2f1.sha256sum_v20210218

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #271, #272 and #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/histSST-piNTCF
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/histSST-piNTCF

**version**
- v20210319

**sha256sum**
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/histSST-piNTCF
- .r1i1p2f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe this file does not exist /esg/data/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/AERmon/airmass/gn/v20210319/airmass_AERmon_NorESM2-MM_ssp585_r1i1p1f1_gn_201501-202012.nc There could be some others. But publishing failing at this point atleast.

**Comment by monsieuralok** [comment]
@YanchunHe published
