### ISSUE TITLE
[BUG] source/m_modelsocn.F INDEX in IF statement need to be tested for LOGICAL

### ISSUE THREAD

**Issue by annefou** [NorESMhub/noresm2cmor#268]
**Describe the bug**
source/m_modelsocn.F  line: 2854 - 2855
```
 INDEX(special,'dpint')
```
and 
```INDEX(special,'dpavg')```

 return integer and not logical as expected so we need to test for values (greater than 0).

```
 IF (INDEX(special,'2rho').GT.0.OR.INDEX(special,'2zoss').GT.0.OR.
     . INDEX(special,'strmf').GT.0.OR.INDEX(special,'Xfield2').GT.0.OR.
     . INDEX(special,'Dfield2').GT.0.OR.INDEX(special,'dpint').OR.
     . INDEX(special,'dpavg')) THEN
```
to be replaced by

```
 IF (INDEX(special,'2rho').GT.0.OR.INDEX(special,'2zoss').GT.0.OR.
     . INDEX(special,'strmf').GT.0.OR.INDEX(special,'Xfield2').GT.0.OR.
     . INDEX(special,'Dfield2').GT.0.OR.INDEX(special,'dpint').GT.0.OR.
     . INDEX(special,'dpavg').GT.0) THEN
```
Does not compile with gfortran 7.5.0.

**Expected behavior**
I expect the code to compile...

**Screenshots**

```
gfortran -O2 -fdefault-real-8 -I/opt/conda/envs/cmor/include -I/opt/conda/envs/cmor/include -I/opt/conda/envs/cmor/include -DCMOR3 -DDEFLATE -c ../source/m_modelsocn.F
../source/m_modelsocn.F:2854:40:

      . INDEX(special,'Dfield2').GT.0.OR.INDEX(special,'dpint').OR.
                                        1
Error: Operands of logical operator '.or.' at (1) are LOGICAL(4)/INTEGER(4)
Makefile_cmor3.jh_gnu:63: recipe for target 'm_modelsocn.o' failed
```

**Comment by YanchunHe** [comment]
Thanks for reporting!

But the error information indicates the old part is still used:
>>>
      . INDEX(special,'Dfield2').GT.0.OR.INDEX(special,'dpint').OR.
                                        1
    Error: Operands of logical operator '.or.' at (1) are LOGICAL(4)/INTEGER(4)
    Makefile_cmor3.jh_gnu:63: recipe for target 'm_modelsocn.o' failed

Are you sure it is really replaced with logical testing? maybe you should clean all temporary compiling files?

We usually use the 'intel' compiler, so I don't spot this incompatibility issue.

**Comment by annefou** [comment]
See https://gcc.gnu.org/onlinedocs/gfortran/INDEX-intrinsic.html

The return value is an integer.

I have no temporary compiling files (it compiles in a container).

**Comment by YanchunHe** [comment]
OK, as long as the fixed statement works with the gnu compiler in the container.

I update the code, commit: d469ce4389f1f2378099f95277f4a8dce99c981e
