### ISSUE TITLE
Error in 6 hourly output of precipitation

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#269]
Reported by Joan Saladich <joansaladich@gmail.com> (plots not attached here)

The file is the following:
filename: 'pr_6hrPlev_NorESM2-LM_ssp245_r1i1p1f1_gn_201501010000-202012312100.nc'
ESGF Node: IPSL
Tracking ID: hdl:21.14100/4d4db429-0957-49b7-ab47-0471c1f40a56

This file only weights 2 mb, while similar datasets weight 300 mb, the "pr" values are all empty values.

I would also like to ask you a question about the "pr" variable
1) The variable values that you provide (be it hourly, daily, etc.); is it an average or an accumulated for the given time step?
2) I haven't found any "prc" variable (convective precipitation). Could I assume that precipitation flux ("pr") includes the convective precipitation? @YanchunHe

**Comment by oyvindseland** [comment]
Checks and early comments: 
The error is also present at our ESGF node at several of the time-series files, The direct model output looks fine.
The variable pr is given as averaged values over the time period.
pr also include convective precipitation

**Comment by YanchunHe** [comment]
I find some other fields of 6hrPlev frequency of ssp126, ssp245, ssp585 are all incomplete. This mainly occurred during the time when Fram disk was temporary mounted to NIRD. I will fix this one by one.
This is related to issue: #179

**Comment by Joueswant** [comment]
Thanks for following up, I was downloading several historical and most of ssp scenarios of NorESM2-LM for the period between 1989-2040 frequency of  6h and variables "pr". I found two more files, so far:
- pr_6hrPlev_NorESM2-LM_ssp126_r1i1p1f1_gn_203101010300-204012311500
- pr_6hrPlev_NorESM2-LM_ssp245_r1i1p1f1_gn_201501010000-202012312100
- pr_6hrPlev_NorESM2-LM_ssp585_r1i1p1f1_gn_202101010300-203012312100
Yet files were downloaded few days ago, maybe @YanchunHe already fix it

**Comment by YanchunHe** [comment]
Hi @Joueswant,

Sorry but I have not fixed these yet. I want to check if there are other experiments suffer from the same problem. I am quite occupied the coming week, so I plan to work on this the week after, i.e., 15th March. Hope this is will not interrupt your workflow too much.

Yanchun

**Comment by oyvindseland** [comment]
Hi @Joueswant  To your question
"Does this means that you calculate an average (I guess a median) with a step of 6 hours?"
No the model accumulates the precipitation over the entire period and then divides by the length of the period.
So 1 mm/hour over 6 hours or 6 mm/hour in 1 hour and 0 for 5 hours will still average out to 1 mm/hour over the 6 hour period.

**Comment by Joueswant** [comment]
thanks a lot!

**Comment by YanchunHe** [comment]
After a through check, I find this error occurs for variables:
* bldep
* hurs
* hus
* huss
* pr
* ps
* psl
* sfcWind
* ta
* tas
* ts
* ua
* wap
* zg
* zg1000
* zg500

of the following frequency categories (`Table`):
* 6hrPlev (mainly)
* 6hrLev (a few)
* 6hrPlevPt (a few)

For the model version `NorESM2-LM`, the following experiments are affected:
* amip
* esm-ssp585
* ssp126
* ssp245
* ssp370
* ssp585

For the model version `NorESM2-MM`, the following experiments are affected:
* 1pctCO2
* abrupt-4xCO2
* historical
* piControl
* ssp126
* ssp245
* ssp370
* ssp585

**I will reopen the issues of the corresponding experiments to request for data retract. I will then redo the cmorization and request the data republish to ESGF.**

---
Specifically, the following dataset will be retracted and recmorized:
```
/projects/NS9034K/CMIP6/.cmorout/NorESM2-LM
./amip/v20191108b/bldep_6hrPlev*
./amip/v20191108b/hurs_6hrPlev*
./amip/v20191108b/hus_6hrPlev*
./amip/v20191108b/pr_6hrPlev*
./amip/v20191108b/psl_6hrPlev*
./amip/v20191108b/sfcWind_6hrPlev*
./amip/v20191108b/tas_6hrPlev*
./amip/v20191108b/wap_6hrPlev*
./amip/v20191108b/zg1000_6hrPlev*
./esm-ssp585/v20200218/hurs_6hrPlev*
./esm-ssp585/v20200218/hus_6hrPlev*
./esm-ssp585/v20200218/huss_6hrPlevPt*
./esm-ssp585/v20200218/pr_6hrPlev*
./esm-ssp585/v20200218/ps_6hrLev*
./esm-ssp585/v20200218/psl_6hrPlev*
./esm-ssp585/v20200218/psl_6hrPlevPt*
./esm-ssp585/v20200218/sfcWind_6hrPlev*
./esm-ssp585/v20200218/sfcWind_6hrPlevPt*
./esm-ssp585/v20200218/ta_6hrPlevPt*
./esm-ssp585/v20200218/tas_6hrPlev*
./esm-ssp585/v20200218/tas_6hrPlevPt*
./esm-ssp585/v20200218/ts_6hrPlevPt*
./esm-ssp585/v20200218/ua_6hrPlevPt*
./esm-ssp585/v20200218/wap_6hrPlev*
./esm-ssp585/v20200218/zg500_6hrPlevPt*
./esm-ssp585/v20200218/zg_6hrPlevPt*
./ssp126/v20191108/hurs_6hrPlev*
./ssp126/v20191108/hus_6hrPlev*
./ssp126/v20191108/pr_6hrPlev*
./ssp126/v20191108/psl_6hrPlev*
./ssp126/v20191108/sfcWind_6hrPlev*
./ssp126/v20191108/tas_6hrPlev*
./ssp126/v20191108/wap_6hrPlev*
./ssp245/v20191108/hurs_6hrPlev*
./ssp245/v20191108/hus_6hrPlev*
./ssp245/v20191108/pr_6hrPlev*
./ssp245/v20191108/psl_6hrPlev*
./ssp245/v20191108/sfcWind_6hrPlev*
./ssp245/v20191108/tas_6hrPlev*
./ssp245/v20191108/wap_6hrPlev*
./ssp370/v20191108/psl_6hrPlev*
./ssp370/v20191108/sfcWind_6hrPlev*
./ssp585/v20191108/hurs_6hrPlev*
./ssp585/v20191108/hus_6hrPlev*
./ssp585/v20191108/pr_6hrPlev*
./ssp585/v20191108/psl_6hrPlev*
./ssp585/v20191108/sfcWind_6hrPlev*
./ssp585/v20191108/tas_6hrPlev*
./ssp585/v20191108/wap_6hrPlev*
```

And:
```
/projects/NS9034K/CMIP6/.cmorout/NorESM2-MM
./1pctCO2/v20191108/hurs_6hrPlev*
./1pctCO2/v20191108/hus_6hrPlev*
./1pctCO2/v20191108/huss_6hrPlevPt*
./1pctCO2/v20191108/pr_6hrPlev*
./1pctCO2/v20191108/ps_6hrLev*
./1pctCO2/v20191108/psl_6hrPlev*
./1pctCO2/v20191108/psl_6hrPlevPt*
./1pctCO2/v20191108/sfcWind_6hrPlevPt*
./1pctCO2/v20191108/ta_6hrPlevPt*
./1pctCO2/v20191108/tas_6hrPlev*
./1pctCO2/v20191108/ts_6hrPlevPt*
./1pctCO2/v20191108/ua_6hrPlevPt*
./1pctCO2/v20191108/wap_6hrPlev*
./1pctCO2/v20191108/zg500_6hrPlevPt*
./abrupt-4xCO2/v20191108/hurs_6hrPlev*
./abrupt-4xCO2/v20191108/hus_6hrPlev*
./abrupt-4xCO2/v20191108/huss_6hrPlevPt*
./abrupt-4xCO2/v20191108/pr_6hrPlev*
./abrupt-4xCO2/v20191108/ps_6hrLev*
./abrupt-4xCO2/v20191108/psl_6hrPlev*
./abrupt-4xCO2/v20191108/psl_6hrPlevPt*
./abrupt-4xCO2/v20191108/sfcWind_6hrPlev*
./abrupt-4xCO2/v20191108/sfcWind_6hrPlevPt*
./abrupt-4xCO2/v20191108/ta_6hrPlevPt*
./abrupt-4xCO2/v20191108/tas_6hrPlevPt*
./abrupt-4xCO2/v20191108/zg500_6hrPlevPt*
./historical/v20200218/hurs_6hrPlev*
./historical/v20200218/hus_6hrPlev*
./historical/v20200218/huss_6hrPlevPt*
./historical/v20200218/pr_6hrPlev*
./historical/v20200218/ps_6hrLev*
./historical/v20200218/psl_6hrPlev*
./historical/v20200218/psl_6hrPlevPt*
./historical/v20200218/sfcWind_6hrPlev*
./historical/v20200218/sfcWind_6hrPlevPt*
./historical/v20200218/ta_6hrPlevPt*
./historical/v20200218/tas_6hrPlev*
./historical/v20200218/tas_6hrPlevPt*
./historical/v20200218/ts_6hrPlevPt*
./historical/v20200218/ua_6hrPlevPt*
./historical/v20200218/wap_6hrPlev*
./historical/v20200218/zg500_6hrPlevPt*
./piControl/v20191108/hurs_6hrPlev*
./piControl/v20191108/hus_6hrPlev*
./piControl/v20191108/huss_6hrPlevPt*
./piControl/v20191108/pr_6hrPlev*
./piControl/v20191108/ps_6hrLev*
./piControl/v20191108/psl_6hrPlev*
./piControl/v20191108/psl_6hrPlevPt*
./piControl/v20191108/sfcWind_6hrPlev*
./piControl/v20191108/sfcWind_6hrPlevPt*
./piControl/v20191108/ta_6hrPlevPt*
./piControl/v20191108/tas_6hrPlev*
./piControl/v20191108/tas_6hrPlevPt*
./piControl/v20191108/ts_6hrPlevPt*
./piControl/v20191108/ua_6hrPlevPt*
./piControl/v20191108/wap_6hrPlev*
./piControl/v20191108/zg500_6hrPlevPt*
./ssp126/v20191108/hurs_6hrPlev*
./ssp126/v20191108/hus_6hrPlev*
./ssp126/v20191108/pr_6hrPlev*
./ssp126/v20191108/psl_6hrPlev*
./ssp126/v20191108/sfcWind_6hrPlev*
./ssp126/v20191108/tas_6hrPlev*
./ssp126/v20191108/wap_6hrPlev*
./ssp245/v20191108/hurs_6hrPlev*
./ssp245/v20191108/hus_6hrPlev*
./ssp245/v20191108/pr_6hrPlev*
./ssp245/v20191108/psl_6hrPlev*
./ssp245/v20191108/sfcWind_6hrPlev*
./ssp245/v20191108/tas_6hrPlev*
./ssp245/v20191108/wap_6hrPlev*
./ssp370/v20191108/hurs_6hrPlev*
./ssp370/v20191108/hus_6hrPlev*
./ssp370/v20191108/pr_6hrPlev*
./ssp370/v20191108/psl_6hrPlev*
./ssp370/v20191108/sfcWind_6hrPlev*
./ssp370/v20191108/tas_6hrPlev*
./ssp370/v20191108/wap_6hrPlev*
./ssp585/v20191108/hurs_6hrPlev*
./ssp585/v20191108/hus_6hrPlev*
./ssp585/v20191108/pr_6hrPlev*
./ssp585/v20191108/psl_6hrPlev*
./ssp585/v20191108/sfcWind_6hrPlev*
./ssp585/v20191108/tas_6hrPlev*
./ssp585/v20191108/wap_6hrPlev*
```

**Comment by monsieuralok** [comment]
@YanchunHe in table for NorESM2-LM for experiment esm-ssp585 there are two rows for 6hrPlev; is it ok?

**Comment by YanchunHe** [comment]
> @YanchunHe in table for NorESM2-LM for experiment esm-ssp585 there are two rows for 6hrPlev; is it ok?

This is because the 'sort' command is quit tricky so that I did not sort out as I expected. With some tweak, these duplicated rows are now merged. It is updated.

**Comment by monsieuralok** [comment]
@YanchunHe NorESM2-LM data are retracted

**Comment by monsieuralok** [comment]
@YanchunHe NorESM2-MM data are also retracted.

**Comment by YanchunHe** [comment]
> @YanchunHe NorESM2-MM data are also retracted.

thanks a lot, Alok!

I am redoing the cmorization, and will update each relevant issues after it is ready to be published.

**Comment by YanchunHe** [comment]
Datasets have been recmorized for the above-referred datasets and are now in the queue to be republished to ESGF.

I close the issue now, and reopen when necessary.

Relates to commit: c4d6aa1
