### ISSUE TITLE
Identified issue with NorESM2-LM and NorESM2-MM 'siareas' CMIP variable

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#270]
Quote from C.Holmes at bas.ac.uk

> I have been using the variable 'siconc' to produce sea ice area, and the ready-produced 'siareas' (sea ice area south) where available as a cross-reference.

>For both NorESM2-LM and NorESM2-MM, I noticed a discrepancy between these two values and concluded the published 'siareas' dataset is erroneous. I concluded this for the following reasons
>The February minimum of the NorESM siareas in the published dataset is around 15Mkm2 (obs ~2, CMIP range ~0-6). However, the siconc distribution shows that the siarea values should not be a high outlier (see e.g. supplementary Figure S3 panels an and ao in https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2019GL086729)
>The seasonal cycle of the NorESM siareas in the published dataset has a double peak.
>Investigating further, the erroneous values are what I obtain if siconc is aggregated over the full globe and not only the southern hemisphere.
>
>This error exists in historical and each SSP under ScenarioMIP, I've not checked elsewhere.
>The "sivols" I have calculated appear to be the same as those provided. 
>
>I hope this is helpful, easily rectifiable, and that I have informed the right person.

C.H

**Comment by YanchunHe** [comment]
Quote J. Debernard.
>> Thank you for reporting this issue, and the very helpful information. 
> 
> I can confirm that the published siareas-values are aggregated over the whole globe, as you suggested. 
> When taking the difference between the published siareas values and the published siarean values, (global - Nh), the resulting Sh-values are identical (within run-off) to Sh-values I calculate independently. 
> 
> I can also confirm that this is only an issue with the siareas field, the siexts and sivols fields (which are calculated in a similar manner) look correct. 
> I also think I have spotted the reason for this error in a namelist file for our cmorization procedure, so unfortunately, I think this error is present in all our CMIP6 data. 
> 
> Many thanks for your effort concerning this matter.

**Comment by YanchunHe** [comment]
Alo, @monsieuralok, please retract all the `siareas` variable, for both NorESM2-LM and NorESM-MM. Thanks!

**Comment by monsieuralok** [comment]
@YanchunHe I have removed all siareas from NorESM2-LM and NorESM2-MM. Are we planning to republish them?

**Comment by YanchunHe** [comment]
> @YanchunHe I have removed all siareas from NorESM2-LM and NorESM2-MM. Are we planning to republish them?

Yes, @monsieuralok 

corrected `siareas` from some of the experiments will be published together with other fields!

**Comment by YanchunHe** [comment]
Datasets have been recmorized for the above-referred datasets (CMIP and ScenarioMIP experiments), and are now in the queue to be republished to ESGF.

I close the issue now, and reopen when necessary.

Relates to commit: c4d6aa1
