### ISSUE TITLE
Add CMIP6_AERmon table

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#271]
The following fields were defined in the NorESM CMOR table but not included due to an error in the definition of the added variables. Corrected in the table but also included here
Used in monthly mean files (h0)

drydust : DST_A2DDF+DST_A3SDDF+DST_A2_OCWDDF+DST_A3_OCWDDF
wetdust:  DST_A2SFWET+DST_A3SFWET+DST_A2_OCWSFWET+DST_A3_OCWSFWET

Needed for AerChemMIP, RFMIP and CMIP simulations, LM and MM, although not included in all ensemble members.

@YanchunHe @DirkOlivie @MichaelSchulzMETNO

**Comment by YanchunHe** [comment]
Should `DST_A3SDDF` be `DST_A3DDF` for the `drydust`?

**Comment by oyvindseland** [comment]
Yes. it should be DST_A3DDF. Sorry

**Comment by oyvindseland** [comment]
corrected also in the excel sheet

**Comment by YanchunHe** [comment]
Thanks, @oyvindseland !

A bunch of files for NorESM2-LM historical are cmorized under:
/projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical/v20210319

could you have a quick look if they looks OK?

Here I attached some time series of these variables:

## dryss
![dryss](https://user-images.githubusercontent.com/1725351/112305171-ac65b480-8c9e-11eb-875a-15d1c3c58433.png)

## dryoa
![dryoa](https://user-images.githubusercontent.com/1725351/112305295-cef7cd80-8c9e-11eb-98f9-5ba61b149c06.png)

## dry dust
![drydust](https://user-images.githubusercontent.com/1725351/112305341-dcad5300-8c9e-11eb-9fb3-938aef01b65e.png)

## wetdust
![wetdust](https://user-images.githubusercontent.com/1725351/112305361-e2a33400-8c9e-11eb-97f0-391d1910933f.png)

**Comment by oyvindseland** [comment]
Hi

The best check is to plot emidust-drydust+wetdust

This should be quite close to zero at least when averaged over a year.  The same holds true  for all the other variables as well 
(emi-dry+wet) @YanchunHe 

As you can see dry and wet both goes to the surface but are defined with different signs so that is the reason why it is emi-dry+wet.

Øyvind

**Comment by YanchunHe** [comment]
Thank, looks like the arithmetic `emi-dry+wet` of global average is of 10^-4 magnitude smaller of the mean. So I assume they are quite closed.

![dust](https://user-images.githubusercontent.com/1725351/112323053-b3e28900-8cb1-11eb-9a33-2e07babc6387.png)

**Comment by oyvindseland** [comment]
Yes and also both positive and negative so the long-terrm average should be even lower. 
There may be a slight trend inn the emissions and together with not perfect masse conservation I think it is fine.

**Comment by YanchunHe** [comment]
Datasets have been recmorized for the above-referred datasets (mainly CMIP and ScenarioMIP experiments) and are now in the queue to be republished to ESGF.

I close the issue now, and reopen when necessary.

Relates to commit: c4d6aa1
