### ISSUE TITLE
[BUG] Error in AERmon variables

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#272]
Error in AERmon variables dryss and dryoa. Must be retracted and republished. Not all output fields included.
dryso4 and drybc correct.

Simulations: AerChemMIP, RFMIP and CMIP 

Corrected in the table but also included here

dryss: SS_A1DDF + SS_A2DDF + SS_A3DDF +SS_A1_OCWDDF + SS_A2_OCWDDF + SS_A3_OCWDDF

dryoa: OM_ACDDF + OM_AIDDF + OM_NIDDF +OM_AC_OCWDDF + OM_AI_OCWDDF + OM_NI_OCWDDF

@YanchunHe @DirkOlivie @MichaelSchulzMETNO

**Comment by DirkOlivie** [comment]
@øyvind

I think we maybe have to change the expression for dryoa and wetoa, and include the contribution from SOA_A1 and SOA_NA dry and wet depostion.  In mmroa (which is used by many people to calculate the burden en then the lifetime) SOA_A1 and SOA_NA is included, and therefore I think it should be also included in dryoa and wetoa.

Could you check whether I see this right.

**Comment by oyvindseland** [comment]
@DirkOlivie 

Yes you are right. the secondary organic aerosols should also be included.

**Comment by YanchunHe** [comment]
OK, so then,
 the `dryoa` is:
 OM_ACDDF + OM_AIDDF + OM_NIDDF +OM_AC_OCWDDF + OM_AI_OCWDDF + OM_NI_OCWDDF + SOA_A1 + SOA_NA ;

and the `wetoa` is:
OM_ACSFWET+OM_AISFWET+OM_NISFWET+OM_AC_OCWSFWET+OM_AI_OCWSFWET+OM_NI_OCWSFWET+SOA_A1 + SOA_NA

??

Could you also go through the whole CMIP6_AERmon table variables, to check if others are correct (except for those dry dust, wetdust, dryss, dryoa, which has been corrected by not committed).

See the current list of supported variables of AERmon in https://github.com/NorESMhub/noresm2cmor/blob/master/namelists/var_CMIP6_NorESM2_default.nml

Not there are some duplicated entries of the same CMIP6 variable names, for example, `dryso4`. The last will override if both exist. Please let me know if you are sure that one of such option can be removed fro the `var_*.nml` file.

**Comment by DirkOlivie** [comment]
@YanchunHe 

dryoa should be :
OM_ACDDF + OM_AIDDF + OM_NIDDF +OM_AC_OCWDDF + OM_AI_OCWDDF + OM_NI_OCWDDF + SOA_A1DDF + SOA_NADDF + SOA_A1_OCWDDF + SOA_NA_OCWDDF

wetoa  should be :
OM_ACSFWET+OM_AISFWET+OM_NISFWET+OM_AC_OCWSFWET+OM_AI_OCWSFWET+OM_NI_OCWSFWET + SOA_A1SFWET + SOA_NASFWET + SOA_A1_OCWSFWET + SOA_NA_OCWSFWET

I'll try to have a look at the other variables too.

**Comment by DirkOlivie** [comment]
@YanchunHe @oyvindseland 

Another issue is that in all the cmorized wet-deposition fields for aerosols (wetoa, wetso4, wetbc, wetss, wetdst) the values are negative, whereas they are positive for the dry deposition fields.
This is because the raw aerosol wet-depostion fields are negative in NorESM.
Maybe we should also correct that.

**Comment by YanchunHe** [comment]
> @YanchunHe @oyvindseland
> 
> Another issue is that in all the cmorized wet-deposition fields for aerosols (wetoa, wetso4, wetbc, wetss, wetdst) the values are negative, whereas they are positive for the dry deposition fields.
> This is because the raw aerosol wet-depostion fields are negative in NorESM.
> Maybe we should also correct that.

Thanks! So we need to make all of those above aerosols positive sign? (absolute values)

And also please review other AERmon fields, so that I can proceed, and republish them together with other fixes.

We would better do this at once.

**Comment by DirkOlivie** [comment]
Hi @YanchunHe ,

shall I change the table
https://docs.google.com/spreadsheets/d/1-XOmrpOewOJ4msZ2cuQ41NRiMKgMZ5BfiNeAAFUsp3M/edit#gid=251590531
with the following modifications :
- the sign for the five aerosol deposition fields (wetoa, wetso4, wetbc, wetss, wetdst) 
- adding the contribution from SOA deposition to OA deposition (affects wetoa and dryoa)

**Comment by YanchunHe** [comment]
Yes, please do that! @DirkOlivie  Thanks!
If there is not other changes for the AERmon variables, I will proceed with the cmorization and publishing.

**Comment by DirkOlivie** [comment]
@YanchunHe 
I have now updated in the table the description of 
- wetoa, wetso4, wetbc, wetss, wetdst
- dryoa

**Comment by YanchunHe** [comment]
@DirkOlivie 

These mentioned data are processed under /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical/v20210319,

Could you have a look if they looks OK?

I also attached some global-averaged time series plots of these fields:

* CMIP.NCC.NorESM2-LM.historical.r1i1p1f1.AERmon.wetoa.gn.v20210319
![CMIP NCC NorESM2-LM historical r1i1p1f1 AERmon wetoa gn v20210319](https://user-images.githubusercontent.com/1725351/114160932-bedf1f80-9927-11eb-8c3c-2542f7a13150.png)

* CMIP.NCC.NorESM2-LM.historical.r1i1p1f1.AERmon.wetbc.gn.v20210319
![CMIP NCC NorESM2-LM historical r1i1p1f1 AERmon wetbc gn v20210319](https://user-images.githubusercontent.com/1725351/114161218-1b423f00-9928-11eb-9edc-a7ae671915e2.png)

* CMIP.NCC.NorESM2-LM.historical.r1i1p1f1.AERmon.wetdust.gn.v20210319
![CMIP NCC NorESM2-LM historical r1i1p1f1 AERmon wetdust gn v20210319](https://user-images.githubusercontent.com/1725351/114161249-239a7a00-9928-11eb-817c-2993bdcc2f0f.png)

* CMIP.NCC.NorESM2-LM.historical.r1i1p1f1.AERmon.wetso4.gn.v20210319
![CMIP NCC NorESM2-LM historical r1i1p1f1 AERmon wetso4 gn v20210319](https://user-images.githubusercontent.com/1725351/114161268-28f7c480-9928-11eb-8880-89e6643a747c.png)

* CMIP.NCC.NorESM2-LM.historical.r1i1p1f1.AERmon.wetss.gn.v20210319
![CMIP NCC NorESM2-LM historical r1i1p1f1 AERmon wetss gn v20210319](https://user-images.githubusercontent.com/1725351/114161282-2d23e200-9928-11eb-95d2-b914fbe1975d.png)

* CMIP.NCC.NorESM2-LM.historical.r1i1p1f1.AERmon.dryoa.gn.v20210319
![CMIP NCC NorESM2-LM historical r1i1p1f1 AERmon dryoa gn v20210319](https://user-images.githubusercontent.com/1725351/114161325-357c1d00-9928-11eb-8f4d-cfdc12b974f3.png)

**Comment by YanchunHe** [comment]
@monsieuralok 

Could you retract all `dryss` and `dryoa` variables of `AERmon` table for all experiments. Thanks!

I will recmorize some of them and republish.

**Comment by MichaelSchulzMETNO** [comment]
@YanchunHe 
Havent you recalculated all these: wetoa, wetso4, wetbc, wetss, wetdst, dryoa
Shouldnt all from all experiments be recomputed, retracted and republished then?

**Comment by MichaelSchulzMETNO** [comment]
By the way, I had checked the new wetoa and dryoa , compared to Gliss et al 2020 paper, and they seemed to be correct now.

**Comment by YanchunHe** [comment]
> Havent you recalculated all these: wetoa, wetso4, wetbc, wetss, wetdust, dryoa
Yes, I am doing this right now, and will be ready to be republished the next week.

@MichaelSchulzMETNO

**Comment by DirkOlivie** [comment]
@YanchunHe 
I have checked the wetss, wetdust, wetso4, wetbc, wetoa and dryoa and they seem ok.

**Comment by monsieuralok** [comment]
> 
> 
> @monsieuralok
> 
> Could you retract all `dryss` and `dryoa` and `wetoa` variables of `AERmon` table for all experiments. Thanks!
> 
> I will recmorize some of them and republish.

@YanchunHe do we need to remove all data from all experiments from NorESM2-LM and NorESM-MM  ? or only NorESM2-LM?

**Comment by YanchunHe** [comment]
Datasets have been recmorized for the above-referred datasets (mainly CMIP and ScenarioMIP experiments) and are now in the queue to be republished to ESGF.

I close the issue now, and reopen when necessary.

Relates to commit: c4d6aa1

**Comment by monsieuralok** [comment]
@YanchunHe do we need to remove all data from all experiments from NorESM2-LM and NorESM-MM ? or only NorESM2-LM?
Please could you reply regarding that?

**Comment by YanchunHe** [comment]
> @YanchunHe do we need to remove all data from all experiments from NorESM2-LM and NorESM-MM ? or only NorESM2-LM?
> Please could you reply regarding that?

Yes, please retract all the following dataset for all experiments, for both LM and MM
* dryss, dryoa, wetoa

And retract all the dataset of the following for CMIP and ScenarioMIp for LM and MM.
* wetso4, wetbc, wetss, wetdst

**Comment by monsieuralok** [comment]
@YanchunHe if I am correct for only AERmon frequency?

**Comment by YanchunHe** [comment]
Yes, I think they are only available in the AERmon frequency.

**Comment by monsieuralok** [comment]
> 
> 
> > @YanchunHe do we need to remove all data from all experiments from NorESM2-LM and NorESM-MM ? or only NorESM2-LM?
> > Please could you reply regarding that?
> 
> Yes, please retract all the following dataset for all experiments, for both LM and MM
> 
>     * dryss, dryoa, wetoa
> 
> 
> And retract all the dataset of the following for CMIP and ScenarioMIp for LM and MM.
> 
>     * wetso4, wetbc, wetss, wetdst

@YanchunHe  If I am correct wetdst is not published already for any experiments?

**Comment by YanchunHe** [comment]
You are right @monsieuralok , `wetdust` was not cmorized and published before.

(not a typo of `webdst`, should be `wetdust`. I correct this in the above comments)

**Comment by monsieuralok** [comment]
> 
> 
> You are right @monsieuralok , `wetdust` was not cmorized and published before.
> 
> (not a typo of `webdst`, should be `wetdust`. I correct this in the above comments)

@YanchunHe but, wetdust also does not exist for atleast NorESM2-LM and NorESM-MM in previously published experiment for CMIP and ScenarioMIP?

**Comment by YanchunHe** [comment]
Yes, your are right. `wetdust` does not exist for any previously published datasets.

(Sorry for the confusion, the 'auto-correction' of the keyboard input makes a lot of 'typos' for non-dictionary words.)

**Comment by MichaelSchulzMETNO** [comment]
drydust and wetdust should be published on **all** experiments indeed, where the output was save.,

**Comment by YanchunHe** [comment]
It is now only cmorized for CMIP and ScenarioMIP.

Can be quite a bit work to cmorize and publish all experiments.

But Alok and I can arrange that if this is necessary.

@monsieuralok  Alok, do you find it is OK to publish data for all experiments?

**Comment by MichaelSchulzMETNO** [comment]
Ok, priority would be to do also AerChemMIP and RFMIP experiments, please. All deposition data are useful here.

**Comment by monsieuralok** [comment]
@YanchunHe @MichaelSchulzMETNO I can start to publish already data those are CMORised. Today, my most time gone with ESGF server issues. But, all the open issues I will publish tomorrow.

**Comment by YanchunHe** [comment]
Thank you for the clarifying, @MichaelSchulzMETNO 

Sure, we can cmorize and publish AerChemMIP and RFMIP for this.

And if there are need for some other MIP, please point to us here. Thanks!

Yanchun

**Comment by monsieuralok** [comment]
@YanchunHe unpublished finally!!!
