### ISSUE TITLE
[ERROR] in chlos

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#273]
Quote josue.bock@laposte.net

> I noticed an issue with the missing data of variable chlos, for historical CMIP6 runs (‌all 3 realisations) in NorESM2-LM.

> The actual missing value (2439999920476782592) in files does not match the one set as _FillValue (1e+20). Thus it is not accounted as a missing, but as an existing (very high) value.

> As far as I can see, the problem has been solved in ssp585 files.

> All the best,

> Josué

**Comment by YanchunHe** [comment]
I checked through all experiments, this error occurs in only the following datasets:
* CMIP6.CMIP.NCC.NorESM2-LM.1pctCO2.r1i1p1f1.Omon.chlos.gn.v20190815
* CMIP6.CMIP.NCC.NorESM2-LM.historical.r1i1p1f1.Omon.chlos.gn.v20190815
* CMIP6.CMIP.NCC.NorESM2-LM.historical.r2i1p1f1.Omon.chlos.gn.v20190920
* CMIP6.CMIP.NCC.NorESM2-LM.historical.r3i1p1f1.Omon.chlos.gn.v20190920

They will be recmorized and published.

**Comment by YanchunHe** [comment]
Hi Alok, @monsieuralok Could you also retract the above mentioned datasets?  Thanks!

**Comment by monsieuralok** [comment]
@YanchunHe retracted all the above mentioned datasets

**Comment by YanchunHe** [comment]
Hi Alok,

I see those files are still available on the noresg.nird.noresm.no node, and can be downloaded? Are they really retracted?

<img width="1012" alt="Screenshot 2021-04-08 at 11 22 27" src="https://user-images.githubusercontent.com/1725351/114002018-c71e5880-985c-11eb-8522-ff6ec7a949f2.png">

**Comment by monsieuralok** [comment]
@YanchunHe sorry now it fixed; I did something wrong.

**Comment by YanchunHe** [comment]
Datasets have been recmorized for the above-referred datasets (mainly CMIP and ScenarioMIP experiments) and are now in the queue to be republished to ESGF.

I close the issue now, and reopen when necessary.

Relates to commit: c4d6aa1
