### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - amip (phys 2)

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#274]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases

**experiment_id**
amip

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NFHISTnorpddmsbc_f19_mg17_20191025, 1979-2014

### Optional information
hybrid from historical (NHIST_f19_tn14_20190710) on 1975-01-01

**parent_experiment_id**
no parent

**parent_experiment_rip**
no parent

**parent_time_units**

**branch_method**
Hybrid-restart from year 1975-01-01 of historical (NHIST_f19_tn14_20190710)

**other information**
realization = 1
physics = 2
I suggest to call this member r1i1p2f1
The experiment has started in 1975-01-01, as there was no restart available from the historical in 1979-01-01.   I would suggest to cmorize and put on ESGF the period 1979-2014.

**Comment by YanchunHe** [comment]
CMORized and are ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/amip
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip

**data version**
- v20210319b

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip
- .r1i1p2f1.sha256sum_v20210319b

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by monsieuralok** [comment]
@YanchunHe retracted
