### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-MM - hist-piAerOxid

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#275]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**

/projects/projects/NS9252K/noresm/cases

**experiment_id**

 hist-piAerOxid

**model_id**

NorESM2-MM

**CASENAME(s) and years to be CMORized**
e.g., 
NHISTpiaeroxid_f09_tn14_keyClim20201217  ,1850-2015

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
 
piControl

**parent_experiment_rip**

**parent_time_units**

**branch_method**
e.g.,
'Hybrid-restart from year 1200-01-01 of piControl',

**other information**
(provide other information that might be useful)
e.g., realisation, initialisation, etc...
and the cases name and path to the parent experiment, etc

**Comment by YanchunHe** [comment]
Looks like the `TSA` in the `land` component is wrong.
for example, `NHISTpiaeroxid_f09_tn14_keyClim20201217.clm2.h2.2010-01.nc`
![Screenshot 2021-05-25 at 11 39 11](https://user-images.githubusercontent.com/1725351/119476062-fece5a80-bd4d-11eb-8851-6697d084b4a4.png)

**Comment by oyvindseland** [comment]
Strange. I have not touched the land-model. I do not think many have need of this fields so just leave it out.

**Comment by YanchunHe** [comment]
The experiment is cmorized and is stored under /projects/NS9252K/cmorout/NorESM2-MM/hist-piAerOxid/v20210521

**Comment by oyvindseland** [comment]
I am sorry, I did not answer your question about where to place the data. ns9252k is probably fine for now. This will be relevant for all KeyClim experiments so we should discuss it at one of the meetings @lisesg

**Comment by YanchunHe** [comment]
> I am sorry, I did not answer your question about where to place the data. ns9252k is probably fine for now. This will be relevant for all KeyClim experiments so we should discuss it at one of the meetings @lisesg

Thanks, then I will close this issue.
