### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-MM  ssp370-piAerOxid

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#276]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/projects/NS9252K/noresm/cases

**experiment_id**
ssp370-piAerOxid

**model_id**
NorESM2-MM

**CASENAME(s) and years to be CMORized**

NSSP370piaeroxid_f09_tn14_keyClim20210210, 2015-2100

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**

hist-piAerOxid

**parent_experiment_rip**

**parent_time_units**

**branch_method**

'Hybrid-restart from year 2015-01-01 of hist-piAerOxid',

**other information**
(provide other information that might be useful)
e.g., realisation, initialisation, etc...
and the cases name and path to the parent experiment, etc

**Comment by YanchunHe** [comment]
Hi Øyvind, where do you think we should put the cmorized data?
`/projects/NS9252K/cmorout` ?

**Comment by YanchunHe** [comment]
The experiment is cmorized and is stored under `/projects/NS9252K/cmorout/NorESM2-MM/ssp370-piAerOxid/v20210521`

**Comment by YanchunHe** [comment]
I close this issue now.
