### ISSUE TITLE
[ERROR] in the land data for the NorESM2-LM ssp runs

### ISSUE THREAD

**Issue by aliasaadi** [NorESMhub/noresm2cmor#277]
**Describe the error**

January 2015 is missing for all the Lmon variables of the SSP runs under the following directory: "/nird/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM"
 
Example file name:
gpp_Lmon_NorESM2-LM_ssp585_r1i1p1f1_gn_201502-202012

**Comment by YanchunHe** [comment]
I will update all SSP* experiments, for relevant Emon, Lmon and LImon variables.

**Comment by YanchunHe** [comment]
The affected datasets have been recmorized and will be published to ESGF. I close this issue now. Reopen if necessary.

**Comment by aliasaadi** [comment]
Thank you so much!
