### ISSUE TITLE
extra files in the land data of the NorESM2-LM 1pctCO2-cdr run

### ISSUE THREAD

**Issue by aliasaadi** [NorESMhub/noresm2cmor#278]
**Describe the error**
Extra files ending with "014102-014912.nc" should be removed from the Lmon variables under "/nird/projects/NS9034K/CMIP6/CDRMIP/NCC/NorESM2-LM/1pctCO2-cdr/r1i1p1f1/Lmon"

**Comment by YanchunHe** [comment]
Thanks for reporting! These are all broken links, and have been removed.

Please reopen the issue if something new.
