### ISSUE TITLE
Inconsistent sea ice and ocean grids

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#279]
Quote S.Wang (FIO, CN).
>I found the sea ice products of NorESM2-LM are on a 360x384 grid, while the ocean products are on a 360x385 grid. When I calculate the areal summation of the ocean (e.g., total shortwave radiation), I resort to the file areacello_Ofx_NorESM2_LM_historical_r1i1p1d1_gn.nc. What file shall I use if I want to do the areal summation of the sea ice (e.g., sea ice volume in the Northern Hemisphere)?
 
> I think sea ice model should share the same mesh with the ocean model (and most of CMIP6 models do). So I feel confused why the sea ice component and the ocean component use different meshes in NorESM2-LM.

**Comment by YanchunHe** [comment]
Maybe Alok can report this as an issue/warning for all `areacello`, `thkcello` and `volcello` variables in the ESGF doc? Not that the last column j=385 can be dropped when using these variables as masks/weights for sea-ice variables?
@monsieuralok

**Comment by monsieuralok** [comment]
@YanchunHe do we need to mention it for all experiments and variables areacello, thkcello and volcello ?

**Comment by monsieuralok** [comment]
@YanchunHe opened errata issue https://errata.es-doc.org/static/view.html?uid=fe3ef410-e0e9-24d6-a987-35285dc3c66f and it would be nice if you could check it once.
