### ISSUE TITLE
[ERROR] cmorized ocean vertical velocity

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#280]
Quote A. Gjermundsen
> I wonder if there is something wrong with the cmorized wo variables.
when looking at wo in gn grid the values range from -0.0012 to 0.001 m/s. For the same variable, experiment and time period in the cmorized gr files, wo values range from -0.0016 to 1.88e8. It seems to me that all bottom values (or where there is bathymetry) are given in the range 1e7 to 1.9e8 instead of nan-

>E.g.
/nird/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl/r1i1p1f1/Omon/wo/gn/latest/wo_Omon_NorESM2-LM_piControl_r1i1p1f1_gn_160001-160912.nc

>/nird/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl/r1i1p1f1/Omon/wo/gr/latest/wo_Omon_NorESM2-LM_piControl_r1i1p1f1_gr_160001-160912.nc

**Comment by YanchunHe** [comment]
You are right, @adagj . The noresm2cmor tool uses the surface grid to mask the ocean grid of missing values, so that it fails to identify the missing value points in vertically interpolated data of marginal seas.

It is hard to redo the cmorization of `wo` for all the experiments, but should be possible to report an issue at ESGF, that resetting all values larger than 1 should be a quick fix.

Alok, could you report this issue at ESGF for all the published `wo` on `gr` grid (data on `gn` grid are OK). @monsieuralok 

I can reprocess `wo` on `gr` for all CMIP and SenarioMIP experiments, if you find useful, Ada!

**Comment by adagj** [comment]
@YanchunHe 
For my sake, you don't need to reprocess anything. I set all wo larger than 1 to nan (as you also suggested) in my scripts and the results seem reasonable. I just wanted to let you know :)

Ada

**Comment by YanchunHe** [comment]
Alok, could you report this issue at ESGF for all the published wo on gr grid (data on gn grid are OK). @monsieuralok

A quick fix is to set `wo` to NaN when it is larger than 1.

**Comment by monsieuralok** [comment]
@YanchunHe would this issue will be fixed in future version? or if already some data are published with fixed?

**Comment by monsieuralok** [comment]
@YanchunHe https://errata.es-doc.org/static/view.html?uid=62a25f76-78f6-e46f-9a7c-e890ee22e518 I have mentioned it on errata.

**Comment by YanchunHe** [comment]
Thanks Alok! Cmorized data in the future will not have this issue. Already published data will be not changed. This errata should be enough.
