### ISSUE TITLE
Check for unit error in field sndmasssnf in SImon NorESM2-LM and MM

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#282]
Possible unit error in the field sndmasssnf in Simon. The unit is given as kg m-2 s-1 but the values seem to be 1 000 times too high both when comparing to other models but also compared to the loss term sndmassmelt. sndmassmelt give the expected values.

**Way to correct**

Check and confirm if this is a unit error.
Adjust the number to the correct unit starting with scenarios as this is where a user reported the problem, although just confirm that the unit is wrong will help users.

@JensBDebernard

**Comment by JensBDebernard** [comment]
I have confirmed that this is a bug in the output from the ice model. 
By accident the sndmasssnf field was multiplied by the density of model snow (330 kg/m^3) while preparing the output. The error has been corrected in newer versions of CESM. It is not an error in the cmorization step, but in the history output from the ice model. Thus, all NorESM2 results up to now have this bug. 

**Way to correct**
This error can be corrected in all cmorized fields by dividing the sndmasssnf field by 330. 

**Further steps **
The error should  be corrected in new versions of NorESM, but we will then need a check during the cmorization step to ensure that the correct version of the model has been

**Comment by YanchunHe** [comment]
Hi @oyvindseland @JensBDebernard 

Can we just report an errata for the published datasets, and make fix (divide 330 during cmorization for future experiments until new version of NorESM)?

**Comment by YanchunHe** [comment]
fixed in commit `9b4b7db`

datasets of `sndmasssnf` newer from v20210811 will be divided with 330.

Please notice me (preferably reopen this issue if you have fixed this in the model source code, so that we have to remove this divisor number in the cmorisation).

**Comment by monsieuralok** [comment]
@YanchunHe do we need to report this also for NorESM1-F? or only for NorESM2-LM and NorESM2-MM?

**Comment by YanchunHe** [comment]
That is a good question!

@ChunchengGuo Can you answer this?

Otherwise, the fix by dividing 330 is not valid for NorESM1-F.

**Comment by monsieuralok** [comment]
@YanchunHe opend errata issue : https://errata.es-doc.org/static/view.html?uid=f05051d2-99ad-402c-834c-d0acc8fdf482 as NorESM1-F does not have this data.

**Comment by ChunchengGuo** [comment]
> @YanchunHe opend errata issue : https://errata.es-doc.org/static/view.html?uid=f05051d2-99ad-402c-834c-d0acc8fdf482 as NorESM1-F does not have this data.

yeah, NorESM2 have more output than NorESM1-F. It is not unexpected that NorESM1-F does not have this variable.
