### ISSUE TITLE
[question] regarding CMIP6 burntFractionAll

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#286]
Quote Yan Yu (princeton.edu)

> I'm analyzing CMIP6 burned area (burntFractionAll) from both historical and ScenarioMIP simulations. 
> 
> It looks like burntFractionAll from both NorESM2-LM and NorESM2-MM in all the historical and ScenarioMIP experiments are several orders of magnitude smaller than other ESMs. I wonder if there is any error in the units conversion.

**Comment by oyvindseland** [comment]
I just had a quick glance into the results, cmorized and native output and it looks like the cmorized output is given in percent / second, not as accumulated percentage
I have not looked into the cmor definition of the unit the unit but  the cmorized file says just percentage with no time unitss

I made a simple check by looking at random example (NorESM2-LM, historical ensemble 1 2014-01)  
The highest burned area fraction is given as approximately 7*10 -8 s-1. This give around 20 % burned area for the entire month, while the cmorized data give approximately  7*10-6 (no defined units)

**Comment by YanchunHe** [comment]
The cmorized data uses the unit `%` for `burntFractionAll`.
It uses the variable `FAREA_BURNED` in the original model output as input, but multiple 100.

in the CMIP6 tabel definition `CMIP6_Lmon.json` :
```json
        "burntFractionAll": {
            "frequency": "mon",
            "modeling_realm": "land",
            "standard_name": "area_fraction",
            "units": "%",
            "cell_methods": "area: mean where land over all_area_types time: mean",
```
The time method is `mean` instead of accumulation.

What is the correct fix?

**Comment by YanchunHe** [comment]
Hi Øyvind @oyvindseland ,

So if we can have a quick fix by multiplying 30 days*24 hours*3600seconds*100 percent for model ouput `FAREA_BURNED` during cmorization?

For the already published data, Alok can report an erratum for this. For datasets published in the future, this will be fixed.

yanchun

**Comment by oyvindseland** [comment]
Yes, this quick fix will work

I hope that it is possible to use the actual number of days for each month instead of 30 days though

**Comment by YanchunHe** [comment]
OK, this will be fixed in the future released datasets (accumulated with the actual days of month).

**Comment by YanchunHe** [comment]
@monsieuralok 

Alok, would you report an erratum for this variable for all experiments, that the monthl (Lmon) burntFractionAll should multiply with the number of seconds in a month, 
ie.. number of days in a month * 24 hours*3600seconds*100 percent.

datasets newer than version 20210818 will be free with this issue.

**Comment by CGL5230** [comment]
I download the NorESM  burnFractionAll from CMIP6 data pool. Now the NorESM values seem to be somewhat corrected, but still underestimated. It's probably about 2-3 times lower than other models.

**Comment by JorgSchwinger** [comment]
If you look here (Fig. 2)

https://doi.org/10.5194/gmd-2024-85

NorESM looks fine for present day (2001–2014 average). NorESM2-LM is a bit lower than many other models, but nothing suspicious. I'm also not entirely sure which version of the data was used and if a correction was applied to NorESM data (I can check if necessary).

**Comment by JorgSchwinger** [comment]
I have randomly downloaded burntFractionAll for the beginning of SSP5-8.5 from NorESM2 and CESM2. They look very similar (of course because it is the same land model), which indicates that our data should be correct unless both NCAR and we did the same unit conversion error.

Maybe you can check which version of the data you downloaded? Which are the other models shown above? What are the units?

**Comment by CGL5230** [comment]
I want to share the data I download from CMIP6, but it's too large. Here is the name of NorESM(burntFractionAll_Lmon_NorESM2-MM_ssp585_r1i1p1f1_gn_201501-210012) and CESM2(burntFractionAll_Lmon_CESM2-WACCM_ssp585_r1i1p1f1_gn_201501-210012). 

I hope this will help. Perhaps I can send an email with the test data attached to your email address, if you will.
