### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - piClim-spAer-histaer (phys 2)

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#290]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases

**experiment_id**
piClim-spAer-histaer

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NFHISTnorpibc_spAer_aeronly_f19_20210523, 1850-2014

### Optional information

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 0421-01-01'

**branch_method**
'Hybrid-restart from year 1600-01-01 of piControl'

**other information**
physics = 2
I suggest to call this member r1i1p2f1

**Comment by YanchunHe** [comment]
cmorized and ready to be published to ESGF:

**data path**
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-spAer-histaer
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-spAer-histaer

**version**
- v20210811

**sha256sum**
/projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-spAer-histaer
- .r2i1p1f1.sha256sum_v20210811

**Comment by monsieuralok** [comment]
@YanchunHe published on 24th August
