### ISSUE TITLE
[ERROR] too much siarean from NorESM1-F

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#295]
**Describe the error**
Quote "S.Z.Wang"
>I found the siarean output from the PI simulation of NorESM2-LM is ok, but the output of NorESM1-F seems to be extremely higher by two orders of magnitude. Is this the mode bias or an issue related to cmorization?

**Comment by ChunchengGuo** [comment]
This is because in NorESM1-F output, the unit of sea ice area (aice) is '%', whereas it is '1' in NorESM2. So that makes a two order difference in the aggregated 'siarean' variable. So not a model bias - just divide it by 100 in the NorESM1-F 'siarean'.

**Comment by YanchunHe** [comment]
do we need to report an erratum at ESGF for NorESM1-F? @ChunchengGuo

**Comment by ChunchengGuo** [comment]
NorESM1-F is like a CMIP6 'fringe' model mostly used for PMIP4 simulations, and this variable is perhaps not so important in the paleo-modelling community, but if not much work would be good to report it (together with the corresponding siareas).

**Comment by YanchunHe** [comment]
OK, thanks, @ChunchengGuo 
@monsieuralok Could you report and errata for `siarean` and `siareas` for experiments by `NorESM1-F`? Thanks!

**Comment by monsieuralok** [comment]
@YanchunHe @ChunchengGuo if I am correct siareas is in % in NorESM1-F and for comparison siarean should be divided by 100 if comparing within CMIP6 (not with CMIP5 if I am correct)?

**Comment by YanchunHe** [comment]
Yes, I think so. thanks! @monsieuralok

**Comment by ChunchengGuo** [comment]
> @YanchunHe @ChunchengGuo if I am correct siareas is in % in NorESM1-F and for comparison siarean should be divided by 100 if comparing within CMIP6 (not with CMIP5 if I am correct)?

@monsieuralok no, this is not correct.

both siarean and siareas should be divided by 100.

**Comment by monsieuralok** [comment]
@YanchunHe  Errata issue opened : https://errata.es-doc.org/static/view.html?uid=cff04045-deec-0b53-9301-7852166d493f

**Comment by YanchunHe** [comment]
Thank you, Alok!
