### ISSUE TITLE
[ERROR] superfluous daily NorESM-LM data for ssp126

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#296]
**Describe the error**
Quote M.Sandstad:
> the ssp126 daily data for NorESM-LM. For all of the variables, there seem to be three superfluous files running over the time periods 2031-2040, 2061-2070 and 2081-2090, all of them missing data for December the 31st of the last of the years. Files for the same time periods including the New Years Eve data also exist. Is there a reason for why these files are included in the “official” datasets (this is true for what is available on esgf as well as on nird) for ssp126 daily NorESM-LM data?

**Way to correct**
Retract the data from ESGF?

**Comment by YanchunHe** [comment]
I can't recall how did this exactly happen, but seems like this discrepancy was introduced during I was away on vacation 2019/2020 when Jang helps to do the cmorization work.

for example, 
```
/projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp126/v20191108
$ ls -l tas_day_NorESM2-LM_ssp126_r1i1p1f1_gn_20*
-rw-rw-r-- 1 yanchun ns9034k  71956197 Dec  6  2019 tas_day_NorESM2-LM_ssp126_r1i1p1f1_gn_20150101-20201231.nc
-rw-rw-r-- 1 yanchun ns9034k 119908659 Nov 22  2019 tas_day_NorESM2-LM_ssp126_r1i1p1f1_gn_20210101-20301231.nc
-rw-rw-r-- 1 jang    ns9034k 119830523 Dec 18  2019 tas_day_NorESM2-LM_ssp126_r1i1p1f1_gn_20310101-20401230.nc
-rw-rw-r-- 1 yanchun ns9034k 119863505 Dec  4  2019 tas_day_NorESM2-LM_ssp126_r1i1p1f1_gn_20310101-20401231.nc
-rw-rw-r-- 1 yanchun ns9034k 119879459 Nov 23  2019 tas_day_NorESM2-LM_ssp126_r1i1p1f1_gn_20410101-20501231.nc
-rw-rw-r-- 1 yanchun ns9034k 119834280 Dec  2  2019 tas_day_NorESM2-LM_ssp126_r1i1p1f1_gn_20510101-20601231.nc
-rw-rw-r-- 1 jang    ns9034k 119835938 Dec 19  2019 tas_day_NorESM2-LM_ssp126_r1i1p1f1_gn_20610101-20701230.nc
-rw-rw-r-- 1 yanchun ns9034k 119868817 Dec  3  2019 tas_day_NorESM2-LM_ssp126_r1i1p1f1_gn_20610101-20701231.nc
-rw-rw-r-- 1 yanchun ns9034k 119835662 Nov 23  2019 tas_day_NorESM2-LM_ssp126_r1i1p1f1_gn_20710101-20801231.nc
-rw-rw-r-- 1 jang    ns9034k 119854545 Dec 19  2019 tas_day_NorESM2-LM_ssp126_r1i1p1f1_gn_20810101-20901230.nc
-rw-rw-r-- 1 yanchun ns9034k 119887419 Dec  6  2019 tas_day_NorESM2-LM_ssp126_r1i1p1f1_gn_20810101-20901231.nc
-rw-rw-r-- 1 yanchun ns9034k 119914173 Nov 24  2019 tas_day_NorESM2-LM_ssp126_r1i1p1f1_gn_20910101-21001231.nc
```

There are in total 258 daily files of ssp126, that are superfluous and need to be retracted.

These files can be listed with the following command:
```bash
$ cd /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp126/v20191108
$ ls -l *day*1230.nc
```

@monsieuralok , could you retract these data? and I can then remove them from NIRD. Thanks!

Yanchun

**Comment by monsieuralok** [comment]
@YanchunHe we can not remove a single file then, we have to retract the whole datasets and I noticed there are many variables. Then we need to remove whole data from those variables and republish then with different version. There are many variables including different frequency around 86. What would be yours suggestion removing whole experiment or remove all datasets related to these variables?

**Comment by oyvindseland** [comment]
Add the information in errata? As long as the content are identical except for the missing day, it should not make for any science mistakes at least.

**Comment by YanchunHe** [comment]
> Add the information in errata? As long as the content are identical except for the missing day, it should not make for any science mistakes at least.

Then I agree an erratum might suffice.

**Comment by monsieuralok** [comment]
@YanchunHe opened errata issue : https://errata.es-doc.org/static/view.html?uid=6f82a8ee-7f48-1f7e-8bd9-d998989d6cb2

**Comment by YanchunHe** [comment]
Thanks @monsieuralok 

There are another files side by side which have the last day of the year (1231). So people should just ignore this file missing the last day, but use the other one with full record.

I close this issue now.
