### ISSUE TITLE
Variable found on ESG node but not published: Ozone

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#297]
From: Studholme Joshua 

I’m trying to track down as much ozone data as possible from CMIP6 and see that the data from NorESM2-MM is not uploaded yet. (var: ‘o3’, table_id: ‘Amon’, run_id: ‘pi_control').

Please may I ask whether it would be possible to access this data?

**Comment by oyvindseland** [comment]
I checked the ESG node and the ozone fields are cmorized but not publicly available. Is this an error or is it a choice due to the fact that ozone is prescribed and not prognostic.

@DirkOlivie @YanchunHe

**Comment by DirkOlivie** [comment]
I am not aware of a reason not to make it available (it is true that it is prescribed).

@YanchunHe @oyvindseland

**Comment by YanchunHe** [comment]
Hi, I see `o3` for all `NorESM2-MM` are available through ESGF. So I don't understand where is the real problem?

```bash
$ synda search source_id=NorESM2-MM variable_id=o3
new  CMIP6.CMIP.NCC.NorESM2-MM.historical.r1i1p1f1.AERmon.o3.gn.v20191108
new  CMIP6.CMIP.NCC.NorESM2-MM.historical.r1i1p1f1.Amon.o3.gn.v20191108
new  CMIP6.CMIP.NCC.NorESM2-MM.1pctCO2.r1i1p1f1.AERmon.o3.gn.v20191108
new  CMIP6.CMIP.NCC.NorESM2-MM.1pctCO2.r1i1p1f1.Amon.o3.gn.v20191108
new  CMIP6.CMIP.NCC.NorESM2-MM.abrupt-4xCO2.r1i1p1f1.AERmon.o3.gn.v20191108
new  CMIP6.CMIP.NCC.NorESM2-MM.abrupt-4xCO2.r1i1p1f1.Amon.o3.gn.v20191108
new  CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.Amon.o3.gn.v20191108
new  CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.AERmon.o3.gn.v20191108
new  CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp370.r1i1p1f1.AERmon.o3.gn.v20191108
new  CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp126.r1i1p1f1.Amon.o3.gn.v20191108
new  CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp245.r1i1p1f1.AERmon.o3.gn.v20191108
new  CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp245.r1i1p1f1.Amon.o3.gn.v20191108
new  CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp126.r1i1p1f1.AERmon.o3.gn.v20191108
new  CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp370.r1i1p1f1.Amon.o3.gn.v20191108
new  CMIP6.CMIP.NCC.NorESM2-MM.historical.r2i1p1f1.Amon.o3.gn.v20200218
new  CMIP6.CMIP.NCC.NorESM2-MM.historical.r2i1p1f1.AERmon.o3.gn.v20200218
new  CMIP6.CMIP.NCC.NorESM2-MM.historical.r3i1p1f1.AERmon.o3.gn.v20200702
new  CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp245.r2i1p1f1.Amon.o3.gn.v20200702
new  CMIP6.RFMIP.NCC.NorESM2-MM.piClim-control.r1i1p1f1.Amon.o3.gn.v20200206
new  CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp245.r2i1p1f1.AERmon.o3.gn.v20200702
new  CMIP6.RFMIP.NCC.NorESM2-MM.piClim-aer.r1i1p1f1.Amon.o3.gn.v20200206
```

<img width="1153" alt="Screenshot 2021-08-04 at 12 12 06" src="https://user-images.githubusercontent.com/1725351/128164579-5b348942-c057-439b-b734-9b55d2e5eb62.png">

**Comment by oyvindseland** [comment]
Perhaps it was a question of noresg being down. (At least it was down on last Friday) and for some reason I was not able to find it among the replicas.
Minor point. I do not understand why the value is sometimes defined as Amon and sometimes as AERmon but as long as one searches for o3 that should not matter
I will reply to the original e-mail and then the issue can be closed. Thank you for the help
