### ISSUE TITLE
Add "CMIP6_Amon" and "CMIP6_6hrPlevPt" table

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#307]
Fields in  6hr-instantaneous output (cam.h3)
```
'snowmxrat      ','QSNOW

Fields in monthly mean files (cam.h0)
'snowmxrat      ','AQSNOW
...

**Comment by oyvindseland** [comment]
Added in the table. Note the monthly averaged and instantaneous fields are not defined identically.

**Comment by YanchunHe** [comment]
reopened the above-mentioned issues. And close this issue now, and will update these  issues  in the future.
