### ISSUE TITLE
Should / does C4MIP results deviate from general DECK and scenario simulations?

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#313]
Professor Justin Mankin and Harmanveer Singh, Climate Modeling and Impacts Group at Dartmouth College in the United States are working are hoping to use the pertinent variables for their analysis from the NorESM2-LM model. As part of this work they noticed that the precipitation datasets on the ESGF archive for the C4MIP 1pctCO2-rad and 1pctCO2-bgc experiments are the same. Given that we have included the CO2 cycle in our standard simulations except for the feedback to atmospheric CO2, should the field be identical? Likewise for general DECK and scenario experiments.

**Comment by tjiputra** [comment]
Hi @oyvindseland, no the physic outputs in 1pctCO2-rad and 1pctCO2-bgc should differ. I suspect this is related to the wrong processing of 1pctCO2-bgc outputs in the first ESGF submission (@YanchunHe has used the wrong experiment: 1pctCO2-rad). I just sent an e-mail to Yanchun than he has also updated the physical fields in late 2020. I can replay to Harmanveer when I got the confirmation from Yanchun.

**Comment by oyvindseland** [comment]
Thank you for the information. Good that you follow it up further. I have
sent the github issue link as a reply to the original e-mail



tir. 22. feb. 2022 kl. 11:11 skrev tjiputra ***@***.***>:

**Comment by oyvindseland** [comment]
@tjiputra Note that the question is also about the scenario and DECK experiments

**Comment by YanchunHe** [comment]
Hi,

I see the 1pctCO2-bgc was reprocessed and republished.

[https://github.com/NorESMhub/noresm2cmor/issues/173](https://github.com/NorESMhub/noresm2cmor/issues/173)
[https://github.com/NorESMhub/noresm2cmor/issues/235](https://github.com/NorESMhub/noresm2cmor/issues/235)

There are daily precipitation that appear for both experiments:
/projects/NS9034K/CMIP6/C4MIP/NCC/NorESM2-LM/1pctCO2-bgc/r1i1p1f1/day/pr/gn/v20201001
/projects/NS9034K/CMIP6/C4MIP/NCC/NorESM2-LM/1pctCO2-rad/r1i1p1f1/day/pr/gn/v20200206

I have a quick look at the average of all the data of each experiment, and the there are sensible difference between them.

Probably, they download the old data version? Please use the above-mentiond data version (v20200206 for 1pctCO2-rad, and v20201001 for 1pctCO2-bgc).

For data publish and Errata issues, please contact @monsieuralok .

![figure_pr](https://user-images.githubusercontent.com/1725351/155113388-402909cf-df12-4c2b-aaf0-0cafecf95979.png)

**Comment by YanchunHe** [comment]
quote

> Yes, I was able to locate the correct versions of the datasets on the ESGF data archive. Thank you for your help with this.
>  
> Regards,
> Harmanveer (Harry) Singh
