### ISSUE TITLE
Possible wrong height coordinate in the cmorized cloud data

### ISSUE THREAD

**Issue by adagj** [NorESMhub/noresm2cmor#314]
Hi @YanchunHe , @lisesg 

**Describe the error**
For the Amon variables, there seem to be a mix of interpolated and nativ grid variables. E.g ta, hus, hur, ta, ua and uv are interpolated to pressure levels (plev). The cloud variables, cl, cli, clw +++ are on sigma levels (lev). I had the impression that all Amon variables should be on the same (plev) grid, but maybe I'm wrong... 

Best,
Ada

**Comment by YanchunHe** [comment]
Hi Ada,

The vertical coordinates for different variables are clearly stated in the 'table' file, for example:

https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_Amon.json
```json
       "ta": {
            "dimensions": "longitude latitude plev19 time", 
```

```json
        "clw": {

            "dimensions": "longitude latitude alevel time", 
```

And the vertical coordinates are described in:
https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_coordinate.json


So I think all these are correct.

Yanchun

**Comment by adagj** [comment]
Yes, you are right. But I find it a bit strange that it is such a mix of interpolated and native grid output under Amon. But nothing you need to bother about :-) 

Cheers,
Ada
