### ISSUE TITLE
[ERROR] in the co2 cmorized data

### ISSUE THREAD

**Issue by adagj** [NorESMhub/noresm2cmor#315]
Hi,
after a disussion with @DirkOlivie and @tjiputra, we wonder if the cmorized varible co2 should be retracted fro the non-esm simulations.

**Describe the error**
For piControl co2 is ~430.9*1e-6 mol/mol (/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl/r1i1p1f1/AERmon/co2/gn/latest/). Should be ~282e-6mol/mol
The numbers are almost the same for the abrupt-4xCO2 simulation (/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/abrupt-4xCO2/r1i1p1f1/AERmon/co2/gn/latest/ on NIRD). We know that the piControl simulation and the 4xCO2 simulation have different co2 concentration, so that can't be correct. 

For the PAMIP simulations forced by year 2000 emissions and GHG forcing (e.g. /projects/NS9034K/CMIP6/PAMIP/NCC/NorESM2-LM/pa-pdSIC-ext/r1i1p1f1/AERmon/co2/gn/latest/ on NIRD), the co2 is 282.5e-6 mol/mol in the cmorized output. It should be at year 2000 level so more like ~370e-6 mol/mol.

Too me it seems like the CO2 variable in NorESM raw data **always** has values around 430 kg/kg so it is probably not really used, and then we should probably not cmorize it.

**Way to correct**
(i) For the simulations with interactive carbon cycle (esm simulations), the cmorized fields are correct and make sense.

(ii) For the simulations without interactive carbon cycle but still coupled to the ocean, the cmorized fields are not useful (and should possibly not be cmorized).

(iii) It looks to me the conversion from [kg/kg] to [mol/mol] in: 
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl/r1i1p1f1/AERmon/co2/gn/latest/
 (as well as abrupt-4xCO2 and probably other simulations) was not done correctly.

**Comment by YanchunHe** [comment]
We have discussed this before, refer to https://github.com/NorESMhub/noresm2cmor/issues/181

The unit conversion is done by a factor of 1e6*29./(12.+2.*16.). from kg/kg to mol/mol.

If the co2 in some of the experiments should be retracted, please list those experiments and tables, so that Alok can retract them.

**Comment by oyvindseland** [comment]
I think the title of this issue is somewhat misleading. The number is correct for PI conditions but the number is not connected to the CO2 value that is actually used for the model in a non-carbon cycle setting. As it is more confusing than describing the question is if that variable can be retracted for all non-concentration driven simulations. Jerry can likely provide a list of simulations that should retain the value. If retracting the field is to much work, an errata should probably be published

**Comment by monsieuralok** [comment]
@YanchunHe what should be done regarding this issue? and which datasets/variables/experiments  are affected?

**Comment by YanchunHe** [comment]
Hi Ada and Øyvind,

@adagj @oyvindseland ?

Could any of you indicate in more details what to proceed by Alok? 

Could you list the all the datasets (experiments, etc) that should be reported with Erratum and/or retracted?

Thanks!

**Comment by YanchunHe** [comment]
Could anyone make a summary how to proceed?

**Comment by oyvindseland** [comment]
Hi I think the best way forward is to retract the variable from all non-CO2 prognostic simulations  @tjiputra for list of CO2 prognostic, with the explanation in errata that the cmorized value is not the value used for the simulations.

**Comment by monsieuralok** [comment]
@YanchunHe Please could you put list here for all variables and frequency .

**Comment by monsieuralok** [comment]
@YanchunHe please could you look at this issue what needs to be done?

**Comment by JorgSchwinger** [comment]
> * esm-hist
> 
> * esm-pi-CO2pulse
> 
> * esm-pi-cdr-pulse
> 
> * esm-ssp585

These are emission driven simulations, for these the co2 variable should be okay and shouldn't be retracted??? @tjiputra?

**Comment by tjiputra** [comment]
@JorgSchwinger, @YanchunHe, @monsieuralok,
yes, this is what i told Yanchun today. Probably just a typo.

**Comment by YanchunHe** [comment]
> @JorgSchwinger, @YanchunHe, @monsieuralok,
> yes, this is what i told Yanchun today. Probably just a typo.

Oh, yes, sorry that I made a mistake forgetting to remove these esm-* from the list. I have corrected from the above list.

@monsieuralok the above list is now the correct one.

**Comment by monsieuralok** [comment]
@YanchunHe if I am correct in NorESM2-MM piControl should also be there ? Should be remove for all version or did we published any corrected version or planning to publish as will open an errata issue?

**Comment by YanchunHe** [comment]
> @YanchunHe if I am correct in NorESM2-MM piControl should also be there ? Should be remove for all version or did we published any corrected version or planning to publish as will open an errata issue? Example data version 20230616 is having correct datasets or not?

Yes, even if they are version v20230616, the `co2` should be extracted, except for those experiments started with `esm-*`.

I have a look, and there are following experiments with v20230616 that need to be retracted (plus those earlier version as show above):
* ssp245
* historical
* piControl
* amip
* amip-p4K
* 1pctCO2

While the following with can be kept:
* esm-ssp534-over
* esm-hist

Thanks!

**Comment by oyvindseland** [comment]
Just to make sure. You can retract one dataset without changing the rest of the datasets? I presume that if you want to republish one dataset you need to republish the whole set, but given the instability of the server I hope that republishing of all major datasets can be avoided.

**Comment by monsieuralok** [comment]
@oyvindseland yes only co2 datasets will be retracted; not the whole experiments
@YanchunHe Here is errata issue:- https://errata.es-doc.org/static/view.html?uid=2dc98710-b977-ff15-8602-828bd7f8d844

**Comment by YanchunHe** [comment]
Thanks @monsieuralok 

According to @tjiputra, the CO2 concentration used in the concentration-driven experiments are provided as below:

[Atmospheric_CO2_SSP585.csv](https://github.com/NorESMhub/noresm2cmor/files/13264823/Atmospheric_CO2_SSP585.csv)
[Atmospheric_CO2_SSP370.csv](https://github.com/NorESMhub/noresm2cmor/files/13264824/Atmospheric_CO2_SSP370.csv)
[Atmospheric_CO2_SSP245.csv](https://github.com/NorESMhub/noresm2cmor/files/13264825/Atmospheric_CO2_SSP245.csv)
[Atmospheric_CO2_SSP126.csv](https://github.com/NorESMhub/noresm2cmor/files/13264826/Atmospheric_CO2_SSP126.csv)
[Atmospheric_CO2_hist.csv](https://github.com/NorESMhub/noresm2cmor/files/13264827/Atmospheric_CO2_hist.csv)
