### ISSUE TITLE
[ERROR] in wap ssp585

### ISSUE THREAD

**Issue by YanchunHe** [NorESMhub/noresm2cmor#316]
**Describe the error**
Quote from Birthe
> the wap is given on 4 Plevels, but all the values in the vertical are equal.

**Way to correct**
> Is it possible to get wap data for this scenario that is more reasonable?
If not,, is there any reasonable wap fields for another model simulation on 6 hour time resolution?

**Comment by YanchunHe** [comment]
I can't track where is the cause of the problem now. but I redo the cmorization and it seems OK.

The fixed dataset is here:
/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrPlev/wap/gn/v20220505

I also noticed that all (just check randomly) the 3D 6hrPlev data are wrong with identicial data on plevs.

This should apply for the experiments with 6hrPlev dataset available, including:

NorESM2-LM:
* [1pctCO2](#128 )
* abrupt-4xCO2
* amip
* esm-ssp585
* historical
* piControl
* ssp126
* ssp245
* ssp370
* ssp585

**Comment by monsieuralok** [comment]
@YanchunHe I have published errata issue on that : -https://errata.es-doc.org/static/view.html?uid=590fbf04-3fca-8d3d-a286-d7876f4b2970 datasets are not removed yet as again I am having problem with ESGF node.

**Comment by monsieuralok** [comment]
@YanchunHe retracted

**Comment by YanchunHe** [comment]
Thanks, @monsieuralok !

I keep this open, since the new data has not been generated and republished yet, so it is not closed.

**Comment by oyvindseland** [comment]
Why do you want to calculate additional fields than we have published though. The 3 3D 6 hour average fields we have output Q,Omega and cloud volume do vary with height in the output (checked 3 random files) 
Any additional fields should be calculated by the user I think

**Comment by YanchunHe** [comment]
The 3D 6 hourly output, Q, Omega are all right in the original output on sigma levels, but the CMIP6 requires them on interpolated 4 Plevs, corresponding to 'hus' and 'wap'. To calculate the latter with Q and Omega on original sigma levels, we need PS data, which is missing.

Only 'hus' is published on simga levels, 'wap' is not required and thus not cmorized and published.

Fine of me if you don't think it is necessary to calculate these additional fields.

Then please close this issue.

**Comment by YanchunHe** [comment]
OK, according to the discussion. I close this issue now. reopen when needed.
