### ISSUE TITLE
[BUG] different longitude vertices values for same model resolution SImon output

### ISSUE THREAD

**Issue by adagj** [NorESMhub/noresm2cmor#318]
**Describe the bug**
There seems to be different values for vertices_longitude in e.g siconc (SImon variable) for ssp585 and historical 
This is problematic for e.g. regridding and right now I'm not sure which one to use

**To Reproduce**
ncdump -v vertices_longitude /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r1i1p1f1/SImon/siconc/gn/latest/siconc_SImon_NorESM2-LM_historical_r1i1p1f1_gn_200001-200912.nc

and compare to 

ncdump -v vertices_longitude /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp585/r1i1p1f1/SImon/siconc/gn/latest/siconc_SImon_NorESM2-LM_ssp585_r1i1p1f1_gn_201501-202012.nc

**Comment by YanchunHe** [comment]
Hi @adagj 

Do we need to redo cmorization for some varialbes, or this is not critical so that we leave it as it is?
