### ISSUE TITLE
[ERROR] in the fLuc and fHarvest data

### ISSUE THREAD

**Issue by kjetilaas** [NorESMhub/noresm2cmor#319]
Hi,

There is an error with the published fLUC (Net Carbon Mass Flux into Atmosphere Due to Land-Use Change), as discussed in this issue:
https://github.com/NorESMhub/NorESM/issues/366 

**Describe the error**
The fLUC variable seems to have been based on the CLM variable "land_use_flux", which includes C emissions from land conversion pluss fluxes from wood and grain products. The C flux from grain products should not be included. 

**Way to correct**
fLUC needs to be CMORized again using (to my understanding) 'DWT_CONV_CFLUX' + 'TOT_WOODPRODC_LOSS' (which is equivalent to subtracting crop loss 'CROPPROD1C_LOSS' from the existing fLUC).

**Comment by kjetilaas** [comment]
Following up on this, I think fHarvest (Carbon Mass Flux into Atmosphere Due to Crop Harvesting) is also incorrect, as this seems to be based on "WOOD_HARVESTC" (wood harvest carbon flux).

**Comment by kjetilaas** [comment]
Here is the list of datasets that I believe is affected, @monsieuralok and @YanchunHe:

fLuc (should be calculated as DWT_CONV_CFLUX+TOT_WOODPRODC_LOSS):
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/1pctCO2/r1i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/abrupt-4xCO2/r1i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip/r1i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip/r1i1p2f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/esm-hist/r1i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/esm-piControl/r1i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r1i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r2i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r3i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl/r1i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/1pctCO2/r1i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/abrupt-4xCO2/r1i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/amip/r1i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/r1i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/r2i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/r3i1p1f1/Emon/fLuc
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/piControl/r1i1p1f1/Emon/fLuc

fHarvest (should be "CROPPROD1C_LOSS"):
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/1pctCO2/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/abrupt-4xCO2/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r10i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r11i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r12i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r13i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r14i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r15i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r16i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r17i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r18i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r19i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r20i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r21i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r22i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r23i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r24i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r25i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r26i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r27i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r28i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r29i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r2i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r30i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r3i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r4i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r5i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r6i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r7i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r8i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical-ext/r9i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r10i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r11i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r12i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r13i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r14i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r15i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r16i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r17i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r18i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r19i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r20i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r21i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r22i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r23i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r24i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r25i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r26i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r27i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r28i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r29i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r2i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r30i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r3i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r4i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r5i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r6i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r7i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r8i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/historical/r9i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/piControl/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/piControl/r2i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorCPM1/piControl/r3i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/1pctCO2/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/abrupt-4xCO2/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip/r1i1p2f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/esm-hist/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/esm-piControl/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r2i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r3i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/1pctCO2/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/abrupt-4xCO2/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/amip/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/r1i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/r2i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/historical/r3i1p1f1/Lmon/fHarvest
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-MM/piControl/r1i1p1f1/Lmon/fHarvest

**Comment by kjetilaas** [comment]
fLuc seems to be correct for NorCPM1 (probably because it doesn't include crops). For the same reason, fHarvest should maybe just be retracted rather than recmorized for NorCPM1. Maybe @blcc or @counillf could confirm this?

**Comment by kjetilaas** [comment]
fLuc seems to be correct for NorCPM1 (probably because it doesn't include crops). For the same reason, fHarvest should maybe just be retracted rather than recmorized for NorCPM1. Maybe @blcc or @counillf could confirm this?

**Comment by kjetilaas** [comment]
fLuc seems to be correct for NorCPM1 (probably because it doesn't include crops). For the same reason, fHarvest (Carbon Mass Flux into Atmosphere due to Crop Harvesting) should probably just be retracted rather than re-cmorized for NorCPM1. Maybe @blcc or @counillf could confirm this?

**Comment by monsieuralok** [comment]
@kjetilaas There are 2757 datasets related to fHarvest and fLuc involving ALL experiments in NorESM2-LM and NorESM2-MM. Do we need to retract all datasets or republish ?

**Comment by monsieuralok** [comment]
@kjetilaas please could you confirm that we need to retract all datasets related to fHarvest and fLuc and republish which are around 2757 involving ALL experiments  in NorESM2-LM and NorESM2-MM.

**Comment by monsieuralok** [comment]
@kjetilaas @YanchunHe Opened an errata issue: https://errata.es-doc.org/static/view.html?uid=ecfe4e31-e619-447e-a46b-d3d74baa64cf

**Comment by YanchunHe** [comment]
Hi @monsieuralok 

I think you should retract all the datasets of both `fLuc` and `fHarvest`.

I will then redo cmorization and republish.

**Comment by YanchunHe** [comment]
Hi @monsieuralok 

Have you retracted the data?

**Comment by YanchunHe** [comment]
> 

So what the correct form of the `fHarvest`?

**Comment by kjetilaas** [comment]
Hi @YanchunHe

fHarvest should use "CROPPROD1C_LOSS".

**Comment by YanchunHe** [comment]
> 

Thanks 👍

**Comment by monsieuralok** [comment]
@YanchunHe retracted
