### ISSUE TITLE
[ERROR] missing values in 6hrLev historical r2i1p1f1 NorESM2-MM files for ua, va, and ta

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#322]
**Describe the error**
Some of the cmorized files from the r2i1p1f1 historical simulation (member 2) from NorESM2-MM contain only missing data.  This is the case for the 6hrLev data for the following variables and periods:
ua: period 1950-1960, 1960-1970, and 2000-2010
va : period 1990-2000
ta : period 1960-1970, 1970-1980,1990-2000
These data are used by researchers at MISU (Stockholm University).

**Way to correct**
As the original output from NorESM2-MM seems to be ok (cam.h3 files all have similar sizes), I presume the error has been introduced during the cmorization process.  Therefore I suggest to run the cmorization again.

**Comment by YanchunHe** [comment]
The corrected data from 1950 to 2014 have been cmorized and stored under:
NIRD: /projects/NS9034K/CMIP6/.cmorout/NorESM2-MM/historical/v20221027

As the ESGF is still down, it is not ready to be published to ESGF now.

The corrected data will be shared with the users at MISU through private communication. 

Updates will be posted here  in the future.

**Comment by YanchunHe** [comment]
published, and close the issue now.
