### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-MM -ssp585 extension

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#326]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**

/projects/NS2345K/noresm/cases/NSSP58frc2ext_f09_tn14_20220309

**experiment_id**

  ssp585

**model_id**

NorESM2-MM

**CASENAME(s) and years to be CMORized**

NSSP58frc2ext_f09_tn14_20220309 (2101-2298)

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
 
ssp585

**parent_experiment_rip**
 r1i1p1

**parent_time_units**

**branch_method**

**other information**
Extension of /projects/NS9560K/noresm/cases/NSSP585frc2_f09_tn14_20191105

In cmip5 the scenario extensions beyond 2100 had a separate experiment_id than until 2100. I can not find that this is the case for CMIP6 so the cmorized data should probably be appended to the existing experiment

**Comment by YanchunHe** [comment]
Hi @oyvindseland 

To extend the existing experiment (published data on ESGF), we need firstly retract all published data, and then republish them again with the extended period.

@monsieuralok Could you retract all NorESM2-MM SSP585 r1i1p1f1 datasets?

**Comment by YanchunHe** [comment]
CMORized and ready to be published, together with the years from 2015-2100.

See the full status in issue #151
