### ISSUE TITLE
Add new physics category for publishing new simulations (p4)

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#336]
Hi

I am planning to publish a project intercomparison with CMIP6 forcings but different physics using NorESM2-LM. Suggested experiment id convention already started by EC-Earth is to use "p4" in the label e.g. the historical simulation is to be given variant_label=r1i1p4f1
It will be on the order of 10 experiments with a mix of coupled and atmosphere/land only experiments. The expected (and mostly finished) coupled simulations are piControl, historical, 1 pct CO2 and SSP245. 
There will be one or two historical with prescribed SST and a number of 30 year long AMIP simulations.

Is the naming convention easily included in noresm2cmor?
Since it is a project with no participation from Bergen should / must I organize the cmorization and / or publication myself?

@YanchunHe @lisesg

**Comment by YanchunHe** [comment]
Yes, `r1i1p4f1` is easily given. 

However, please note, `r1i1p4f1` is `realisation` (or variant_label, or ensemble), not `experiment_id`. The `experiment_id` should exactly be the same as already defined, e.g., `historical` or `1pctCO2`.

Therefore, in summary, we can say,  `experiment_id` =  historical, `variant_label`=r1i1p4f1 will work.

**Comment by YanchunHe** [comment]
Please submit cmorize request issues. One issue for one experiment, but can have several experiment with different `variant_label`.

**Comment by oyvindseland** [comment]
Will add experiment_rip in the cmorisation request. typically as above, r1i1p4f1

**Comment by oyvindseland** [comment]
Based in the discussions here I am creating individual cmorization and publications requests. Closing this issue
