### ISSUE TITLE
[CMORization request] NorESM2-LM, new physics and tuning settings, piControl 

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#337]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS2345K/oyvinds/cases/N1850_f19_tn14_Forces_230512

**experiment_id**
piControl

**model_id**

NorESM2-LM

**CASENAME(s) and years to be CMORized**
e.g., 
N1850_f19_tn14_Forces_230512, 1601-1901

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorwegianClimateCentre/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1

**parent_time_units**

**branch_method**
'Hybrid-restart from year 1601-01-01 of piControl',

**other information**

experiment_rip
r1i1p4f1

**Comment by YanchunHe** [comment]
The exp. is cmorized and ready to be published to ESGF.

## data path
* /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piControl
* /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl

## version
* v20230616

## sha256sum
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/piControl
* .r1i1p1f1.sha256sum_v20230616

**Comment by YanchunHe** [comment]
The historical `r1i1p4f1` is cmorized and ready to be published to ESGF.

## data path
* /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical
* /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical

## version
* v20230616

## sha256sum
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical
* .r1i1p4f1.sha256sum_v20230616

**Comment by monsieuralok** [comment]
@YanchunHe published
