### ISSUE TITLE
[CMORization request] NorESM2-LM new physics, historical

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#338]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS2345K/oyvinds/cases/NHIST_f19_tn14_Forces_230515

**experiment_id**
 historical

**model_id**

NorESM2-LM

**CASENAME(s) and years to be CMORized**
 
NHIST_f19_tn14_Forces_230515 1850-2014

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorwegianClimateCentre/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
 
piControl

**parent_experiment_rip**
 r1i1p1

**branch_method**

<strike> 'Hybrid-restart from year 1601-01-01 of piControl', </strike>

'Hybrid-restart from year 1600-01-01 of piControl',

**other information**
(provide other information that might be useful)
e.g., realisation, initialisation, etc...
and the cases name and path to the parent experiment, etc

experiment_rip
r1i1p4f1

parent case path
/projects/NS9560K/noresm/cases/N1850_f19_tn14_20190621

case
N1850_f19_tn14_20190621

**Comment by YanchunHe** [comment]
NorESM2-LM is branched from 1600-01-01, see issue #133 

@oyvindseland Could you check if the branch time is correct as above formulated?

**Comment by YanchunHe** [comment]
So the physics=4 case here is branched from 1601-01-01, instead of 1600-01-01?

**Comment by oyvindseland** [comment]
Yes.

I mad a mistake in using 1601 although a 1 year change is going to change any conclusions

**Comment by YanchunHe** [comment]
> 

Yes, for sure. Only to make sure to avoid introduce any unnecessary confusion.

(I made update at the top).

**Comment by oyvindseland** [comment]
The correct date is 1601 though. It might have been better to use 1600 but there it is.

**Comment by YanchunHe** [comment]
> The correct date is 1601 though. It might have been better to use 1600 but there it is.

OK. I misundstood it. I thought it is just a typo in this issue.

I have done some cmorisation for this experiment, but I will do it again with setting the branch date as 1601-01-01.

Thanks for the explanation!

**Comment by monsieuralok** [comment]
@YanchunHe published
