### ISSUE TITLE
[CMOR-ization & ESGF-publication] NorESM2-LM new physics, 1pctCO2

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#341]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS2345K/oyvinds/cases/N1PCT_f19_tn14_Forces_230515

**experiment_id**
1pctCO2

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
e.g., 
N1PCT_f19_tn14_Forces_230515, year 1-140

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id** 
piControl

**parent_experiment_rip**
e.g., r1i1p1

**branch_method**
'Hybrid-restart from year 1601-01-01 of piControl',

**other information**
(provide other information that might be useful)

experiment_rip
r1i1p4f1

parent case path
/projects/NS9560K/noresm/cases/N1850_f19_tn14_20190621

case
N1850_f19_tn14_20190621

**Comment by YanchunHe** [comment]
CMORized 1pctCO2 with new physics:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/1pctCO2
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/1pctCO2

**version**
- v20230616

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/1pctCO2
- .r1i1p4f1.sha256sum_v20230616

**Comment by monsieuralok** [comment]
@YanchunHe @oyvindseland recently, we noticed problem on ESGF node so, Thierry has wrote to Prashant. While data publication was successful but ,still data did not appeared on liu-cmip6 node. But, data were visible on noresg node. So, we have to wait a bit before problem is resolved.  It happened with ALL data recently published.

**Comment by monsieuralok** [comment]
@YanchunHe published
