### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM new physics, amip

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#342]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS2345K/oyvinds/cases

**experiment_id**
amip

**model_id**

NorESM2-LM

**CASENAME(s) and years to be CMORized**

NFHISTnorpddmsbc_f19_f19_Forces_230607, 1975-2014
NFSSP245norpddmsbc_f19_mg17_Forces_230623, 2015-2020
### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
historical

**parent_experiment_rip**
r1i1p4f1

**branch_method**
'Hybrid-restart from year 1975-01-01 of historical ',

**other information**

experiment_rip
r1i1p4f1

parent case path
/projects/NS2345K/oyvinds/cases

case
NHIST_f19_tn14_Forces_230515

**Comment by YanchunHe** [comment]
CMORized and ready to be published:

**data path**

- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/amip
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip

**version**

- v20230616

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip
- .r1i1p4f1.sha256sum_v20230616

**Comment by monsieuralok** [comment]
@YanchunHe published
