### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM new physics, amip-p4K

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#343]
Mandatory information:

Full path to the case(s) of the experiment on NIRD
/projects/NS2345K/oyvinds/cases

experiment_id
amip-p4K

model_id

NorESM2-LM

CASENAME(s) and years to be CMORized

NFHISTp4Knorpddmsbc_f19_f19_Forces_230607, 1975-2014
NFSSPp4K245norpddmsbc_f19_mg17_Forces_230623, 2015-2020

Optional information

parent_experiment_id
historical

parent_experiment_rip
r1i1p4f1

branch_method
'Hybrid-restart from year 1975-01-01 of historical ',

other information

experiment_rip
r1i1p4f1

parent case path
/projects/NS2345K/oyvinds/cases

case
NHIST_f19_tn14_Forces_230515

**Comment by YanchunHe** [comment]
Seems that 'NFSSPp4K245norpddmsbc_f19_mg17_Forces_230623' does not exist in the directory specified above.

Could you please check that? @oyvindseland

**Comment by oyvindseland** [comment]
Sorry. Typo in name
Edited in the correct name

**Comment by YanchunHe** [comment]
> 

OK, then I think you meant: NFSSP245p4Knorpddmsbc_f19_mg17_Forces_230623

**Comment by oyvindseland** [comment]
yes


man. 4. sep. 2023 kl. 13:31 skrev Yanchun He ***@***.***>:

**Comment by YanchunHe** [comment]
cmorized and ready to be published:

CMORized and ready to be published:

**data path**

- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/amip-p4K
- /projects/NS9034K/CMIP6/CFMIP/NCC/NorESM2-LM/amip-p4K

**version**

- v20230616

**sha256sum**
/projects/NS9034K/CMIP6/CFMIP/NCC/NorESM2-LM/amip-p4K
- .r1i1p4f1.sha256sum_v20230616
-

**Comment by monsieuralok** [comment]
@YanchunHe published
