### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM new physics, ssp245

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#344]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS2345K/oyvinds/cases

**experiment_id**
ssp245

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**

NSSP245_f19_tn14_Forces_230609, 2015-2100

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

parent_experiment_id
historical

parent_experiment_rip
r1i1p4f1

branch_method
'Hybrid-restart from year 2015-01-01 of historical ',

**other information**
(provide other information that might be useful)
e.g., realisation, initialisation, etc...
and the cases name and path to the parent experiment, etc

experiment_rip
r1i1p4f1

parent case path
/projects/NS2345K/oyvinds/cases

case
NHIST_f19_tn14_Forces_230515

**Comment by YanchunHe** [comment]
Just an update:

There is problem cmorizing data between 2060-2069.

Have tried several times, but have not figured out why, but seems some low-level library problem.

```
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
--------------------------------------------------------------------------
mpirun has exited due to process rank 5 with PID 0 on
node ipcc exiting improperly. There are three reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

3. this process called "MPI_Abort" or "orte_abort" and the mca parameter
orte_create_session_dirs is set to false. In this case, the run-time cannot
detect that the abort call was an abnormal termination. Hence, the only
error message you will receive is this one.

This may have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).

You can avoid this message by specifying -quiet on the mpirun command line.
--------------------------------------------------------------------------
```

Will need some more time to figure out the solution.

**Comment by YanchunHe** [comment]
> Do you find the same problem for later periods or have you not tested?

The late periods are totally OK, and have been successfully cmorized.

**Comment by YanchunHe** [comment]
> Should I re-run the period in case there was something with the archiving?

Yes, I would prefer to do so, as this seems to be problem with certain file(s).

**Comment by oyvindseland** [comment]
I have restarted the simulation today from 2060 and confirmed that it at least by month 3 is bit-identical to the existing. I have set the run to end in 2069. The simulation should be finished by tomorrow afternoon.  I do not know if rsync recognizes that the files are new or if I need to manually delete the old ones on nird before I copy the files.

**Comment by YanchunHe** [comment]
> I have restarted the simulation today from 2060 and confirmed that it at least by month 3 is bit-identical to the existing. I have set the run to end in 2069. The simulation should be finished by tomorrow afternoon. I do not know if rsync recognizes that the files are new or if I need to manually delete the old ones on nird before I copy the files.

Thanks. Rsync do recognise new files.

However, I would suggest give a slightly different casename, or put the case to another folder/subfolder if the case has the same name as the full one.

Then I will just redo the cmorization for only the 10 years part.

**Comment by oyvindseland** [comment]
Had already restarted the simulation with the same name but I have put the period in a separate directory
/projects/NS2345K/oyvinds/correctedcases/NSSP245_f19_tn14_Forces_230609

**Comment by YanchunHe** [comment]
cmorized and ready to be published.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp245/v20230616
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp245

**version**
- v20230616

**sha256sum**
/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/ssp245
- .r1i1p4f1.sha256sum_v20230616

**Comment by monsieuralok** [comment]
@YanchunHe published
