### ISSUE TITLE
CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM new physics piClim-aer

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#355]
**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/oyvinds/cases

**experiment_id**
<strike>piClim-control </strike>
piClim-aer

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
F1850norbc_aer2014_f19_f19_Forces_fsst_20231130, years 1-30

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
piControl 

**parent_experiment_rip**
r1i1p4f1

**branch_method**
'Hybrid-restart from year 1741-01-01 of piControl',

**other information**

experiment_rip
r1i1p4f1

parent case path
/projects/NS2345K/oyvinds/cases

case
N1850_f19_tn14_Forces_230512

Physics information
Alternative / updated model version based on CMIP6 but updated with parameterisations from projects  NFR-KeyClim and H2020-Forces

**Comment by YanchunHe** [comment]
@oyvindseland `/projects/NS9560K/oyvinds/cases/F1850norbc_aer2014_f19_f19_Forces_fsst_20231130` does not exist, please check.

**Comment by oyvindseland** [comment]
Corrected the case name in the original issue post.

**Comment by YanchunHe** [comment]
> Corrected the case name in the original issue post.

Sorry, but I don't see the correction?

**Comment by oyvindseland** [comment]
Full path to the case(s) of the experiment on NIRD
/projects/NS9560K/oyvinds/cases

experiment_id
piClim-control
piClim-aer

model_id
NorESM2-LM

CASENAME(s) and years to be CMORized
NF1850norbc_aer2014_f19_f19_Forces_fsst_20231130, years 1-30
Optional information

(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

parent_experiment_id
piControl

parent_experiment_rip
r1i1p4f1

branch_method
'Hybrid-restart from year 1741-01-01 of piControl',

other information

experiment_rip
r1i1p4f1

parent case path
/projects/NS2345K/oyvinds/cases

case
N1850_f19_tn14_Forces_230512

Physics information
Alternative / updated model version based on CMIP6 but updated with parameterisations from projects NFR-KeyClim and H2020-Forces

**Comment by oyvindseland** [comment]
I though I had edited it, but it did not work.

Copied and sent in the whole list over again. The compset should start with NF not F. Corrected in the new list

**Comment by YanchunHe** [comment]
> I though I had edited it, but it did not work.
> 
> Copied and sent in the whole list over again. The compset should start with NF not F. Corrected in the new list

Thanks. It is working now.

**Comment by YanchunHe** [comment]
Cmorized and  is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-aer
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-aer

**version**
- v20230616

**sha256sum**
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-aer
- .r1i1p4f1.sha256sum_v20230616

**Comment by monsieuralok** [comment]
@YanchunHe published
