### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM new physics histSST-piAer

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#357]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/oyvinds/cases

**experiment_id**
histSST-piAer

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NFHISTnorbc_piaer_f19_Forces_230706, years 1850-2014

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
piControl 

**parent_experiment_rip**
r1i1p4f1

**branch_method**
'Hybrid-restart from year 1601-01-01 of piControl',

**other information**

experiment_rip
r1i1p4f1

parent case path
/projects/NS2345K/oyvinds/cases

case
N1850_f19_tn14_Forces_230512

Physics information
Alternative / updated model version based on CMIP6 but updated with parameterisations from projects  NFR-KeyClim and H2020-Forces

**Comment by oyvindseland** [comment]
Hi Is it due to not being a CMIP6 experiment, i.e no resources for doing so or is it not due to this not being a CMIP6 type experiment. It is as far as I can see.

**Comment by YanchunHe** [comment]
> Hi Is it due to not being a CMIP6 experiment, i.e no resources for doing so or is it not due to this not being a CMIP6 type experiment. It is as far as I can see.

Yes, it is due to both, mainly for the former.

I have previously already setup a `noncmip` branch for this `noresm2cmor` tool, to handle these user customized 'non-cmip6' experiments. see https://github.com/NorESMhub/noresm2cmor/tree/noncmip

I have predefined some experiment recipes, for example, as 'generic' experiments, which can be used as a general experiment name. Please see the explanation and example in the [README](https://github.com/NorESMhub/noresm2cmor/blob/noncmip/README.md) file of this `noncmip` branch.

If one would like to use other customized experiment names, for example, 'histSST-piAer', one can add entries in the 'CMIP6_CV.json' file, which will be already copied to each case recipe folder as a start-up template.

I would like to keep this branch updated with some important updates in the main branch, and fix some issues, but I don't have additional in-kind time to do the actual cmorization for non-cmip6 experiments. Those should be contributed from specific projects.

**Comment by YanchunHe** [comment]
> > Hi Is it due to not being a CMIP6 experiment, i.e no resources for doing so or is it not due to this not being a CMIP6 type experiment. It is as far as I can see.
> 
> Yes, it is due to both, mainly for the former.
> 
> I have previously already setup a `noncmip` branch for this `noresm2cmor` tool, to handle these user customized 'non-cmip6' experiments. see https://github.com/NorESMhub/noresm2cmor/tree/noncmip
> 
> I have predefined some experiment recipes, for example, as 'generic' experiments, which can be used as a general experiment name. Please see the explanation and example in the [README](https://github.com/NorESMhub/noresm2cmor/blob/noncmip/README.md) file of this `noncmip` branch.
> 
> If one would like to use other customized experiment names, for example, 'histSST-piAer', one can add entries in the 'CMIP6_CV.json' file, which will be already copied to each case recipe folder as a start-up template.
> 
> I would like to keep this branch updated with some important updates in the main branch, and fix some issues, but I don't have additional in-kind time to do the actual cmorization for non-cmip6 experiments. Those should be contributed from specific projects.

And, btw, the noncmip experiment can not be published to ESGF, of course.

**Comment by oyvindseland** [comment]
OK 

I will try it and come back with questions and will at any rate need help with publishing for the CMIP6 type of experiments.
As yo may have seen I had split my issues into cmorize and publish for the CMIP6 type of experiments, and only cmorize for the non-cmip6 experiments.
The experiment here is a CMIP6 type of experiment though as found in
/projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/histSST-piAer

**Comment by YanchunHe** [comment]
> The experiment here is a CMIP6 type of experiment though as found in /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/histSST-piAer

Oh, yes, this is indeed CMIP6 experiment. I will process it, and Alok will publish it later.

**Comment by YanchunHe** [comment]
> OK
> 
> I will try it and come back with questions and will at any rate need help with publishing for the CMIP6 type of experiments. As yo may have seen I had split my issues into cmorize and publish for the CMIP6 type of experiments, and only cmorize for the non-cmip6 experiments. The experiment here is a CMIP6 type of experiment though as found in /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/histSST-piAer

But the other ssp245SST-* experiments are not CMIP6, right? But you have specified as 'publish' too. Please check.

**Comment by oyvindseland** [comment]
You are right. I thought it followed the same structure as ssp370, but they are not included in the CMIP6 list. I am sorry for the mistake.  I guess the conclusion should be that the other ssp245 can only stay as cmorize while histSST-piAer can be included as publish.
