### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - esm-ssp585-ocn-alk (ensemble members 2 and 3)

### ISSUE THREAD

**Issue by JorgSchwinger** [NorESMhub/noresm2cmor#365]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**

/projects/NS10054K/noresm/cases

I have added Yanchun to this project, so you should have access, let me know if not.

**experiment_id**

esm-ssp585-ocn-alk

**model_id**

NorESM2-LM

**CASENAME(s) and years to be CMORized**

NSSP585frc2esm_f19_tn14_OAn0p14_02_20231128, 2015-2100, to be cmorized as r2i1p1f1
NSSP585frc2esm_f19_tn14_OAn0p14_03_20231128, 2015-2100, to be cmorized as r3i1p1f1

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorESMhub/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**

esm-hist

**parent_experiment_rip**

NHIST_1901_f19_tn14_20230201esm: esm-hist, r2i1p1f1
NHIST_1951_f19_tn14_20230201esm: esm-hist, r3i1p1f1

**parent_time_units**

parent_time_units = "days since 1850-01-01 00:00:00"

**branch_method**
Hybrid-restart from year 2015-01-01 of esm-hist

**other information**

These are ensemble members 2 and 3 of the esm-ssp585-ocn-alk experiment. Ensemble member 1 is already cmorized. These member have reduced output volume to save disk space.

r2i1p1f1
r3i1p1f1

**Comment by YanchunHe** [comment]
@JorgSchwinger I will do the cmorization soon.

**Comment by YanchunHe** [comment]
Hi @monsieuralok, these two experiments have been cmorizedand, please publish them to ESGF. Thanks!

## data path
* /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/esm-ssp585-ocn-alk
* /projects/NS9034K/CMIP6/CDRMIP/NCC/NorESM2-LM/esm-ssp585-ocn-alk

## version
* v20230616

## sha256sum
/projects/NS9034K/CMIP6/CDRMIP/NCC/NorESM2-LM/esm-ssp585-ocn-alk
* .r2i1p1f1.sha256sum_v20230616
* .r3i1p1f1.sha256sum_v20230616

**Comment by monsieuralok** [comment]
@YanchunHe @JorgSchwinger should we remove all the variable related to co2mass from these experiements also as these are not published yet?

**Comment by JorgSchwinger** [comment]
Yes, I think it does not make sense to publish co2mass, since it will not be correct.

**Comment by monsieuralok** [comment]
@JorgSchwinger @YanchunHe experiments are published

**Comment by JorgSchwinger** [comment]
Great, thank you!
