### ISSUE TITLE
[ERROR] co2mass in emission driven runs 

### ISSUE THREAD

**Issue by adagj** [NorESMhub/noresm2cmor#366]
**Describe the error**
co2mass = co2vmr\*44/29\*totalmass

where totalmass is 5.1127790e+21 g (CAM total dry air mass) and co2vmr is the model mean "CO2 volume mixing ratio", which we interpret as a molar ratio mol CO2/mol dry air (only entirely correct for ideal gasses).

HOWEVER: It seems we didn't do this correctly, since **co2vmr doesn't hold the correct co2 mixing ratio in emission driven runs**

https://bb.cgd.ucar.edu/cesm/threads/bprp-case-failed-to-calculate-co2-concentration.6235/

**Way to correct**
There is no easy way to correct this, so we suggest to retract the co2mass variable for all emission-driven runs, and not generate new co2mass variables when running the cmorization.

We need to remeber this bug for CMIP7 and make sure to get it correct :)

**Comment by YanchunHe** [comment]
Hi @adagj, Thanks!

So no `co2mass` in the future for CMIP6 esm-* type experiments? I will try to keep in mind this.

So the list of experiments will be, with NorESM2-LM:
```
* esm-1pct-brch-1000PgC
* esm-pi-cdr-pulse
* esm-ssp245
* esm-ssp585-ocn-alk
* esm-hist
* esm-piControl
* esm-ssp534-over
* esm-ssp585-ssp126Lu
* esm-pi-CO2pulse
* esm-ssp119
* esm-ssp585
```

For the bug itself, maybe it should be recorded in the NorESM/CAM github issue.

@monsieuralok  could you please retract `co2mass` from above list of experiments?

**Comment by JorgSchwinger** [comment]
> So no `co2mass` in the future for CMIP6 esm-* type experiments? I will try to keep in mind this.

There is ways to compute the correct CO2 mass in emission driven runs, but this wouldn't use `co2vmr`, which is not used by the model in emission driven runs. The easiest way would be to use the CAM variable `TMCO2` (total CO2 column burden) and sum this up. Note that `TMCO2` in turn is incorrect in concentration driven simulations...

**Comment by monsieuralok** [comment]
@YanchunHe I have retracted but I have not found experiment:- esm-ssp245, esm-ssp119. 
Errata issue:- https://errata.ipsl.fr/static/view.html?uid=b93b2aff-ee8c-e0b6-b006-c226c26e2175
