### ISSUE TITLE
[CMIP6 CMORization & ESGF-publication] esm-hist NorESM2-LM

### ISSUE THREAD

**Issue by tjiputra** [NorESMhub/noresm2cmor#49]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases/NHIST_f19_tn14_20190909esm

**experiment_id**
esm-hist

**CASENAME(s) and years to be CMORized**
NHIST_f19_tn14_20190909esm, 1850-2014

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorwegianClimateCentre/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
esm-piControl

**parent_experiment_rip**
e.g., r1i1p1

**parent_time_units**
'days since 1851-01-01'

**branch_method**
'Hybrid-restart from year 1851-01-01 of esm-piControl',

**other information**
(provide other information that might be useful)
Prognostic atmospheric CO2 simulation

**Comment by YanchunHe** [comment]
CMORization is done;
Sent to the queue of publishing to ESGF
(Refer to Issue #52)

**Comment by IngoBethke** [comment]
Modified the issue to include ESGF-publication

**Comment by monsieuralok** [comment]
@YanchunHe Published

**Comment by YanchunHe** [comment]
CMORized with additional fields

**path**
- /tos-project1/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/esm-hist

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by YanchunHe** [comment]
(refer to @tjiputra )

some errors are found in the experiments.

stop publish this until the corrected data are cmorized.

**Comment by YanchunHe** [comment]
New issue #194 is created for the corrected experiment.
Close this issue.

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270 #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/esm-hist
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/esm-hist

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/esm-hist
- .r1i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published
