### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - amip

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#54]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases

**experiment_id**
amip

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NFHISTnorpddmsbc_f19_mg17_20190807, 1979-2014

### Optional information
hybrid from historical (NHIST_f19_tn14_20190710) on 1975-01-01

**parent_experiment_id**
no parent

**parent_experiment_rip**
no parent

**parent_time_units**

**branch_method**
Hybrid-restart from year 1975-01-01 of historical (NHIST_f19_tn14_20190710)

**other information**
The experiment has started in 1975-01-01, as there was no restart available from the historical in 1979-01-01.   I would suggest to cmorize and put on ESGF the period 1979-2014.

**Comment by YanchunHe** [comment]
CMORization finished;

**data path**
Raw output at:
`/projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/amip`
Linked to:
`/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip/r1i1p1f1`

**Version**
- v20190920

**other information**
- PrePARE quality-check, passed
- sha256sum, calculated

@DirkOlivie please have a look if the cmorized data look right. Then it is ready to publish to ESGF.

**Comment by monsieuralok** [comment]
Published

**Comment by YanchunHe** [comment]
Redo this CMORization with additionally supported fields.

**data path**
- /tos-project1/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@DirkOlivie @YanchunHe published

**Comment by YanchunHe** [comment]
A bug in some CFmon variables are found by Brian@ucar.

This is fixed in commit: #172 

affected variables: cltisccp and cllcalipso are fixed with version v20200206

the corrected data are cmorized and can be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/amip/v20200206
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip/r1i1p1f1

**version**
- v20200206

**sha256sum**
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip/.r1i1p1f1.sha256sum_v20200206

**Comment by monsieuralok** [comment]
@DirkOlivie @YanchunHe published

**Comment by YanchunHe** [comment]
cmorized new data version to fix bugs reported in issues: #109 #178 #179 

**data path**
- /projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/amip
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/amip

**version**
- v20200218

**sha256sum**
/projects/NS9034K/CMIP6/ScenarioMIP/NCC/NorESM2-LM/amip/
- .r1i1p1f1.sha256sum_v20200218

**Comment by monsieuralok** [comment]
@DirkOlivie @YanchunHe published

**Comment by YanchunHe** [comment]
(refer to suns@ynu.edu.cn)
> Dear Sir or Madam,

> I am downloading the NorESM2-LM's AMIP experiment outputs (from 1979 to 2014). I have found out that for the land variables, for example, total soil moisture "mrsos", the available nc files on the webpage https://esgf-node.llnl.gov/search/cmip6/ are : 

> mrsos_Lmon_NorESM2-LM_amip_r1i1p1f1_gn_197901-197912.nc
> mrsos_Lmon_NorESM2-LM_amip_r1i1p1f1_gn_198001-198912.nc
> mrsos_Lmon_NorESM2-LM_amip_r1i1p1f1_gn_199001-199912.nc
> mrsos_Lmon_NorESM2-LM_amip_r1i1p1f1_gn_200001-200904.nc
> mrsos_Lmon_NorESM2-LM_amip_r1i1p1f1_gn_201001-201412.nc

> That is, 8 months' data are missing (200905-200912). And it happens to all other land variables. Could you help me with it? I do need the whole datasets for my research as soon as possible.

**Comment by YanchunHe** [comment]
I checked this, and find the months 5-12 are missing in the original model output.

```
/projects/NS9560K/noresm/cases/NFHISTnorpddmsbc_f19_mg17_20190807/lnd/hist
$ cdo showdate NFHISTnorpddmsbc_f19_mg17_20190807.clm2.h0.2009-02-01-00000.nc
2009-02-01  2009-03-01  2009-04-01  2009-05-01
```

**Comment by DirkOlivie** [comment]
The data is indeed lacking.

I will rerun the period 2005-2009 (starting from a 2005-01-01 restart).   Once finshed, I will upload the clm2.h0 files to nird, and inform via this way.

**Comment by YanchunHe** [comment]
Thanks @DirkOlivie 

You can overwrite the old incomplete files, or put to new place.

**Comment by DirkOlivie** [comment]
@YanchunHe 
I have rerun the period 2005-2009 and uploaded the file NFHISTnorpddmsbc_f19_mg17_20190807.clm2.h0.2009-02-01-00000.nc to nird (the old corrupt file is still on nird but has now "old" in its name).

I have checked the results for these 5 years and they are still bit-identical with the original simulation.

If other files are needed from this period, I can upload them also (from vilje) to nird.  I'll keep the files for a few extra weeks on vilje.

**Comment by YanchunHe** [comment]
> @YanchunHe
> I have rerun the period 2005-2009 and uploaded the file NFHISTnorpddmsbc_f19_mg17_20190807.clm2.h0.2009-02-01-00000.nc to nird (the old corrupt file is still on nird but has now "old" in its name).
> 
> I have checked the results for these 5 years and they are still bit-identical with the original simulation.
> 
> If other files are needed from this period, I can upload them also (from vilje) to nird. I'll keep the files for a few extra weeks on vilje.

Thank you, @DirkOlivie 
I will redo the cmorization.

**Comment by YanchunHe** [comment]
Redo the cmorization for affected the Emon Lmon LImon fields.
Can be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/amip/v20200702b
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip/r1i1p1f1/

**version**
- v20200702b

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip/r1i1p1f1/
.r1i1p1f1.sha256sum_v20200702b

**Comment by DirkOlivie** [comment]
@YanchunHe 
I have removed from nird the file with "old" in its name :
NFHISTnorpddmsbc_f19_mg17_20190807.clm2.h0.2009-02-01-00000.old.nc

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
Cmorized with additional iLAMB variables (#262), AERday `zg500` (#263) and corrected `fNup` (#251).

They are ready to be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/amip/v20210203
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip

**version**
- v20210203

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip
- .r1i1p1f1.sha256sum_v20210203

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
@monsieuralok 
Please retract NorESM2-LM amip, all `6hrPlev` data.

**Comment by YanchunHe** [comment]
New cmorized 6hourly data are ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/amip
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip

**data version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip
- .r1i1p1f1.sha256sum_v20210319

**Comment by YanchunHe** [comment]
Hi @monsieuralok 
Please stop the publishing process, as there are other errors identified, refer to issue #272 . So we would better retract the data and republish all together.

**Comment by YanchunHe** [comment]
It is ready now to republish the above-mentioned new dataset v20210319.

This version fix issues: #269, #271, #272

@monsieuralok

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
Recmorize `sftlf` and `sftgif` related to issue #162
need to be published

**data path**

- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/amip
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip

**version**

- v20191108

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/amip
- .r1i1p1f1.sha256sum_v20191108c

**Comment by YanchunHe** [comment]
Hi @monsieuralok , have you published these new datasets? Thanks!

Yanchun

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by monsieuralok** [comment]
@YanchunHe retracted
