### ISSUE TITLE
[CMORization & ESGF-publication] piClim-spAer-anthro

### ISSUE THREAD

**Issue by Kirkevag** [NorESMhub/noresm2cmor#64]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases/piClim-SpAer-anthro

**experiment_id**
historical (with SpAer aerosols)

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
piClim-SpAer-anthro, 1-30
 
### Optional information

More details found at 
https://docs.google.com/spreadsheets/d/1vEkf5u4r-5JVMO4JOwLw7EY6RD59bnCpsk7YQs-5y-M/edit#gid=352840336
and at
https://docs.google.com/spreadsheets/d/1UkkJ9nDkz0xuN7RZvR93W9x2Obudr2aH5dH9T6WPod0/edit#gid=0

**parent_experiment_id**
e.g. 
piControl
historical
no parent
etc.,...

**parent_experiment_rip**
e.g., r1i1p1
'no parent'

**parent_time_units**
e.g.,
'days since 0421-01-01'

**branch_method**
e.g.,
'Hybrid-restart from year 1600-01-01 of piControl',

**other information**

The data are now being rsync'ed to nird, but will very soon be finalized. This is one of the experiments to be studied in a RFMIP-SpAer manuscript, so please give this at least MEDIUM priority.

**Comment by YanchunHe** [comment]
Hi Alf, please open the read access to this case folder. thanks!

**Comment by Kirkevag** [comment]
Try now, Yanchun. Cheers.

**Comment by YanchunHe** [comment]
works now, thanks!

**Comment by YanchunHe** [comment]
CMORized and ready to publish
**data path**
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-spAer-anthro

**version**
-v20190920

**other*
- PrePARE QC passed
- sha256sum updated

@Kirkevag Please have a look if it looks OK to publish to ESGF

**Comment by Kirkevag** [comment]
After a very quick check, I think it's ok to publish this to ESGF. Thank you, Yanchun!

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
This experiment is finished cmorizing with addtional fields. @jgriesfeller
You can try to check the result and post the the information here to require ESGF publish
(check the cmorized results, QCreport, links, sha256sum etc).

**Comment by YanchunHe** [comment]
Could you help to do this? @jgriesfeller
Thanks!

**Comment by YanchunHe** [comment]
This is cmorized with addtional fields

**data path**
- /tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-spAer-anthro
- /tos-project1/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-spAer-anthro

**version**
- v20191108

**sha256sum**
- /tos-project1/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-spAer-anthro/.r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@Kirkevag @YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #271, #272 and #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-spAer-anthro
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-spAer-anthro

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-spAer-anthro
- .r1i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published
