### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM historical ensemble member 3

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#69]
Full path to the case(s) of the experiment on NIRD
/projects/projects/NS9560K/noresm/cases/

experiment_id
historical

model_id
NorESM2-LM

CASENAME(s) and years to be CMORized
e.g.,
NHIST_03_f19_tn14_20190801 (1850-1949)
NHIST_03_f19_tn14_20190813 (1950-2014)
Optional information

parent_experiment_id
piControl

parent_experiment_rip
r1i1p1f1

parent_time_units
e.g.,
'days since 0421-01-01'

branch_method
'Hybrid-restart from year 1661-01-01 of piControl',

other information
(provide other information that might be useful)
Ensemble member 3 of historical

**Comment by YanchunHe** [comment]
CMORized and to be published

**data path**
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r3i1p1f1/

**version**
- v20190920

**other**

- sha256sum updated
- QC passed

**commit**
- 2d52690

**Comment by monsieuralok** [comment]
@YanchunHe @oyvindseland published

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
- /tos-project1/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r3i1p1f1/

**version**
- v20191108

**sha256sum**
- .r3i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
Cmorized with additional iLAMB variables (#262), AERday zg500 (#263) and corrected `fNup` (#251).

They are ready to be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical/v20210203
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical

**version**
- v20210203

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical
- .r3i1p1f1.sha256sum_v20210203

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
cmorized `burtFractionAll` related to issue #286 

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical/v20210818
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r3i1p1f1

**version**
- v20210818

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r3i1p1f1
- .r3i1p1f1.sha256sum_v20210818

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
cmorized `snowmxrat`  for Emon (#82) and 6hrPlevPt (#109).

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical/
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical

**version**
- v20210908

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical
- .r3i1p1f1.sha256sum_v20210908

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by monsieuralok** [comment]
@YanchunHe retracted
