### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - piClim-anthro

### ISSUE THREAD

**Issue by Kirkevag** [NorESMhub/noresm2cmor#70]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases/NF1850norbc_anthro2014_f19_20190811

**experiment_id**
<strike>e.g., RFMIP</strike>
- piClim-anthro

**model_id**
e.g.,
NorESM2-LM

**CASENAME(s) and years to be CMORized**
e.g., 
<strike>NF1850norbc_anthro2014_f19_20190811</strike>
NF1850norbc_anthro2014_f19_20190811, 1-30

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorwegianClimateCentre/noresm2cmor/blob/master/tables/CMIP6_CV.json)

<strike>
**parent_experiment_id**
e.g., 
piControl

**parent_experiment_rip**
e.g., r1i1p1
'no parent'

**parent_time_units**
e.g.,
'days since 0421-01-01'

**branch_method**
e.g.,
'Hybrid-restart from year 1751-01-01 of piControl',
</strike>

**other information**
(provide other information that might be useful)
e.g., realisation, initialisation, etc...
and the cases name and path to the parent experiment, etc

This is requested as input to a RFMIP paper by the end of October, so please give it a high prioity.

**Comment by YanchunHe** [comment]
CMORized and ready to publish

**data path**
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-anthro

**version**
- v20190920

**other**
- sha256sum updated
- PrePARE QC passed.

**commit**
- f068b61

**Comment by monsieuralok** [comment]
@YanchunHe @Kirkevag  published

**Comment by YanchunHe** [comment]
cmorized with addtional fields

**data path**
- /tos-project1/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-anthro/r1i1p1f1/

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@Kirkevag @YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #271, #272 and #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/piClim-anthro
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-anthro

**version**
- v20210319

**sha256sum**
- /projects/NS9034K/CMIP6/AerChemMIP/NCC/NorESM2-LM/piClim-anthro
- .r1i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published
