### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - piClim-histaer

### ISSUE THREAD

**Issue by DirkOlivie** [NorESMhub/noresm2cmor#87]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/noresm/cases

**experiment_id**
piClim-histaer

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NFHISTnorpibc_aeroxidonly_f19_20190810, 1850-2014

### Optional information

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 0421-01-01'

**branch_method**
'Hybrid-restart from year 1600-01-01 of piControl'

**other information**

**Comment by YanchunHe** [comment]
CMORized and ready to publish

**data path**
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-histaer/r1i1p1f1

**version**
- v20190920

**sha256sum**
- .r1i1p1f1.sha256sum_v20190920

**Comment by monsieuralok** [comment]
@DirkOlivie @YanchunHe published

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
- /tos-project1/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-histaer/r1i1p1f1/

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@Kirkevag @YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #271, #272 and #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-histaer
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-histaer

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-histaer
- .r1i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published
